export type AboutContent = {
  badge: string
  heroTitle: string
  heroDesc: string
  stats: { value: string; label: string }[]
  missionTitle: string
  mission1: string
  mission2: string
  standardsTitle: string
  standards: { badge: string; title: string; description: string; badgeColor: string }[]
  coversTitle: string
  categories: { icon: string; name: string; description: string }[]
  principlesTitle: string
  principles: { icon: string; text: string }[]
  ctaTitle: string
  ctaDesc: string
  ctaBtn: string
}

const data: Record<string, AboutContent> = {
  en: {
    badge: '🧮 About SolviqLab',
    heroTitle: 'Solving Real Problems,\nCompletely Free',
    heroDesc: 'SolviqLab is a platform of free, professional-grade calculators, science-backed quizzes, and AI health & finance coaching. Built on WHO, CFPB, and NIST standards. No ads. No sign-up required. Just accurate answers.',
    stats: [
      { value: '36+', label: 'Free Calculators' },
      { value: '10', label: 'Quizzes' },
      { value: '2', label: 'AI Coaches' },
      { value: '100%', label: 'Free, No Sign-up' },
    ],
    missionTitle: 'Our Mission',
    mission1: 'Every person deserves access to the same tools that professionals use — without paywalls, subscriptions, or confusing interfaces. We build calculators that give clear, accurate answers and explain the math behind them.',
    mission2: "Whether you're planning your retirement, tracking your health, getting coaching from our AI, or splitting a restaurant bill — SolviqLab has the right tool, available instantly, in your language.",
    standardsTitle: 'Built on Trusted Standards',
    standards: [
      { badge: 'WHO', title: 'World Health Organization', description: 'Health calculators (BMI, BMR, body fat, ideal weight) follow WHO clinical guidelines and reference ranges.', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
      { badge: 'CFPB', title: 'Consumer Financial Protection Bureau', description: 'Financial calculators (mortgage, loan, compound interest) comply with CFPB disclosure standards.', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
      { badge: 'NIST', title: 'National Institute of Standards & Technology', description: 'Unit converters use NIST and ISO measurement standards for maximum accuracy.', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
    ],
    coversTitle: 'What We Cover',
    categories: [
      { icon: '❤️', name: 'Health', description: 'BMI, BMR, TDEE, body fat, ideal weight, calorie deficit, sleep, ovulation, pregnancy' },
      { icon: '💰', name: 'Finance', description: 'Mortgage, loan, compound interest, retirement, savings, tax, salary, VAT, discount, tip' },
      { icon: '🧮', name: 'Math', description: 'Percentage, fraction, ratio, average, scientific notation' },
      { icon: '🔄', name: 'Conversion', description: 'Length, weight, temperature, area, volume, currency' },
    ],
    principlesTitle: 'Our Principles',
    principles: [
      { icon: '🆓', text: 'Always free — no subscriptions, no paywalls, no hidden fees' },
      { icon: '🔒', text: 'No data collection — all calculations happen in your browser' },
      { icon: '🌍', text: 'Available in 10 languages — English, Ukrainian, Spanish, Portuguese, French, German, Polish, Turkish, Italian, Dutch' },
      { icon: '📐', text: 'Formula transparency — every result shows the math behind it' },
      { icon: '⚡', text: 'Instant results — no loading spinners, no waiting' },
    ],
    ctaTitle: 'Ready to get started?',
    ctaDesc: 'Browse 36+ free tools across health, finance, math, and conversions.',
    ctaBtn: 'Browse All Calculators',
  },
  uk: {
    badge: '🧮 Про SolviqLab',
    heroTitle: 'Вирішуємо реальні проблеми,\nповністю безкоштовно',
    heroDesc: "SolviqLab — платформа безкоштовних професійних калькуляторів, наукових тестів та ШІ-коучингу для здоров'я і фінансів. Побудовано на стандартах ВООЗ, CFPB та NIST. Без реклами. Без реєстрації. Тільки точні відповіді.",
    stats: [
      { value: '36+', label: 'Калькуляторів' },
      { value: '10', label: 'Тестів' },
      { value: '2', label: 'ШІ-коучі' },
      { value: '100%', label: 'Безкоштовно' },
    ],
    missionTitle: 'Наша місія',
    mission1: "Кожна людина заслуговує доступу до тих самих інструментів, якими користуються професіонали — без платних стін, підписок або заплутаних інтерфейсів. Ми створюємо калькулятори, які дають чіткі й точні відповіді та пояснюють математику за ними.",
    mission2: "Плануєте пенсію, відстежуєте здоров'я, консультуєтесь з нашим ШІ, чи просто ділите рахунок у ресторані — SolviqLab має потрібний інструмент, доступний миттєво, вашою мовою.",
    standardsTitle: 'Засновано на перевірених стандартах',
    standards: [
      { badge: 'ВООЗ', title: 'Всесвітня організація охорони здоров\'я', description: "Калькулятори здоров'я (ІМТ, BMR, відсоток жиру, ідеальна вага) відповідають клінічним настановам і довідковим діапазонам ВООЗ.", badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
      { badge: 'CFPB', title: 'Бюро фінансового захисту споживачів', description: 'Фінансові калькулятори (іпотека, кредит, складні відсотки) відповідають стандартам розкриття інформації CFPB.', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
      { badge: 'NIST', title: 'Національний інститут стандартів і технологій', description: 'Конвертери одиниць використовують стандарти вимірювань NIST та ISO для максимальної точності.', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
    ],
    coversTitle: 'Що ми охоплюємо',
    categories: [
      { icon: '❤️', name: "Здоров'я", description: "ІМТ, BMR, TDEE, відсоток жиру, ідеальна вага, дефіцит калорій, сон, овуляція, вагітність" },
      { icon: '💰', name: 'Фінанси', description: 'Іпотека, кредит, складні відсотки, пенсія, заощадження, податки, зарплата, ПДВ, знижка, чайові' },
      { icon: '🧮', name: 'Математика', description: 'Відсотки, дроби, пропорції, середнє, науковий запис' },
      { icon: '🔄', name: 'Конвертація', description: 'Довжина, вага, температура, площа, об\'єм, валюта' },
    ],
    principlesTitle: 'Наші принципи',
    principles: [
      { icon: '🆓', text: 'Завжди безкоштовно — без підписок, платних стін та прихованих платежів' },
      { icon: '🔒', text: 'Без збору даних — всі обчислення відбуваються у вашому браузері' },
      { icon: '🌍', text: 'Доступно на 10 мовах — англійська, українська, іспанська, португальська, французька, німецька, польська, турецька, італійська, нідерландська' },
      { icon: '📐', text: 'Прозорість формул — кожен результат показує математику за ним' },
      { icon: '⚡', text: 'Миттєві результати — без завантажень та очікування' },
    ],
    ctaTitle: 'Готові почати?',
    ctaDesc: 'Перегляньте 36+ безкоштовних інструментів для здоров\'я, фінансів, математики та конвертацій.',
    ctaBtn: 'Переглянути всі калькулятори',
  },
  es: {
    badge: '🧮 Acerca de SolviqLab',
    heroTitle: 'Resolviendo Problemas Reales,\nCompletamente Gratis',
    heroDesc: 'SolviqLab es una plataforma de calculadoras profesionales gratuitas, tests científicos y coaching IA para salud y finanzas. Construida sobre estándares OMS, CFPB y NIST. Sin anuncios. Sin registro. Solo respuestas precisas.',
    stats: [
      { value: '36+', label: 'Calculadoras' },
      { value: '10', label: 'Tests' },
      { value: '2', label: 'Coaches IA' },
      { value: '100%', label: 'Gratis' },
    ],
    missionTitle: 'Nuestra Misión',
    mission1: 'Toda persona merece acceso a las mismas herramientas que usan los profesionales — sin muros de pago, suscripciones ni interfaces confusas. Construimos calculadoras que dan respuestas claras y precisas y explican las matemáticas detrás de ellas.',
    mission2: 'Ya sea que estés planificando tu jubilación, monitoreando tu salud, consultando con nuestra IA, o dividiendo la cuenta del restaurante — SolviqLab tiene la herramienta adecuada, disponible instantáneamente, en tu idioma.',
    standardsTitle: 'Basado en Estándares de Confianza',
    standards: [
      { badge: 'OMS', title: 'Organización Mundial de la Salud', description: 'Las calculadoras de salud (IMC, TMB, grasa corporal, peso ideal) siguen las guías clínicas y rangos de referencia de la OMS.', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
      { badge: 'CFPB', title: 'Oficina de Protección Financiera del Consumidor', description: 'Las calculadoras financieras (hipoteca, préstamo, interés compuesto) cumplen con los estándares de divulgación CFPB.', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
      { badge: 'NIST', title: 'Instituto Nacional de Estándares y Tecnología', description: 'Los conversores de unidades usan los estándares de medición NIST e ISO para máxima precisión.', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
    ],
    coversTitle: 'Lo Que Cubrimos',
    categories: [
      { icon: '❤️', name: 'Salud', description: 'IMC, TMB, TDEE, grasa corporal, peso ideal, déficit calórico, sueño, ovulación, embarazo' },
      { icon: '💰', name: 'Finanzas', description: 'Hipoteca, préstamo, interés compuesto, jubilación, ahorros, impuestos, salario, IVA, descuento, propina' },
      { icon: '🧮', name: 'Matemáticas', description: 'Porcentaje, fracción, ratio, promedio, notación científica' },
      { icon: '🔄', name: 'Conversión', description: 'Longitud, peso, temperatura, área, volumen, moneda' },
    ],
    principlesTitle: 'Nuestros Principios',
    principles: [
      { icon: '🆓', text: 'Siempre gratis — sin suscripciones, sin muros de pago, sin tarifas ocultas' },
      { icon: '🔒', text: 'Sin recopilación de datos — todos los cálculos ocurren en tu navegador' },
      { icon: '🌍', text: 'Disponible en 10 idiomas — inglés, ucraniano, español, portugués, francés, alemán, polaco, turco, italiano, holandés' },
      { icon: '📐', text: 'Transparencia de fórmulas — cada resultado muestra las matemáticas detrás' },
      { icon: '⚡', text: 'Resultados instantáneos — sin spinners de carga, sin esperas' },
    ],
    ctaTitle: '¿Listo para empezar?',
    ctaDesc: 'Explora 36+ herramientas gratuitas para salud, finanzas, matemáticas y conversiones.',
    ctaBtn: 'Ver Todas las Calculadoras',
  },
  fr: {
    badge: '🧮 À propos de SolviqLab',
    heroTitle: 'Résoudre de Vrais Problèmes,\nEntièrement Gratuitement',
    heroDesc: "SolviqLab est une plateforme de calculatrices professionnelles gratuites, de tests scientifiques et de coaching IA pour la santé et les finances. Construit sur les normes OMS, CFPB et NIST. Sans publicité. Sans inscription. Juste des réponses précises.",
    stats: [
      { value: '36+', label: 'Calculatrices' },
      { value: '10', label: 'Tests' },
      { value: '2', label: 'Coachs IA' },
      { value: '100%', label: 'Gratuit' },
    ],
    missionTitle: 'Notre Mission',
    mission1: "Chaque personne mérite d'accéder aux mêmes outils que les professionnels — sans paywalls, abonnements ou interfaces confuses. Nous construisons des calculatrices qui donnent des réponses claires et précises et expliquent les maths qui les sous-tendent.",
    mission2: "Que vous planifiiez votre retraite, surveilliez votre santé, consultiez notre IA, ou divisiez l'addition au restaurant — SolviqLab a le bon outil, disponible instantanément, dans votre langue.",
    standardsTitle: 'Fondé sur des Normes Fiables',
    standards: [
      { badge: 'OMS', title: 'Organisation Mondiale de la Santé', description: 'Les calculatrices de santé (IMC, BMR, graisse corporelle, poids idéal) suivent les directives cliniques et plages de référence de l\'OMS.', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
      { badge: 'CFPB', title: 'Bureau de Protection Financière des Consommateurs', description: 'Les calculatrices financières (hypothèque, prêt, intérêts composés) respectent les normes de divulgation CFPB.', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
      { badge: 'NIST', title: 'Institut National des Normes et de la Technologie', description: 'Les convertisseurs d\'unités utilisent les normes de mesure NIST et ISO pour une précision maximale.', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
    ],
    coversTitle: 'Ce Que Nous Couvrons',
    categories: [
      { icon: '❤️', name: 'Santé', description: 'IMC, BMR, TDEE, graisse corporelle, poids idéal, déficit calorique, sommeil, ovulation, grossesse' },
      { icon: '💰', name: 'Finance', description: 'Hypothèque, prêt, intérêts composés, retraite, épargne, impôts, salaire, TVA, remise, pourboire' },
      { icon: '🧮', name: 'Maths', description: 'Pourcentage, fraction, ratio, moyenne, notation scientifique' },
      { icon: '🔄', name: 'Conversion', description: 'Longueur, poids, température, surface, volume, monnaie' },
    ],
    principlesTitle: 'Nos Principes',
    principles: [
      { icon: '🆓', text: 'Toujours gratuit — sans abonnements, sans paywalls, sans frais cachés' },
      { icon: '🔒', text: 'Aucune collecte de données — tous les calculs s\'effectuent dans votre navigateur' },
      { icon: '🌍', text: 'Disponible en 10 langues — anglais, ukrainien, espagnol, portugais, français, allemand, polonais, turc, italien, néerlandais' },
      { icon: '📐', text: 'Transparence des formules — chaque résultat montre les maths derrière' },
      { icon: '⚡', text: 'Résultats instantanés — sans indicateurs de chargement, sans attente' },
    ],
    ctaTitle: 'Prêt à commencer ?',
    ctaDesc: 'Parcourez 36+ outils gratuits pour la santé, les finances, les maths et les conversions.',
    ctaBtn: 'Voir Toutes les Calculatrices',
  },
  de: {
    badge: '🧮 Über SolviqLab',
    heroTitle: 'Echte Probleme lösen,\nvöllig kostenlos',
    heroDesc: 'SolviqLab ist eine Plattform für kostenlose professionelle Rechner, wissenschaftliche Tests und KI-Coaching für Gesundheit und Finanzen. Basierend auf WHO-, CFPB- und NIST-Standards. Keine Werbung. Keine Anmeldung. Nur präzise Antworten.',
    stats: [
      { value: '36+', label: 'Rechner' },
      { value: '10', label: 'Tests' },
      { value: '2', label: 'KI-Coaches' },
      { value: '100%', label: 'Kostenlos' },
    ],
    missionTitle: 'Unsere Mission',
    mission1: 'Jeder Mensch verdient Zugang zu denselben Werkzeugen, die Profis verwenden — ohne Paywalls, Abonnements oder verwirrende Schnittstellen. Wir entwickeln Rechner, die klare, präzise Antworten geben und die Mathematik dahinter erklären.',
    mission2: 'Ob Sie Ihren Ruhestand planen, Ihre Gesundheit überwachen, unsere KI konsultieren oder eine Restaurantrechnung aufteilen — SolviqLab hat das richtige Tool, sofort verfügbar, in Ihrer Sprache.',
    standardsTitle: 'Basierend auf vertrauenswürdigen Standards',
    standards: [
      { badge: 'WHO', title: 'Weltgesundheitsorganisation', description: 'Gesundheitsrechner (BMI, BMR, Körperfett, Idealgewicht) folgen den klinischen Richtlinien und Referenzbereichen der WHO.', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
      { badge: 'CFPB', title: 'Consumer Financial Protection Bureau', description: 'Finanzrechner (Hypothek, Darlehen, Zinseszins) entsprechen den CFPB-Offenlegungsstandards.', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
      { badge: 'NIST', title: 'Nationales Institut für Standards und Technologie', description: 'Einheitenumrechner verwenden NIST- und ISO-Messstandards für maximale Genauigkeit.', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
    ],
    coversTitle: 'Was wir abdecken',
    categories: [
      { icon: '❤️', name: 'Gesundheit', description: 'BMI, BMR, TDEE, Körperfett, Idealgewicht, Kaloriendefizit, Schlaf, Eisprung, Schwangerschaft' },
      { icon: '💰', name: 'Finanzen', description: 'Hypothek, Darlehen, Zinseszins, Rente, Ersparnisse, Steuern, Gehalt, MwSt., Rabatt, Trinkgeld' },
      { icon: '🧮', name: 'Mathematik', description: 'Prozent, Bruch, Verhältnis, Durchschnitt, wissenschaftliche Notation' },
      { icon: '🔄', name: 'Umrechnung', description: 'Länge, Gewicht, Temperatur, Fläche, Volumen, Währung' },
    ],
    principlesTitle: 'Unsere Grundsätze',
    principles: [
      { icon: '🆓', text: 'Immer kostenlos — keine Abonnements, keine Paywalls, keine versteckten Gebühren' },
      { icon: '🔒', text: 'Keine Datenerfassung — alle Berechnungen erfolgen in Ihrem Browser' },
      { icon: '🌍', text: 'In 10 Sprachen verfügbar — Englisch, Ukrainisch, Spanisch, Portugiesisch, Französisch, Deutsch, Polnisch, Türkisch, Italienisch, Niederländisch' },
      { icon: '📐', text: 'Formel-Transparenz — jedes Ergebnis zeigt die Mathematik dahinter' },
      { icon: '⚡', text: 'Sofortige Ergebnisse — keine Ladeanimationen, kein Warten' },
    ],
    ctaTitle: 'Bereit loszulegen?',
    ctaDesc: 'Stöbern Sie in 36+ kostenlosen Tools für Gesundheit, Finanzen, Mathematik und Konvertierungen.',
    ctaBtn: 'Alle Rechner ansehen',
  },
  it: {
    badge: '🧮 Chi siamo',
    heroTitle: 'Risolvere Problemi Reali,\nCompletamente Gratis',
    heroDesc: 'SolviqLab è una piattaforma di calcolatrici professionali gratuite, test scientifici e coaching IA per salute e finanza. Costruita su standard OMS, CFPB e NIST. Nessuna pubblicità. Nessuna registrazione. Solo risposte precise.',
    stats: [
      { value: '36+', label: 'Calcolatori' },
      { value: '10', label: 'Test' },
      { value: '2', label: 'Coach IA' },
      { value: '100%', label: 'Gratuito' },
    ],
    missionTitle: 'La Nostra Missione',
    mission1: 'Ogni persona merita accesso agli stessi strumenti usati dai professionisti — senza paywall, abbonamenti o interfacce confuse. Costruiamo calcolatrici che danno risposte chiare e precise e spiegano la matematica dietro di esse.',
    mission2: 'Che tu stia pianificando la pensione, monitorando la salute, consultando la nostra IA o dividendo il conto al ristorante — SolviqLab ha lo strumento giusto, disponibile istantaneamente, nella tua lingua.',
    standardsTitle: 'Basato su Standard Affidabili',
    standards: [
      { badge: 'OMS', title: 'Organizzazione Mondiale della Sanità', description: 'I calcolatori della salute (IMC, BMR, grasso corporeo, peso ideale) seguono le linee guida cliniche e i range di riferimento OMS.', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
      { badge: 'CFPB', title: 'Ufficio di Protezione Finanziaria dei Consumatori', description: 'I calcolatori finanziari (mutuo, prestito, interesse composto) rispettano gli standard di divulgazione CFPB.', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
      { badge: 'NIST', title: 'Istituto Nazionale di Standard e Tecnologia', description: 'I convertitori di unità usano gli standard di misurazione NIST e ISO per la massima precisione.', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
    ],
    coversTitle: 'Cosa Copriamo',
    categories: [
      { icon: '❤️', name: 'Salute', description: 'IMC, BMR, TDEE, grasso corporeo, peso ideale, deficit calorico, sonno, ovulazione, gravidanza' },
      { icon: '💰', name: 'Finanza', description: 'Mutuo, prestito, interesse composto, pensione, risparmio, tasse, stipendio, IVA, sconto, mancia' },
      { icon: '🧮', name: 'Matematica', description: 'Percentuale, frazione, rapporto, media, notazione scientifica' },
      { icon: '🔄', name: 'Conversione', description: 'Lunghezza, peso, temperatura, area, volume, valuta' },
    ],
    principlesTitle: 'I Nostri Principi',
    principles: [
      { icon: '🆓', text: 'Sempre gratuito — nessun abbonamento, nessun paywall, nessuna tariffa nascosta' },
      { icon: '🔒', text: 'Nessuna raccolta dati — tutti i calcoli avvengono nel tuo browser' },
      { icon: '🌍', text: 'Disponibile in 10 lingue — inglese, ucraino, spagnolo, portoghese, francese, tedesco, polacco, turco, italiano, olandese' },
      { icon: '📐', text: 'Trasparenza delle formule — ogni risultato mostra la matematica dietro' },
      { icon: '⚡', text: 'Risultati istantanei — nessun caricamento, nessuna attesa' },
    ],
    ctaTitle: 'Pronto per iniziare?',
    ctaDesc: 'Sfoglia 36+ strumenti gratuiti per salute, finanza, matematica e conversioni.',
    ctaBtn: 'Vedi Tutti i Calcolatori',
  },
  tr: {
    badge: '🧮 SolviqLab Hakkında',
    heroTitle: 'Gerçek Sorunları Çözme,\nTamamen Ücretsiz',
    heroDesc: "SolviqLab, sağlık ve finans için ücretsiz profesyonel hesap makineleri, bilimsel testler ve yapay zeka koçluğu sunan bir platformdur. WHO, CFPB ve NIST standartları üzerine inşa edilmiştir. Reklam yok. Kayıt gerekmez. Sadece doğru yanıtlar.",
    stats: [
      { value: '36+', label: 'Hesap Makinesi' },
      { value: '10', label: 'Test' },
      { value: '2', label: 'Yapay Zeka Koçu' },
      { value: '100%', label: 'Ücretsiz' },
    ],
    missionTitle: 'Misyonumuz',
    mission1: "Her insan, profesyonellerin kullandığı araçlara erişmeyi hak eder — ödeme duvarları, abonelikler veya kafa karıştırıcı arayüzler olmadan. Net, doğru yanıtlar veren ve arkasındaki matematiği açıklayan hesap makineleri geliştiriyoruz.",
    mission2: "Emekliliğinizi planlıyor, sağlığınızı takip ediyor, yapay zekamıza danışıyor veya restoran hesabını bölüyor olun — SolviqLab'da doğru araç, anında, kendi dilinizde mevcuttur.",
    standardsTitle: 'Güvenilir Standartlara Dayalı',
    standards: [
      { badge: 'WHO', title: 'Dünya Sağlık Örgütü', description: 'Sağlık hesap makineleri (VKİ, BMR, vücut yağı, ideal kilo) WHO klinik kılavuzlarını ve referans aralıklarını takip eder.', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
      { badge: 'CFPB', title: 'Tüketici Finansal Koruma Bürosu', description: 'Finans hesap makineleri (mortgage, kredi, bileşik faiz) CFPB açıklama standartlarına uygundur.', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
      { badge: 'NIST', title: 'Ulusal Standartlar ve Teknoloji Enstitüsü', description: 'Birim dönüştürücüler maksimum doğruluk için NIST ve ISO ölçüm standartlarını kullanır.', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
    ],
    coversTitle: 'Ne Kapsıyoruz',
    categories: [
      { icon: '❤️', name: 'Sağlık', description: 'VKİ, BMR, TDEE, vücut yağı, ideal kilo, kalori açığı, uyku, yumurtlama, gebelik' },
      { icon: '💰', name: 'Finans', description: 'Mortgage, kredi, bileşik faiz, emeklilik, tasarruf, vergi, maaş, KDV, indirim, bahşiş' },
      { icon: '🧮', name: 'Matematik', description: 'Yüzde, kesir, oran, ortalama, bilimsel gösterim' },
      { icon: '🔄', name: 'Dönüşüm', description: 'Uzunluk, ağırlık, sıcaklık, alan, hacim, para birimi' },
    ],
    principlesTitle: 'İlkelerimiz',
    principles: [
      { icon: '🆓', text: 'Her zaman ücretsiz — abonelik yok, ödeme duvarı yok, gizli ücret yok' },
      { icon: '🔒', text: 'Veri toplama yok — tüm hesaplamalar tarayıcınızda gerçekleşir' },
      { icon: '🌍', text: '10 dilde kullanılabilir — İngilizce, Ukraynaca, İspanyolca, Portekizce, Fransızca, Almanca, Lehçe, Türkçe, İtalyanca, Hollandaca' },
      { icon: '📐', text: 'Formül şeffaflığı — her sonuç arkasındaki matematiği gösterir' },
      { icon: '⚡', text: 'Anlık sonuçlar — yükleme göstergesi yok, bekleme yok' },
    ],
    ctaTitle: 'Başlamaya hazır mısınız?',
    ctaDesc: 'Sağlık, finans, matematik ve dönüşümler için 36+ ücretsiz aracı keşfedin.',
    ctaBtn: 'Tüm Hesaplayıcıları Gör',
  },
  pt: {
    badge: '🧮 Sobre o SolviqLab',
    heroTitle: 'Resolvendo Problemas Reais,\nCompletamente Grátis',
    heroDesc: 'SolviqLab é uma plataforma de calculadoras profissionais gratuitas, testes científicos e coaching com IA para saúde e finanças. Construída sobre os padrões OMS, CFPB e NIST. Sem anúncios. Sem cadastro. Só respostas precisas.',
    stats: [
      { value: '36+', label: 'Calculadoras' },
      { value: '10', label: 'Testes' },
      { value: '2', label: 'Coaches de IA' },
      { value: '100%', label: 'Grátis' },
    ],
    missionTitle: 'Nossa Missão',
    mission1: 'Toda pessoa merece acesso às mesmas ferramentas que os profissionais usam — sem paywalls, assinaturas ou interfaces confusas. Criamos calculadoras que dão respostas claras e precisas e explicam a matemática por trás delas.',
    mission2: 'Seja planejando sua aposentadoria, monitorando sua saúde, consultando nossa IA ou dividindo a conta do restaurante — SolviqLab tem a ferramenta certa, disponível instantaneamente, no seu idioma.',
    standardsTitle: 'Baseado em Padrões Confiáveis',
    standards: [
      { badge: 'OMS', title: 'Organização Mundial da Saúde', description: 'As calculadoras de saúde (IMC, TMB, gordura corporal, peso ideal) seguem as diretrizes clínicas e intervalos de referência da OMS.', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
      { badge: 'CFPB', title: 'Agência de Proteção Financeira do Consumidor', description: 'As calculadoras financeiras (hipoteca, empréstimo, juros compostos) cumprem os padrões de divulgação do CFPB.', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
      { badge: 'NIST', title: 'Instituto Nacional de Padrões e Tecnologia', description: 'Os conversores de unidades usam os padrões de medição NIST e ISO para máxima precisão.', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
    ],
    coversTitle: 'O Que Cobrimos',
    categories: [
      { icon: '❤️', name: 'Saúde', description: 'IMC, TMB, TDEE, gordura corporal, peso ideal, déficit calórico, sono, ovulação, gravidez' },
      { icon: '💰', name: 'Finanças', description: 'Hipoteca, empréstimo, juros compostos, aposentadoria, poupança, imposto, salário, IVA, desconto, gorjeta' },
      { icon: '🧮', name: 'Matemática', description: 'Porcentagem, fração, razão, média, notação científica' },
      { icon: '🔄', name: 'Conversão', description: 'Comprimento, peso, temperatura, área, volume, moeda' },
    ],
    principlesTitle: 'Nossos Princípios',
    principles: [
      { icon: '🆓', text: 'Sempre grátis — sem assinaturas, sem paywalls, sem taxas ocultas' },
      { icon: '🔒', text: 'Sem coleta de dados — todos os cálculos acontecem no seu navegador' },
      { icon: '🌍', text: 'Disponível em 10 idiomas — inglês, ucraniano, espanhol, português, francês, alemão, polonês, turco, italiano, holandês' },
      { icon: '📐', text: 'Transparência de fórmulas — cada resultado mostra a matemática por trás' },
      { icon: '⚡', text: 'Resultados instantâneos — sem spinners de carregamento, sem espera' },
    ],
    ctaTitle: 'Pronto para começar?',
    ctaDesc: 'Explore 36+ ferramentas gratuitas para saúde, finanças, matemática e conversões.',
    ctaBtn: 'Ver Todas as Calculadoras',
  },
  pl: {
    badge: '🧮 O SolviqLab',
    heroTitle: 'Rozwiązywanie Prawdziwych Problemów,\nZupełnie Za Darmo',
    heroDesc: 'SolviqLab to platforma bezpłatnych profesjonalnych kalkulatorów, naukowych testów i coachingu AI dla zdrowia i finansów. Zbudowana na standardach WHO, CFPB i NIST. Bez reklam. Bez rejestracji. Tylko dokładne odpowiedzi.',
    stats: [
      { value: '36+', label: 'Kalkulatorów' },
      { value: '10', label: 'Testów' },
      { value: '2', label: 'Coachów AI' },
      { value: '100%', label: 'Za darmo' },
    ],
    missionTitle: 'Nasza Misja',
    mission1: 'Każda osoba zasługuje na dostęp do tych samych narzędzi, z których korzystają profesjonaliści — bez paywalli, subskrypcji ani mylących interfejsów. Tworzymy kalkulatory, które dają jasne, dokładne odpowiedzi i wyjaśniają matematykę za nimi.',
    mission2: 'Czy planujesz emeryturę, monitorujesz zdrowie, konsulujesz się z naszą AI, czy dzielisz rachunek w restauracji — SolviqLab ma właściwe narzędzie, dostępne natychmiast, w Twoim języku.',
    standardsTitle: 'Oparte na Zaufanych Standardach',
    standards: [
      { badge: 'WHO', title: 'Światowa Organizacja Zdrowia', description: 'Kalkulatory zdrowotne (BMI, BMR, tkanka tłuszczowa, idealna waga) stosują kliniczne wytyczne i zakresy referencyjne WHO.', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
      { badge: 'CFPB', title: 'Biuro Ochrony Finansowej Konsumentów', description: 'Kalkulatory finansowe (kredyt hipoteczny, pożyczka, odsetki składane) spełniają standardy CFPB.', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
      { badge: 'NIST', title: 'Narodowy Instytut Standardów i Technologii', description: 'Przeliczniki jednostek używają standardów pomiarowych NIST i ISO dla maksymalnej precyzji.', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
    ],
    coversTitle: 'Co Obejmujemy',
    categories: [
      { icon: '❤️', name: 'Zdrowie', description: 'BMI, BMR, TDEE, tkanka tłuszczowa, idealna waga, deficyt kaloryczny, sen, owulacja, ciąża' },
      { icon: '💰', name: 'Finanse', description: 'Kredyt hipoteczny, pożyczka, odsetki składane, emerytura, oszczędności, podatki, wynagrodzenie, VAT, rabat, napiwek' },
      { icon: '🧮', name: 'Matematyka', description: 'Procent, ułamek, stosunek, średnia, notacja naukowa' },
      { icon: '🔄', name: 'Przeliczniki', description: 'Długość, waga, temperatura, powierzchnia, objętość, waluta' },
    ],
    principlesTitle: 'Nasze Zasady',
    principles: [
      { icon: '🆓', text: 'Zawsze za darmo — bez subskrypcji, bez paywalli, bez ukrytych opłat' },
      { icon: '🔒', text: 'Brak zbierania danych — wszystkie obliczenia odbywają się w Twojej przeglądarce' },
      { icon: '🌍', text: 'Dostępne w 10 językach — angielski, ukraiński, hiszpański, portugalski, francuski, niemiecki, polski, turecki, włoski, niderlandzki' },
      { icon: '📐', text: 'Przejrzystość formuł — każdy wynik pokazuje matematykę za nim' },
      { icon: '⚡', text: 'Natychmiastowe wyniki — bez wskaźników ładowania, bez czekania' },
    ],
    ctaTitle: 'Gotowy do działania?',
    ctaDesc: 'Przeglądaj 36+ bezpłatnych narzędzi do zdrowia, finansów, matematyki i przeliczania.',
    ctaBtn: 'Zobacz Wszystkie Kalkulatory',
  },
  nl: {
    badge: '🧮 Over SolviqLab',
    heroTitle: 'Echte Problemen Oplossen,\nVolledig Gratis',
    heroDesc: 'SolviqLab is een platform van gratis professionele calculators, wetenschappelijke testen en AI-coaching voor gezondheid en financiën. Gebouwd op WHO-, CFPB- en NIST-standaarden. Geen advertenties. Geen registratie. Gewoon nauwkeurige antwoorden.',
    stats: [
      { value: '36+', label: 'Calculators' },
      { value: '10', label: 'Testen' },
      { value: '2', label: 'AI-coaches' },
      { value: '100%', label: 'Gratis' },
    ],
    missionTitle: 'Onze Missie',
    mission1: 'Iedereen verdient toegang tot dezelfde tools die professionals gebruiken — zonder paywalls, abonnementen of verwarrende interfaces. We bouwen calculators die duidelijke, nauwkeurige antwoorden geven en de wiskunde erachter uitleggen.',
    mission2: 'Of u nu uw pensioen plant, uw gezondheid bijhoudt, onze AI consulteert of een restaurantrekening deelt — SolviqLab heeft de juiste tool, direct beschikbaar, in uw taal.',
    standardsTitle: 'Gebaseerd op Vertrouwde Standaarden',
    standards: [
      { badge: 'WHO', title: 'Wereldgezondheidsorganisatie', description: 'Gezondheidscalculators (BMI, BMR, lichaamsvet, ideaal gewicht) volgen de klinische richtlijnen en referentiebereiken van de WHO.', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
      { badge: 'CFPB', title: 'Bureau voor Financiële Bescherming van Consumenten', description: 'Financiële calculators (hypotheek, lening, samengestelde rente) voldoen aan de CFPB-openbaarmakingsnormen.', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
      { badge: 'NIST', title: 'Nationaal Instituut voor Standaarden en Technologie', description: 'Eenheidsconverters gebruiken NIST- en ISO-meetstandaarden voor maximale nauwkeurigheid.', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
    ],
    coversTitle: 'Wat We Dekken',
    categories: [
      { icon: '❤️', name: 'Gezondheid', description: 'BMI, BMR, TDEE, lichaamsvet, ideaal gewicht, calorietekort, slaap, eisprong, zwangerschap' },
      { icon: '💰', name: 'Financiën', description: 'Hypotheek, lening, samengestelde rente, pensioen, spaargeld, belasting, salaris, btw, korting, fooi' },
      { icon: '🧮', name: 'Wiskunde', description: 'Percentage, breuk, verhouding, gemiddelde, wetenschappelijke notatie' },
      { icon: '🔄', name: 'Conversie', description: 'Lengte, gewicht, temperatuur, oppervlakte, volume, valuta' },
    ],
    principlesTitle: 'Onze Principes',
    principles: [
      { icon: '🆓', text: 'Altijd gratis — geen abonnementen, geen paywalls, geen verborgen kosten' },
      { icon: '🔒', text: 'Geen gegevensverzameling — alle berekeningen vinden plaats in uw browser' },
      { icon: '🌍', text: 'Beschikbaar in 10 talen — Engels, Oekraïens, Spaans, Portugees, Frans, Duits, Pools, Turks, Italiaans, Nederlands' },
      { icon: '📐', text: 'Formualtransparantie — elk resultaat toont de wiskunde erachter' },
      { icon: '⚡', text: 'Directe resultaten — geen laadspinners, geen wachten' },
    ],
    ctaTitle: 'Klaar om te beginnen?',
    ctaDesc: 'Blader door 36+ gratis tools voor gezondheid, financiën, wiskunde en conversies.',
    ctaBtn: 'Bekijk Alle Calculators',
  },
}

export function getAboutContent(lang: string): AboutContent {
  return data[lang] ?? data.en
}
