export type Section = { title: string; body: string }
export type ContactTopic = { icon: string; label: string; email: string; desc: string }

// ===== PRIVACY POLICY =====
const privacyData: Record<string, { lastUpdated: string; tldr: string; sections: Section[] }> = {
  en: {
    lastUpdated: 'July 27, 2026',
    tldr: "TL;DR — Calculations happen in your browser. We don't require registration. We don't sell your data. The AI coach uses DeepSeek API. Analytics only with your consent.",
    sections: [
      { title: '1. Who We Are', body: 'SolviqLab (solviqlab.com) is a free online calculator platform providing tools for health, finance, mathematics, and unit conversions. For privacy inquiries, contact us at privacy@solviqlab.com.' },
      { title: '2. What Data We Collect', body: 'We are designed to be private by default.\n\n• Calculations — all formulas run entirely in your browser. No calculation inputs or results are sent to our servers.\n• Quiz & assessment results — stored only in your browser\'s localStorage. We do not transmit them.\n• AI Coach sessions — when you interact with Mia or Alex, your messages are sent to the DeepSeek API to generate responses. No personally identifiable information is required. We do not store chat logs on our servers.\n• Analytics (optional) — if you accept analytics cookies, we use Microsoft Clarity. This data is anonymised and governed by Microsoft\'s Privacy Policy.' },
      { title: '3. Cookies & Local Storage', body: 'We use browser localStorage to remember your preferences (theme, language, quiz scores, favourite calculators). These stay on your device and are never sent to our servers.\n\nIf you accept optional analytics cookies, we set cookies for Microsoft Clarity. You can change your preferences at any time using the Cookie Settings link in the footer.' },
      { title: '4. Third-Party Services', body: '• DeepSeek API — powers our AI coaching features. When you use Mia or Alex, conversation messages are processed by DeepSeek. See: https://www.deepseek.com/privacy\n• Microsoft Clarity — session analytics, only with your consent. See: https://privacy.microsoft.com\n• Vercel — our hosting provider processes request metadata (IP address, user agent) under their Privacy Policy.' },
      { title: '5. Your Rights (GDPR / CCPA)', body: 'You have the right to:\n• Access the data we hold about you\n• Request deletion of your data\n• Object to processing\n• Withdraw consent at any time\n\nSince we store almost nothing server-side, most of your data is already under your control (it\'s in your browser). To exercise any right, email us at privacy@solviqlab.com.' },
      { title: '6. Data Retention', body: 'We do not retain calculation inputs or results. AI coach conversation data processed via DeepSeek API is governed by their retention policies. Analytics data collected via Microsoft Clarity is retained per their terms.' },
      { title: '7. Children', body: 'SolviqLab is not directed at children under 13. We do not knowingly collect personal data from children. If you believe a child has provided personal data, contact us and we will delete it promptly.' },
      { title: '8. Changes to This Policy', body: 'We may update this policy from time to time. The date at the top of this page will reflect the latest revision. Continued use of SolviqLab after changes constitutes acceptance of the updated policy.' },
      { title: '9. Contact', body: 'For any privacy-related questions or requests:\nEmail: privacy@solviqlab.com\nWebsite: https://solviqlab.com/en/contact' },
    ],
  },
  uk: {
    lastUpdated: '27 липня 2026',
    tldr: "Коротко — обчислення відбуваються у вашому браузері. Реєстрація не потрібна. Ми не продаємо ваші дані. ШІ-коуч використовує DeepSeek API. Аналітика — лише за вашою згодою.",
    sections: [
      { title: '1. Хто ми', body: "SolviqLab (solviqlab.com) — безкоштовна онлайн-платформа калькуляторів для здоров'я, фінансів, математики та конвертації одиниць. З питань конфіденційності: privacy@solviqlab.com." },
      { title: '2. Які дані ми збираємо', body: "Ми розроблені з дотриманням конфіденційності за замовчуванням.\n\n• Обчислення — всі формули виконуються виключно у вашому браузері. Жодні дані не надсилаються на наші сервери.\n• Результати тестів — зберігаються лише у localStorage вашого браузера. Ми їх не передаємо.\n• Сесії ШІ-коуча — коли ви спілкуєтеся з Mia або Alex, ваші повідомлення надсилаються до DeepSeek API. Особисті дані не вимагаються. Ми не зберігаємо журнали чатів.\n• Аналітика (за бажанням) — якщо ви прийняли аналітичні cookies, ми використовуємо Microsoft Clarity. Дані анонімізовані та регулюються Політикою конфіденційності Microsoft." },
      { title: '3. Файли cookie та локальне сховище', body: "Ми використовуємо localStorage для збереження ваших налаштувань (тема, мова, результати тестів, обрані калькулятори). Вони залишаються на вашому пристрої і ніколи не надсилаються на наші сервери.\n\nЯкщо ви прийняли необов'язкові аналітичні cookies, ми встановлюємо cookies для Microsoft Clarity. Ви можете змінити налаштування в будь-який час через посилання «Налаштування cookie» у підвалі." },
      { title: '4. Сторонні сервіси', body: '• DeepSeek API — забезпечує функції ШІ-коучингу. Докладніше: https://www.deepseek.com/privacy\n• Microsoft Clarity — аналітика сесій, лише за вашою згодою. Докладніше: https://privacy.microsoft.com\n• Vercel — наш хостинг-провайдер обробляє метадані запитів (IP-адреса, user agent) відповідно до їхньої Політики конфіденційності.' },
      { title: '5. Ваші права (GDPR / CCPA)', body: "Ви маєте право:\n• Отримати доступ до даних, які ми зберігаємо про вас\n• Вимагати видалення ваших даних\n• Заперечити проти обробки\n• Відкликати згоду в будь-який час\n\nОскільки ми майже нічого не зберігаємо на сервері, більшість ваших даних вже під вашим контролем (вони у вашому браузері). Напишіть нам: privacy@solviqlab.com." },
      { title: '6. Зберігання даних', body: 'Ми не зберігаємо вхідні дані або результати обчислень. Дані розмов з ШІ-коучем регулюються політикою зберігання DeepSeek. Аналітичні дані Microsoft Clarity зберігаються відповідно до їхніх умов.' },
      { title: '7. Діти', body: 'SolviqLab не призначений для дітей до 13 років. Ми свідомо не збираємо персональні дані дітей. Якщо ви вважаєте, що дитина надала особисті дані, зверніться до нас, і ми негайно їх видалимо.' },
      { title: '8. Зміни до цієї політики', body: 'Ми можемо час від часу оновлювати цю політику. Дата у верхній частині сторінки відображатиме останню редакцію. Продовження використання SolviqLab після змін означає прийняття оновленої політики.' },
      { title: '9. Контакти', body: 'З будь-яких питань щодо конфіденційності:\nEmail: privacy@solviqlab.com\nВебсайт: https://solviqlab.com/uk/contact' },
    ],
  },
  es: {
    lastUpdated: '27 de julio de 2026',
    tldr: 'Resumen — Los cálculos ocurren en tu navegador. No requerimos registro. No vendemos tus datos. El coach de IA usa la API de DeepSeek. Análisis solo con tu consentimiento.',
    sections: [
      { title: '1. Quiénes somos', body: 'SolviqLab (solviqlab.com) es una plataforma gratuita de calculadoras en línea para salud, finanzas, matemáticas y conversión de unidades. Para consultas de privacidad: privacy@solviqlab.com.' },
      { title: '2. Qué datos recopilamos', body: 'Estamos diseñados para ser privados por defecto.\n\n• Cálculos — todas las fórmulas se ejecutan en tu navegador. No enviamos datos a nuestros servidores.\n• Resultados de tests — almacenados solo en localStorage de tu navegador. No los transmitimos.\n• Sesiones del coach IA — cuando usas Mia o Alex, tus mensajes se envían a la API de DeepSeek. No almacenamos registros de chat.\n• Análisis (opcional) — si aceptas cookies analíticas, usamos Microsoft Clarity. Los datos son anonimizados.' },
      { title: '3. Cookies y almacenamiento local', body: 'Usamos localStorage del navegador para recordar tus preferencias (tema, idioma, puntuaciones, calculadoras favoritas). Estos datos permanecen en tu dispositivo.\n\nSi aceptas cookies analíticas opcionales, configuramos cookies para Microsoft Clarity. Puedes cambiar tus preferencias en cualquier momento en el pie de página.' },
      { title: '4. Servicios de terceros', body: '• API de DeepSeek — impulsa el coaching de IA. Más info: https://www.deepseek.com/privacy\n• Microsoft Clarity — análisis de sesiones, solo con tu consentimiento. Más info: https://privacy.microsoft.com\n• Vercel — nuestro proveedor de hosting procesa metadatos de solicitudes bajo su Política de Privacidad.' },
      { title: '5. Tus derechos (RGPD / CCPA)', body: 'Tienes derecho a:\n• Acceder a los datos que tenemos sobre ti\n• Solicitar la eliminación de tus datos\n• Oponerte al procesamiento\n• Retirar el consentimiento en cualquier momento\n\nComo casi no almacenamos nada en el servidor, la mayoría de tus datos ya están bajo tu control. Escríbenos: privacy@solviqlab.com.' },
      { title: '6. Retención de datos', body: 'No conservamos entradas ni resultados de cálculos. Los datos del coach IA procesados por DeepSeek API se rigen por sus políticas. Los datos de Microsoft Clarity se conservan según sus condiciones.' },
      { title: '7. Menores', body: 'SolviqLab no está dirigido a menores de 13 años. No recopilamos datos personales de menores. Si crees que un menor ha proporcionado datos personales, contáctanos y los eliminaremos.' },
      { title: '8. Cambios en esta política', body: 'Podemos actualizar esta política. La fecha al inicio de la página reflejará la última revisión. El uso continuado de SolviqLab tras los cambios constituye la aceptación de la política actualizada.' },
      { title: '9. Contacto', body: 'Para cualquier pregunta sobre privacidad:\nEmail: privacy@solviqlab.com\nWeb: https://solviqlab.com/es/contact' },
    ],
  },
  fr: {
    lastUpdated: '27 juillet 2026',
    tldr: "En bref — Les calculs s'effectuent dans votre navigateur. Aucune inscription requise. Nous ne vendons pas vos données. Le coach IA utilise l'API DeepSeek. Analyses uniquement avec votre consentement.",
    sections: [
      { title: '1. Qui sommes-nous', body: "SolviqLab (solviqlab.com) est une plateforme gratuite de calculatrices en ligne pour la santé, la finance, les mathématiques et la conversion d'unités. Pour toute question sur la confidentialité : privacy@solviqlab.com." },
      { title: '2. Quelles données collectons-nous', body: "Nous sommes conçus pour être privés par défaut.\n\n• Calculs — toutes les formules s'exécutent dans votre navigateur. Aucune donnée n'est envoyée à nos serveurs.\n• Résultats des tests — stockés uniquement dans le localStorage de votre navigateur. Nous ne les transmettons pas.\n• Sessions de coach IA — lorsque vous interagissez avec Mia ou Alex, vos messages sont envoyés à l'API DeepSeek. Nous ne stockons pas les journaux de chat.\n• Analyses (optionnel) — si vous acceptez les cookies analytiques, nous utilisons Microsoft Clarity. Ces données sont anonymisées." },
      { title: '3. Cookies et stockage local', body: "Nous utilisons le localStorage pour mémoriser vos préférences (thème, langue, scores, calculatrices favorites). Ces données restent sur votre appareil.\n\nSi vous acceptez les cookies analytiques optionnels, nous configurons des cookies pour Microsoft Clarity. Vous pouvez modifier vos préférences à tout moment via le lien en bas de page." },
      { title: '4. Services tiers', body: "• API DeepSeek — alimente le coaching IA. Voir : https://www.deepseek.com/privacy\n• Microsoft Clarity — analyses de session, uniquement avec votre consentement. Voir : https://privacy.microsoft.com\n• Vercel — notre hébergeur traite les métadonnées des requêtes conformément à sa Politique de confidentialité." },
      { title: '5. Vos droits (RGPD / CCPA)', body: "Vous avez le droit de :\n• Accéder aux données que nous détenons sur vous\n• Demander la suppression de vos données\n• Vous opposer au traitement\n• Retirer votre consentement à tout moment\n\nComme nous ne stockons presque rien côté serveur, la plupart de vos données sont déjà sous votre contrôle. Écrivez-nous : privacy@solviqlab.com." },
      { title: '6. Conservation des données', body: "Nous ne conservons pas les entrées ni les résultats des calculs. Les données du coach IA traitées par l'API DeepSeek sont régies par leurs politiques. Les données Microsoft Clarity sont conservées selon leurs conditions." },
      { title: '7. Enfants', body: "SolviqLab ne s'adresse pas aux enfants de moins de 13 ans. Nous ne collectons pas sciemment de données personnelles d'enfants. Si vous pensez qu'un enfant a fourni des données, contactez-nous et nous les supprimerons." },
      { title: '8. Modifications de cette politique', body: 'Nous pouvons mettre à jour cette politique. La date en haut de la page reflétera la dernière révision. L\'utilisation continue de SolviqLab après les modifications constitue l\'acceptation de la politique mise à jour.' },
      { title: '9. Contact', body: 'Pour toute question relative à la confidentialité :\nEmail : privacy@solviqlab.com\nSite : https://solviqlab.com/fr/contact' },
    ],
  },
  de: {
    lastUpdated: '27. Juli 2026',
    tldr: 'Kurzfassung — Berechnungen erfolgen in Ihrem Browser. Keine Registrierung erforderlich. Wir verkaufen Ihre Daten nicht. Der KI-Coach nutzt die DeepSeek API. Analysen nur mit Ihrer Zustimmung.',
    sections: [
      { title: '1. Wer wir sind', body: 'SolviqLab (solviqlab.com) ist eine kostenlose Online-Rechnerplattform für Gesundheit, Finanzen, Mathematik und Einheitenumrechnung. Bei Datenschutzfragen: privacy@solviqlab.com.' },
      { title: '2. Welche Daten wir erheben', body: 'Wir sind standardmäßig auf Datenschutz ausgelegt.\n\n• Berechnungen — alle Formeln laufen ausschließlich in Ihrem Browser. Keine Daten werden an unsere Server gesendet.\n• Quiz-Ergebnisse — werden nur im localStorage Ihres Browsers gespeichert. Wir übertragen sie nicht.\n• KI-Coach-Sitzungen — wenn Sie mit Mia oder Alex interagieren, werden Ihre Nachrichten an die DeepSeek API gesendet. Wir speichern keine Chat-Protokolle.\n• Analysen (optional) — wenn Sie Analyse-Cookies akzeptieren, nutzen wir Microsoft Clarity. Die Daten sind anonymisiert.' },
      { title: '3. Cookies & lokaler Speicher', body: 'Wir nutzen den Browser-localStorage, um Ihre Einstellungen zu speichern (Theme, Sprache, Quiz-Punkte, Lieblingsrechner). Diese verbleiben auf Ihrem Gerät.\n\nBei Akzeptanz optionaler Analyse-Cookies setzen wir Cookies für Microsoft Clarity. Sie können Ihre Einstellungen jederzeit über den Link „Cookie-Einstellungen" im Footer ändern.' },
      { title: '4. Drittanbieter-Dienste', body: '• DeepSeek API — betreibt unsere KI-Coaching-Funktionen. Siehe: https://www.deepseek.com/privacy\n• Microsoft Clarity — Sitzungsanalysen, nur mit Ihrer Zustimmung. Siehe: https://privacy.microsoft.com\n• Vercel — unser Hosting-Anbieter verarbeitet Anfrage-Metadaten gemäß ihrer Datenschutzrichtlinie.' },
      { title: '5. Ihre Rechte (DSGVO / CCPA)', body: 'Sie haben das Recht auf:\n• Auskunft über Ihre bei uns gespeicherten Daten\n• Löschung Ihrer Daten\n• Widerspruch gegen die Verarbeitung\n• Widerruf der Einwilligung jederzeit\n\nDa wir kaum Daten serverseitig speichern, haben Sie die meisten Daten bereits unter Kontrolle. Schreiben Sie uns: privacy@solviqlab.com.' },
      { title: '6. Datenspeicherung', body: 'Wir speichern keine Berechnungseingaben oder -ergebnisse. Konversationsdaten des KI-Coaches über die DeepSeek API unterliegen deren Aufbewahrungsrichtlinien. Microsoft Clarity-Daten werden gemäß deren Bedingungen gespeichert.' },
      { title: '7. Kinder', body: 'SolviqLab richtet sich nicht an Kinder unter 13 Jahren. Wir erheben wissentlich keine personenbezogenen Daten von Kindern. Falls Sie glauben, dass ein Kind Daten angegeben hat, kontaktieren Sie uns zur sofortigen Löschung.' },
      { title: '8. Änderungen dieser Richtlinie', body: 'Wir können diese Richtlinie aktualisieren. Das Datum oben auf der Seite gibt die neueste Überarbeitung an. Die weitere Nutzung von SolviqLab nach Änderungen gilt als Akzeptanz der aktualisierten Richtlinie.' },
      { title: '9. Kontakt', body: 'Bei datenschutzbezogenen Fragen:\nE-Mail: privacy@solviqlab.com\nWebsite: https://solviqlab.com/de/contact' },
    ],
  },
  it: {
    lastUpdated: '27 luglio 2026',
    tldr: "In breve — I calcoli avvengono nel tuo browser. Non richiediamo registrazione. Non vendiamo i tuoi dati. Il coach IA utilizza l'API DeepSeek. Analytics solo con il tuo consenso.",
    sections: [
      { title: '1. Chi siamo', body: 'SolviqLab (solviqlab.com) è una piattaforma gratuita di calcolatrici online per salute, finanza, matematica e conversione di unità. Per domande sulla privacy: privacy@solviqlab.com.' },
      { title: '2. Quali dati raccogliamo', body: 'Siamo progettati per essere privati per impostazione predefinita.\n\n• Calcoli — tutte le formule vengono eseguite nel tuo browser. Nessun dato viene inviato ai nostri server.\n• Risultati dei quiz — archiviati solo nel localStorage del tuo browser. Non li trasmettiamo.\n• Sessioni coach IA — quando interagisci con Mia o Alex, i tuoi messaggi vengono inviati all\'API DeepSeek. Non conserviamo registri delle chat.\n• Analytics (opzionale) — se accetti i cookie analitici, utilizziamo Microsoft Clarity. I dati sono anonimizzati.' },
      { title: '3. Cookie e archiviazione locale', body: 'Utilizziamo localStorage del browser per ricordare le tue preferenze (tema, lingua, punteggi quiz, calcolatrici preferite). Questi dati rimangono sul tuo dispositivo.\n\nSe accetti i cookie analitici opzionali, impostiamo cookie per Microsoft Clarity. Puoi modificare le preferenze in qualsiasi momento tramite il link in fondo alla pagina.' },
      { title: '4. Servizi di terze parti', body: "• API DeepSeek — alimenta le funzioni di coaching IA. Vedi: https://www.deepseek.com/privacy\n• Microsoft Clarity — analisi delle sessioni, solo con il tuo consenso. Vedi: https://privacy.microsoft.com\n• Vercel — il nostro provider di hosting elabora i metadati delle richieste ai sensi della loro Informativa sulla privacy." },
      { title: '5. I tuoi diritti (GDPR / CCPA)', body: "Hai il diritto di:\n• Accedere ai dati che conserviamo su di te\n• Richiedere la cancellazione dei tuoi dati\n• Opporti al trattamento\n• Revocare il consenso in qualsiasi momento\n\nPoiché conserviamo quasi nulla lato server, la maggior parte dei tuoi dati è già sotto il tuo controllo. Scrivici: privacy@solviqlab.com." },
      { title: '6. Conservazione dei dati', body: "Non conserviamo input o risultati dei calcoli. I dati delle conversazioni con il coach IA elaborati tramite l'API DeepSeek sono disciplinati dalle loro politiche. I dati Microsoft Clarity sono conservati secondo le loro condizioni." },
      { title: '7. Bambini', body: 'SolviqLab non è destinato a bambini under 13. Non raccogliamo consapevolmente dati personali di minori. Se ritieni che un bambino abbia fornito dati personali, contattaci e li elimineremo immediatamente.' },
      { title: '8. Modifiche a questa politica', body: "Potremmo aggiornare questa politica di tanto in tanto. La data in cima alla pagina rifletterà l'ultima revisione. L'uso continuato di SolviqLab dopo le modifiche costituisce accettazione della politica aggiornata." },
      { title: '9. Contatto', body: 'Per qualsiasi domanda relativa alla privacy:\nEmail: privacy@solviqlab.com\nSito: https://solviqlab.com/it/contact' },
    ],
  },
  tr: {
    lastUpdated: '27 Temmuz 2026',
    tldr: 'Özet — Hesaplamalar tarayıcınızda gerçekleşir. Kayıt gerekmez. Verilerinizi satmıyoruz. Yapay zeka koçu DeepSeek API kullanır. Analitik yalnızca onayınızla.',
    sections: [
      { title: '1. Biz Kimiz', body: 'SolviqLab (solviqlab.com), sağlık, finans, matematik ve birim dönüşümü için ücretsiz bir çevrimiçi hesap makinesi platformudur. Gizlilik sorularınız için: privacy@solviqlab.com.' },
      { title: '2. Hangi Verileri Topluyoruz', body: 'Varsayılan olarak gizli olmak üzere tasarlandık.\n\n• Hesaplamalar — tüm formüller yalnızca tarayıcınızda çalışır. Sunucularımıza hiçbir veri gönderilmez.\n• Test sonuçları — yalnızca tarayıcınızın localStorage\'ında saklanır. Aktarmıyoruz.\n• Yapay zeka koç oturumları — Mia veya Alex ile etkileşim kurduğunuzda mesajlarınız DeepSeek API\'ye gönderilir. Sohbet günlükleri saklamıyoruz.\n• Analitik (isteğe bağlı) — analitik çerezleri kabul ederseniz Microsoft Clarity kullanıyoruz. Veriler anonimleştirilmiştir.' },
      { title: '3. Çerezler ve Yerel Depolama', body: 'Tercihlerinizi (tema, dil, quiz puanları, favori hesap makineleri) hatırlamak için localStorage kullanıyoruz. Bu veriler cihazınızda kalır.\n\nİsteğe bağlı analitik çerezleri kabul ederseniz Microsoft Clarity için çerezler ayarlarız. Tercihleri istediğiniz zaman altbilgideki bağlantıdan değiştirebilirsiniz.' },
      { title: '4. Üçüncü Taraf Hizmetleri', body: '• DeepSeek API — yapay zeka koçluk özelliklerini destekler. Bkz: https://www.deepseek.com/privacy\n• Microsoft Clarity — yalnızca onayınızla oturum analizi. Bkz: https://privacy.microsoft.com\n• Vercel — barındırma sağlayıcımız istek meta verilerini Gizlilik Politikaları kapsamında işler.' },
      { title: '5. Haklarınız (GDPR / CCPA)', body: 'Şu haklara sahipsiniz:\n• Hakkınızdaki verilere erişim\n• Verilerinizin silinmesini talep etme\n• İşlemeye itiraz etme\n• İstediğiniz zaman onayı geri çekme\n\nSunucu tarafında neredeyse hiçbir şey saklamadığımız için verilerinizin çoğu zaten kontrolünüzde. Bize yazın: privacy@solviqlab.com.' },
      { title: '6. Veri Saklama', body: 'Hesaplama girişlerini veya sonuçlarını saklamıyoruz. DeepSeek API aracılığıyla işlenen yapay zeka koç konuşma verileri kendi saklama politikalarına tabidir. Microsoft Clarity verileri kendi koşulları çerçevesinde saklanır.' },
      { title: '7. Çocuklar', body: 'SolviqLab 13 yaşın altındaki çocuklara yönelik değildir. Bilerek çocuklardan kişisel veri toplamıyoruz. Bir çocuğun veri sağladığını düşünüyorsanız bize bildirin, derhal sileceğiz.' },
      { title: '8. Bu Politikadaki Değişiklikler', body: 'Bu politikayı zaman zaman güncelleyebiliriz. Sayfanın üstündeki tarih en son revizyonu yansıtacaktır. Değişiklikler sonrası SolviqLab kullanımına devam etmek güncellenmiş politikayı kabul anlamına gelir.' },
      { title: '9. İletişim', body: 'Gizlilikle ilgili sorularınız için:\nE-posta: privacy@solviqlab.com\nWeb sitesi: https://solviqlab.com/tr/contact' },
    ],
  },
  pt: {
    lastUpdated: '27 de julho de 2026',
    tldr: 'Resumo — Os cálculos acontecem no seu navegador. Não exigimos cadastro. Não vendemos seus dados. O coach de IA usa a API DeepSeek. Análises somente com seu consentimento.',
    sections: [
      { title: '1. Quem somos', body: 'SolviqLab (solviqlab.com) é uma plataforma gratuita de calculadoras online para saúde, finanças, matemática e conversão de unidades. Para questões de privacidade: privacy@solviqlab.com.' },
      { title: '2. Que dados coletamos', body: 'Somos projetados para ser privados por padrão.\n\n• Cálculos — todas as fórmulas são executadas no seu navegador. Nenhum dado é enviado para nossos servidores.\n• Resultados de testes — armazenados apenas no localStorage do seu navegador. Não os transmitimos.\n• Sessões do coach de IA — quando você interage com Mia ou Alex, suas mensagens são enviadas à API DeepSeek. Não armazenamos registros de chat.\n• Análises (opcional) — se você aceitar cookies analíticos, usamos Microsoft Clarity. Os dados são anonimizados.' },
      { title: '3. Cookies e armazenamento local', body: 'Usamos o localStorage do navegador para lembrar suas preferências (tema, idioma, pontuações de quiz, calculadoras favoritas). Esses dados ficam no seu dispositivo.\n\nSe você aceitar cookies analíticos opcionais, configuramos cookies para Microsoft Clarity. Você pode alterar suas preferências a qualquer momento pelo rodapé.' },
      { title: '4. Serviços de terceiros', body: '• API DeepSeek — alimenta os recursos de coaching de IA. Veja: https://www.deepseek.com/privacy\n• Microsoft Clarity — análise de sessões, somente com seu consentimento. Veja: https://privacy.microsoft.com\n• Vercel — nosso provedor de hospedagem processa metadados de solicitações conforme sua Política de Privacidade.' },
      { title: '5. Seus direitos (LGPD / CCPA)', body: 'Você tem o direito de:\n• Acessar os dados que temos sobre você\n• Solicitar a exclusão dos seus dados\n• Opor-se ao processamento\n• Retirar o consentimento a qualquer momento\n\nComo armazenamos quase nada no servidor, a maioria dos seus dados já está sob seu controle. Escreva-nos: privacy@solviqlab.com.' },
      { title: '6. Retenção de dados', body: 'Não retemos entradas ou resultados de cálculos. Os dados de conversas do coach de IA processados pela API DeepSeek são regidos por suas políticas de retenção. Os dados do Microsoft Clarity são retidos conforme seus termos.' },
      { title: '7. Crianças', body: 'SolviqLab não é direcionado a crianças menores de 13 anos. Não coletamos conscientemente dados pessoais de crianças. Se você acreditar que uma criança forneceu dados pessoais, entre em contato e os excluiremos imediatamente.' },
      { title: '8. Alterações nesta política', body: 'Podemos atualizar esta política periodicamente. A data no topo da página refletirá a última revisão. O uso contínuo do SolviqLab após as alterações constitui aceitação da política atualizada.' },
      { title: '9. Contato', body: 'Para qualquer questão relacionada à privacidade:\nEmail: privacy@solviqlab.com\nSite: https://solviqlab.com/pt/contact' },
    ],
  },
  pl: {
    lastUpdated: '27 lipca 2026',
    tldr: 'Krótko — Obliczenia odbywają się w Twojej przeglądarce. Nie wymagamy rejestracji. Nie sprzedajemy Twoich danych. Coach AI korzysta z API DeepSeek. Analityka tylko za Twoją zgodą.',
    sections: [
      { title: '1. Kim jesteśmy', body: 'SolviqLab (solviqlab.com) to bezpłatna platforma kalkulatorów online dla zdrowia, finansów, matematyki i konwersji jednostek. W sprawach prywatności: privacy@solviqlab.com.' },
      { title: '2. Jakie dane zbieramy', body: 'Jesteśmy zaprojektowani z myślą o prywatności domyślnie.\n\n• Obliczenia — wszystkie formuły działają wyłącznie w Twojej przeglądarce. Żadne dane nie są wysyłane na nasze serwery.\n• Wyniki quizów — przechowywane tylko w localStorage Twojej przeglądarki. Nie przesyłamy ich.\n• Sesje coacha AI — gdy korzystasz z Mia lub Alex, Twoje wiadomości są wysyłane do API DeepSeek. Nie przechowujemy logów czatu.\n• Analityka (opcjonalna) — jeśli zaakceptujesz pliki cookie analityczne, używamy Microsoft Clarity. Dane są anonimizowane.' },
      { title: '3. Pliki cookie i pamięć lokalna', body: 'Używamy localStorage przeglądarki do zapamiętywania Twoich preferencji (motyw, język, wyniki quizów, ulubione kalkulatory). Dane pozostają na Twoim urządzeniu.\n\nJeśli zaakceptujesz opcjonalne pliki cookie analityczne, ustawiamy pliki cookie dla Microsoft Clarity. Preferencje możesz zmienić w dowolnym momencie przez link w stopce.' },
      { title: '4. Usługi podmiotów trzecich', body: '• API DeepSeek — zasila funkcje coachingu AI. Zob.: https://www.deepseek.com/privacy\n• Microsoft Clarity — analityka sesji, tylko za Twoją zgodą. Zob.: https://privacy.microsoft.com\n• Vercel — nasz dostawca hostingu przetwarza metadane żądań zgodnie z własną Polityką Prywatności.' },
      { title: '5. Twoje prawa (RODO / CCPA)', body: 'Masz prawo do:\n• Dostępu do danych, które przechowujemy na Twój temat\n• Żądania usunięcia Twoich danych\n• Sprzeciwu wobec przetwarzania\n• Wycofania zgody w dowolnym momencie\n\nPonieważ prawie nic nie przechowujemy po stronie serwera, większość Twoich danych jest już pod Twoją kontrolą. Napisz do nas: privacy@solviqlab.com.' },
      { title: '6. Przechowywanie danych', body: 'Nie przechowujemy danych wejściowych ani wyników obliczeń. Dane rozmów z coachem AI przetwarzane przez API DeepSeek podlegają ich polityce przechowywania. Dane Microsoft Clarity są przechowywane zgodnie z ich warunkami.' },
      { title: '7. Dzieci', body: 'SolviqLab nie jest przeznaczony dla dzieci poniżej 13 lat. Nie zbieramy świadomie danych osobowych dzieci. Jeśli uważasz, że dziecko podało dane osobowe, skontaktuj się z nami, a usuniemy je niezwłocznie.' },
      { title: '8. Zmiany w tej polityce', body: 'Możemy od czasu do czasu aktualizować tę politykę. Data u góry strony odzwierciedla ostatnią wersję. Dalsze korzystanie z SolviqLab po zmianach oznacza akceptację zaktualizowanej polityki.' },
      { title: '9. Kontakt', body: 'W sprawie pytań dotyczących prywatności:\nEmail: privacy@solviqlab.com\nStrona: https://solviqlab.com/pl/contact' },
    ],
  },
  nl: {
    lastUpdated: '27 juli 2026',
    tldr: 'Samenvatting — Berekeningen vinden plaats in uw browser. Geen registratie vereist. We verkopen uw gegevens niet. De AI-coach gebruikt de DeepSeek API. Analyses alleen met uw toestemming.',
    sections: [
      { title: '1. Wie wij zijn', body: 'SolviqLab (solviqlab.com) is een gratis online calculatorplatform voor gezondheid, financiën, wiskunde en eenheidsconversie. Voor privacyvragen: privacy@solviqlab.com.' },
      { title: '2. Welke gegevens we verzamelen', body: 'We zijn standaard privacyvriendelijk ontworpen.\n\n• Berekeningen — alle formules worden uitsluitend in uw browser uitgevoerd. Geen gegevens worden naar onze servers verzonden.\n• Quizresultaten — alleen opgeslagen in de localStorage van uw browser. We verzenden ze niet.\n• AI-coach sessies — wanneer u met Mia of Alex interacteert, worden uw berichten naar de DeepSeek API verzonden. We slaan geen chatlogboeken op.\n• Analyses (optioneel) — als u analytische cookies accepteert, gebruiken we Microsoft Clarity. De gegevens zijn geanonimiseerd.' },
      { title: '3. Cookies en lokale opslag', body: 'We gebruiken localStorage om uw voorkeuren te onthouden (thema, taal, quizscores, favoriete calculators). Deze blijven op uw apparaat.\n\nAls u optionele analytische cookies accepteert, plaatsen we cookies voor Microsoft Clarity. U kunt uw voorkeuren altijd wijzigen via de link in de voettekst.' },
      { title: '4. Diensten van derden', body: '• DeepSeek API — beheert onze AI-coachingfuncties. Zie: https://www.deepseek.com/privacy\n• Microsoft Clarity — sessie-analyses, alleen met uw toestemming. Zie: https://privacy.microsoft.com\n• Vercel — onze hostingprovider verwerkt aanvraagmetadata conform hun Privacybeleid.' },
      { title: '5. Uw rechten (AVG / CCPA)', body: 'U heeft het recht op:\n• Inzage in uw gegevens die wij bewaren\n• Verwijdering van uw gegevens\n• Bezwaar tegen verwerking\n• Intrekking van toestemming op elk moment\n\nOmdat we vrijwel niets server-side opslaan, heeft u de meeste gegevens al onder controle. Schrijf ons: privacy@solviqlab.com.' },
      { title: '6. Gegevensbewaring', body: 'We bewaren geen berekeningsinvoer of -resultaten. Conversatiegegevens van de AI-coach via de DeepSeek API vallen onder hun bewaarbeleid. Microsoft Clarity-gegevens worden bewaard conform hun voorwaarden.' },
      { title: '7. Kinderen', body: 'SolviqLab is niet gericht op kinderen onder 13 jaar. We verzamelen niet bewust persoonsgegevens van kinderen. Als u denkt dat een kind gegevens heeft verstrekt, neem contact op en we verwijderen deze direct.' },
      { title: '8. Wijzigingen in dit beleid', body: 'We kunnen dit beleid van tijd tot tijd bijwerken. De datum bovenaan de pagina geeft de laatste revisie aan. Voortgezet gebruik van SolviqLab na wijzigingen geldt als acceptatie van het bijgewerkte beleid.' },
      { title: '9. Contact', body: 'Voor privacygerelateerde vragen:\nE-mail: privacy@solviqlab.com\nWebsite: https://solviqlab.com/nl/contact' },
    ],
  },
}

// ===== TERMS OF SERVICE =====
const termsData: Record<string, { lastUpdated: string; warning: string; sections: Section[] }> = {
  en: {
    lastUpdated: 'July 27, 2026',
    warning: 'Important: SolviqLab calculators and AI coaching are for informational purposes only — not medical or financial advice.',
    sections: [
      { title: '1. Acceptance of Terms', body: 'By accessing or using SolviqLab (solviqlab.com), you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.' },
      { title: '2. Description of Service', body: 'SolviqLab provides free online calculators for health, finance, mathematics, and unit conversions. We also offer AI-powered coaching through Mia (health) and Alex (finance), powered by the DeepSeek API.\n\nAll core features are free and require no account or registration.' },
      { title: '3. Not Professional Advice', body: 'SolviqLab calculators and AI coaching features are for informational and educational purposes only.\n\n• Health calculators are NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider.\n• Finance calculators are NOT financial advice. Consult a licensed financial advisor before making financial decisions.\n• Results are estimates based on widely-accepted formulas. Accuracy depends on inputs provided.' },
      { title: '4. Permitted Use', body: 'You may use SolviqLab for personal, non-commercial purposes. You agree not to:\n• Attempt to reverse-engineer, scrape, or overload our services\n• Use automated tools to mass-query our calculators or AI features\n• Misrepresent SolviqLab results as certified medical or financial assessments\n• Use the platform for any unlawful purpose' },
      { title: '5. Intellectual Property', body: 'All content, design, formulas, and AI coaching experiences on SolviqLab are the property of SolviqLab or its licensors. You may share calculator results for personal use, but may not reproduce or redistribute our platform content commercially without written permission.' },
      { title: '6. Disclaimer of Warranties', body: 'SolviqLab is provided "as is" without warranties of any kind, express or implied. We do not guarantee that:\n• Results will be accurate for every individual scenario\n• The service will be available without interruption\n• The AI coaching responses will be error-free\n\nWe strive for accuracy using WHO, CFPB, NIST, and ISO standards, but cannot guarantee results for every edge case.' },
      { title: '7. Limitation of Liability', body: 'To the fullest extent permitted by law, SolviqLab shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform, including reliance on calculator results or AI coaching output.' },
      { title: '8. Third-Party Services', body: 'SolviqLab uses third-party services including DeepSeek (AI), Microsoft Clarity (analytics, with consent), and Vercel (hosting). Your use of these services is also governed by their respective terms.' },
      { title: '9. Changes to Terms', body: 'We reserve the right to update these Terms at any time. Continued use of SolviqLab after changes are posted constitutes your acceptance of the revised Terms. The effective date will be updated at the top of this page.' },
      { title: '10. Governing Law', body: 'These Terms are governed by applicable law. Any disputes shall be resolved through good-faith negotiation. For any legal inquiries, contact legal@solviqlab.com.' },
      { title: '11. Contact', body: 'Questions about these Terms? Contact us at:\nEmail: legal@solviqlab.com\nWebsite: https://solviqlab.com/en/contact' },
    ],
  },
  uk: {
    lastUpdated: '27 липня 2026',
    warning: 'Важливо: калькулятори та ШІ-коучинг SolviqLab призначені виключно для інформаційних цілей — не є медичною або фінансовою порадою.',
    sections: [
      { title: '1. Прийняття умов', body: 'Отримуючи доступ до SolviqLab (solviqlab.com) або використовуючи його, ви погоджуєтеся з цими Умовами використання. Якщо ви не погоджуєтеся, будь ласка, не використовуйте платформу.' },
      { title: '2. Опис сервісу', body: 'SolviqLab надає безкоштовні онлайн-калькулятори для здоров\'я, фінансів, математики та конвертації одиниць. Ми також пропонуємо ШІ-коучинг через Mia (здоров\'я) і Alex (фінанси) на базі DeepSeek API.\n\nВсі основні функції безкоштовні та не вимагають облікового запису або реєстрації.' },
      { title: '3. Не є професійною порадою', body: 'Калькулятори та ШІ-коучинг SolviqLab призначені виключно для інформаційних та освітніх цілей.\n\n• Калькулятори здоров\'я НЕ замінюють професійну медичну консультацію, діагностику або лікування. Завжди звертайтесь до кваліфікованого медичного працівника.\n• Фінансові калькулятори НЕ є фінансовою порадою. Перед прийняттям фінансових рішень зверніться до ліцензованого фінансового консультанта.\n• Результати є оцінками, заснованими на загальноприйнятих формулах. Точність залежить від введених даних.' },
      { title: '4. Дозволене використання', body: 'Ви можете використовувати SolviqLab у особистих, некомерційних цілях. Ви погоджуєтеся не:\n• Намагатися здійснити зворотну розробку, скрейпінг або перевантаження наших сервісів\n• Використовувати автоматизовані інструменти для масових запитів до наших калькуляторів або ШІ-функцій\n• Видавати результати SolviqLab за сертифіковані медичні або фінансові оцінки\n• Використовувати платформу в будь-яких незаконних цілях' },
      { title: '5. Інтелектуальна власність', body: 'Весь контент, дизайн, формули та досвід ШІ-коучингу на SolviqLab є власністю SolviqLab або його ліцензіарів. Ви можете ділитися результатами калькуляторів для особистого використання, але не можете відтворювати або поширювати контент нашої платформи в комерційних цілях без письмового дозволу.' },
      { title: '6. Відмова від гарантій', body: 'SolviqLab надається «як є» без будь-яких гарантій, явних або підразумеваних. Ми не гарантуємо, що:\n• Результати будуть точними для кожного індивідуального сценарію\n• Сервіс буде доступний без перебоїв\n• Відповіді ШІ-коуча будуть без помилок\n\nМи прагнемо до точності за стандартами ВООЗ, CFPB, NIST та ISO, але не можемо гарантувати результати для кожного граничного випадку.' },
      { title: '7. Обмеження відповідальності', body: 'У максимально дозволеній законом мірі SolviqLab не несе відповідальності за будь-які непрямі, випадкові або наслідкові збитки, що виникають внаслідок використання вами платформи, включаючи покладання на результати калькуляторів або висновки ШІ-коуча.' },
      { title: '8. Сторонні сервіси', body: 'SolviqLab використовує сторонні сервіси, включаючи DeepSeek (ШІ), Microsoft Clarity (аналітика, за згодою) та Vercel (хостинг). Використання вами цих сервісів також регулюється їхніми відповідними умовами.' },
      { title: '9. Зміни умов', body: 'Ми залишаємо за собою право оновлювати ці Умови в будь-який час. Продовження використання SolviqLab після публікації змін означає ваше прийняття переглянутих Умов. Дата набрання чинності буде оновлена у верхній частині цієї сторінки.' },
      { title: '10. Застосовне право', body: 'Ці Умови регулюються чинним законодавством. Будь-які суперечки вирішуються шляхом добросовісних переговорів. З юридичних питань: legal@solviqlab.com.' },
      { title: '11. Контакти', body: 'Питання щодо цих Умов?\nEmail: legal@solviqlab.com\nВебсайт: https://solviqlab.com/uk/contact' },
    ],
  },
  es: {
    lastUpdated: '27 de julio de 2026',
    warning: 'Importante: las calculadoras y el coaching de IA de SolviqLab son solo para fines informativos — no son asesoramiento médico ni financiero.',
    sections: [
      { title: '1. Aceptación de los Términos', body: 'Al acceder o usar SolviqLab (solviqlab.com), aceptas estar sujeto a estos Términos de Servicio. Si no estás de acuerdo, por favor no uses la plataforma.' },
      { title: '2. Descripción del Servicio', body: 'SolviqLab ofrece calculadoras online gratuitas para salud, finanzas, matemáticas y conversión de unidades. También ofrecemos coaching con IA a través de Mia (salud) y Alex (finanzas), impulsado por la API de DeepSeek.\n\nTodas las funciones principales son gratuitas y no requieren cuenta ni registro.' },
      { title: '3. No es Asesoramiento Profesional', body: 'Las calculadoras y el coaching de IA de SolviqLab son solo para fines informativos y educativos.\n\n• Las calculadoras de salud NO sustituyen el asesoramiento médico profesional. Consulta siempre a un profesional de la salud.\n• Las calculadoras de finanzas NO son asesoramiento financiero. Consulta a un asesor financiero antes de tomar decisiones.\n• Los resultados son estimaciones basadas en fórmulas ampliamente aceptadas.' },
      { title: '4. Uso Permitido', body: 'Puedes usar SolviqLab para fines personales y no comerciales. Aceptas no:\n• Intentar realizar ingeniería inversa, scraping o sobrecargar nuestros servicios\n• Usar herramientas automatizadas para consultas masivas\n• Presentar los resultados de SolviqLab como evaluaciones médicas o financieras certificadas\n• Usar la plataforma para cualquier propósito ilegal' },
      { title: '5. Propiedad Intelectual', body: 'Todo el contenido, diseño, fórmulas y experiencias de coaching de IA son propiedad de SolviqLab o sus licenciantes. Puedes compartir resultados para uso personal, pero no reproducir ni redistribuir el contenido comercialmente sin permiso escrito.' },
      { title: '6. Exclusión de Garantías', body: 'SolviqLab se ofrece "tal cual" sin garantías de ningún tipo. No garantizamos que:\n• Los resultados sean precisos para cada escenario individual\n• El servicio esté disponible sin interrupciones\n• Las respuestas del coach IA sean libres de errores' },
      { title: '7. Limitación de Responsabilidad', body: 'En la máxima medida permitida por la ley, SolviqLab no será responsable de daños indirectos, incidentales o consecuentes derivados del uso de la plataforma.' },
      { title: '8. Servicios de Terceros', body: 'SolviqLab utiliza DeepSeek (IA), Microsoft Clarity (análisis, con consentimiento) y Vercel (alojamiento). El uso de estos servicios también está sujeto a sus respectivos términos.' },
      { title: '9. Cambios en los Términos', body: 'Nos reservamos el derecho de actualizar estos Términos en cualquier momento. El uso continuado de SolviqLab tras los cambios constituye la aceptación de los Términos revisados.' },
      { title: '10. Ley Aplicable', body: 'Estos Términos se rigen por la ley aplicable. Cualquier disputa se resolverá mediante negociación de buena fe. Para consultas legales: legal@solviqlab.com.' },
      { title: '11. Contacto', body: '¿Preguntas sobre estos Términos?\nEmail: legal@solviqlab.com\nWeb: https://solviqlab.com/es/contact' },
    ],
  },
  fr: {
    lastUpdated: '27 juillet 2026',
    warning: "Important : les calculatrices et le coaching IA de SolviqLab sont à des fins informatives uniquement — pas de conseil médical ou financier.",
    sections: [
      { title: "1. Acceptation des Conditions", body: "En accédant à SolviqLab (solviqlab.com) ou en l'utilisant, vous acceptez d'être lié par ces Conditions d'Utilisation. Si vous n'êtes pas d'accord, veuillez ne pas utiliser la plateforme." },
      { title: '2. Description du Service', body: "SolviqLab propose des calculatrices en ligne gratuites pour la santé, la finance, les mathématiques et la conversion d'unités. Nous proposons également un coaching IA via Mia (santé) et Alex (finance), alimenté par l'API DeepSeek.\n\nToutes les fonctionnalités principales sont gratuites et ne nécessitent ni compte ni inscription." },
      { title: '3. Pas un Conseil Professionnel', body: "Les calculatrices et le coaching IA de SolviqLab sont uniquement à des fins informatives et éducatives.\n\n• Les calculatrices de santé ne remplacent PAS les conseils médicaux professionnels. Consultez toujours un professionnel de santé qualifié.\n• Les calculatrices financières ne constituent PAS des conseils financiers. Consultez un conseiller financier agréé.\n• Les résultats sont des estimations basées sur des formules reconnues." },
      { title: '4. Utilisation Autorisée', body: "Vous pouvez utiliser SolviqLab à des fins personnelles et non commerciales. Vous acceptez de ne pas :\n• Tenter de rétro-ingénierie, scraping ou surcharge de nos services\n• Utiliser des outils automatisés pour des requêtes massives\n• Présenter les résultats de SolviqLab comme des évaluations médicales ou financières certifiées\n• Utiliser la plateforme à des fins illégales" },
      { title: '5. Propriété Intellectuelle', body: "Tout le contenu, la conception, les formules et les expériences de coaching IA sur SolviqLab sont la propriété de SolviqLab ou de ses concédants de licence. Vous pouvez partager les résultats pour un usage personnel, mais ne pouvez pas reproduire ou redistribuer le contenu commercialement sans autorisation écrite." },
      { title: '6. Exclusion de Garanties', body: 'SolviqLab est fourni "tel quel" sans garanties d\'aucune sorte. Nous ne garantissons pas que :\n• Les résultats seront précis pour chaque scénario individuel\n• Le service sera disponible sans interruption\n• Les réponses du coach IA seront exemptes d\'erreurs' },
      { title: '7. Limitation de Responsabilité', body: "Dans toute la mesure permise par la loi, SolviqLab ne sera pas responsable des dommages indirects, accessoires ou consécutifs découlant de votre utilisation de la plateforme." },
      { title: '8. Services Tiers', body: "SolviqLab utilise DeepSeek (IA), Microsoft Clarity (analyses, avec consentement) et Vercel (hébergement). Votre utilisation de ces services est également régie par leurs conditions respectives." },
      { title: '9. Modifications des Conditions', body: "Nous nous réservons le droit de mettre à jour ces Conditions à tout moment. L'utilisation continue de SolviqLab après les modifications vaut acceptation des Conditions révisées." },
      { title: '10. Droit Applicable', body: "Ces Conditions sont régies par le droit applicable. Tout litige sera résolu par négociation de bonne foi. Pour toute question juridique : legal@solviqlab.com." },
      { title: '11. Contact', body: "Des questions sur ces Conditions ?\nEmail : legal@solviqlab.com\nSite : https://solviqlab.com/fr/contact" },
    ],
  },
  de: {
    lastUpdated: '27. Juli 2026',
    warning: 'Wichtig: Die Rechner und das KI-Coaching von SolviqLab dienen nur zu Informationszwecken — keine medizinische oder finanzielle Beratung.',
    sections: [
      { title: '1. Annahme der Bedingungen', body: 'Durch den Zugriff auf SolviqLab (solviqlab.com) oder dessen Nutzung stimmen Sie diesen Nutzungsbedingungen zu. Wenn Sie nicht einverstanden sind, nutzen Sie die Plattform bitte nicht.' },
      { title: '2. Leistungsbeschreibung', body: 'SolviqLab bietet kostenlose Online-Rechner für Gesundheit, Finanzen, Mathematik und Einheitenumrechnung. Wir bieten auch KI-Coaching durch Mia (Gesundheit) und Alex (Finanzen) an, angetrieben von der DeepSeek API.\n\nAlle Kernfunktionen sind kostenlos und erfordern kein Konto oder keine Registrierung.' },
      { title: '3. Keine professionelle Beratung', body: 'SolviqLab-Rechner und KI-Coaching sind nur zu Informations- und Bildungszwecken.\n\n• Gesundheitsrechner ersetzen KEINE professionelle medizinische Beratung. Konsultieren Sie immer einen qualifizierten Arzt.\n• Finanzrechner sind KEINE Finanzberatung. Wenden Sie sich vor Finanzentscheidungen an einen zugelassenen Berater.\n• Ergebnisse sind Schätzungen basierend auf allgemein anerkannten Formeln.' },
      { title: '4. Erlaubte Nutzung', body: 'Sie dürfen SolviqLab für persönliche, nicht-kommerzielle Zwecke nutzen. Sie stimmen zu, Folgendes nicht zu tun:\n• Reverse Engineering, Scraping oder Überlastung unserer Dienste\n• Automatisierte Tools für Massenanfragen verwenden\n• SolviqLab-Ergebnisse als zertifizierte medizinische oder finanzielle Beurteilungen darstellen\n• Die Plattform für illegale Zwecke nutzen' },
      { title: '5. Geistiges Eigentum', body: 'Alle Inhalte, das Design, Formeln und KI-Coaching-Erfahrungen auf SolviqLab sind Eigentum von SolviqLab oder seinen Lizenzgebern. Sie dürfen Rechner-Ergebnisse für den persönlichen Gebrauch teilen, aber den Inhalt nicht ohne schriftliche Genehmigung kommerziell reproduzieren.' },
      { title: '6. Gewährleistungsausschluss', body: 'SolviqLab wird "wie besehen" ohne jegliche Garantien bereitgestellt. Wir garantieren nicht, dass:\n• Ergebnisse für jedes individuelle Szenario genau sind\n• Der Dienst unterbrechungsfrei verfügbar ist\n• KI-Coaching-Antworten fehlerfrei sind' },
      { title: '7. Haftungsbeschränkung', body: 'Im gesetzlich zulässigen Umfang haftet SolviqLab nicht für indirekte, zufällige oder Folgeschäden aus der Nutzung der Plattform.' },
      { title: '8. Drittanbieter-Dienste', body: 'SolviqLab nutzt DeepSeek (KI), Microsoft Clarity (Analysen, mit Zustimmung) und Vercel (Hosting). Ihre Nutzung dieser Dienste unterliegt auch deren jeweiligen Bedingungen.' },
      { title: '9. Änderungen der Bedingungen', body: 'Wir behalten uns das Recht vor, diese Bedingungen jederzeit zu aktualisieren. Die weitere Nutzung von SolviqLab nach Änderungen gilt als Akzeptanz der überarbeiteten Bedingungen.' },
      { title: '10. Anwendbares Recht', body: 'Diese Bedingungen unterliegen dem anwendbaren Recht. Streitigkeiten werden durch Verhandlung in gutem Glauben gelöst. Rechtliche Anfragen: legal@solviqlab.com.' },
      { title: '11. Kontakt', body: 'Fragen zu diesen Bedingungen?\nE-Mail: legal@solviqlab.com\nWebsite: https://solviqlab.com/de/contact' },
    ],
  },
  it: {
    lastUpdated: '27 luglio 2026',
    warning: 'Importante: le calcolatrici e il coaching IA di SolviqLab sono solo a scopo informativo — non costituiscono consulenza medica o finanziaria.',
    sections: [
      { title: "1. Accettazione dei Termini", body: "Accedendo o utilizzando SolviqLab (solviqlab.com), accetti di essere vincolato da questi Termini di Servizio. Se non sei d'accordo, ti preghiamo di non utilizzare la piattaforma." },
      { title: '2. Descrizione del Servizio', body: "SolviqLab fornisce calcolatrici online gratuite per salute, finanza, matematica e conversione di unità. Offriamo anche coaching IA tramite Mia (salute) e Alex (finanza), alimentato dall'API DeepSeek.\n\nTutte le funzionalità principali sono gratuite e non richiedono account o registrazione." },
      { title: '3. Non è una Consulenza Professionale', body: "Le calcolatrici e il coaching IA di SolviqLab sono solo a scopo informativo ed educativo.\n\n• Le calcolatrici della salute NON sostituiscono la consulenza medica professionale. Consulta sempre un operatore sanitario qualificato.\n• Le calcolatrici finanziarie NON sono consulenza finanziaria. Consulta un consulente finanziario autorizzato prima di prendere decisioni.\n• I risultati sono stime basate su formule ampiamente accettate." },
      { title: '4. Uso Consentito', body: "Puoi utilizzare SolviqLab per scopi personali e non commerciali. Accetti di non:\n• Tentare il reverse engineering, scraping o sovraccarico dei nostri servizi\n• Usare strumenti automatizzati per query di massa\n• Presentare i risultati di SolviqLab come valutazioni mediche o finanziarie certificate\n• Usare la piattaforma per scopi illegali" },
      { title: '5. Proprietà Intellettuale', body: "Tutti i contenuti, il design, le formule e le esperienze di coaching IA su SolviqLab sono di proprietà di SolviqLab o dei suoi licenziatari. Puoi condividere i risultati per uso personale, ma non puoi riprodurre o ridistribuire il contenuto commercialmente senza autorizzazione scritta." },
      { title: '6. Esclusione di Garanzie', body: "SolviqLab è fornito \"così com'è\" senza garanzie di alcun tipo. Non garantiamo che:\n• I risultati siano accurati per ogni scenario individuale\n• Il servizio sia disponibile senza interruzioni\n• Le risposte del coach IA siano prive di errori" },
      { title: '7. Limitazione di Responsabilità', body: "Nella misura massima consentita dalla legge, SolviqLab non sarà responsabile per danni indiretti, incidentali o consequenziali derivanti dall'utilizzo della piattaforma." },
      { title: '8. Servizi di Terze Parti', body: "SolviqLab utilizza DeepSeek (IA), Microsoft Clarity (analisi, con consenso) e Vercel (hosting). Il tuo utilizzo di questi servizi è regolato anche dai rispettivi termini." },
      { title: '9. Modifiche ai Termini', body: "Ci riserviamo il diritto di aggiornare questi Termini in qualsiasi momento. L'uso continuato di SolviqLab dopo le modifiche costituisce accettazione dei Termini rivisti." },
      { title: '10. Legge Applicabile', body: "Questi Termini sono regolati dalla legge applicabile. Qualsiasi disputa sarà risolta mediante negoziazione in buona fede. Per questioni legali: legal@solviqlab.com." },
      { title: '11. Contatto', body: "Domande su questi Termini?\nEmail: legal@solviqlab.com\nSito: https://solviqlab.com/it/contact" },
    ],
  },
  tr: {
    lastUpdated: '27 Temmuz 2026',
    warning: 'Önemli: SolviqLab hesap makineleri ve yapay zeka koçluğu yalnızca bilgilendirme amaçlıdır — tıbbi veya finansal tavsiye değildir.',
    sections: [
      { title: '1. Koşulların Kabul Edilmesi', body: "SolviqLab'a (solviqlab.com) erişerek veya kullanarak bu Hizmet Koşullarını kabul etmiş olursunuz. Kabul etmiyorsanız lütfen platformu kullanmayın." },
      { title: '2. Hizmet Açıklaması', body: "SolviqLab, sağlık, finans, matematik ve birim dönüşümü için ücretsiz çevrimiçi hesap makineleri sunar. DeepSeek API tarafından desteklenen Mia (sağlık) ve Alex (finans) aracılığıyla yapay zeka koçluğu da sunmaktayız.\n\nTüm temel özellikler ücretsizdir ve hesap veya kayıt gerektirmez." },
      { title: '3. Profesyonel Tavsiye Değildir', body: "SolviqLab hesap makineleri ve yapay zeka koçluğu yalnızca bilgilendirme ve eğitim amaçlıdır.\n\n• Sağlık hesap makineleri profesyonel tıbbi tavsiyenin YERİNİ TUTMAZ. Her zaman nitelikli bir sağlık uzmanına danışın.\n• Finans hesap makineleri finansal tavsiye DEĞİLDİR. Finansal kararlar almadan önce lisanslı bir danışmana başvurun.\n• Sonuçlar yaygın kabul görmüş formüllere dayalı tahminlerdir." },
      { title: '4. İzin Verilen Kullanım', body: "SolviqLab'ı kişisel, ticari olmayan amaçlarla kullanabilirsiniz. Şunları yapmamayı kabul edersiniz:\n• Hizmetlerimize tersine mühendislik, scraping veya aşırı yükleme girişimi\n• Hesap makinelerimize veya yapay zeka özelliklerine toplu sorgu için otomatik araçlar kullanma\n• SolviqLab sonuçlarını sertifikalı tıbbi veya finansal değerlendirmeler olarak sunma\n• Platformu yasadışı amaçlarla kullanma" },
      { title: '5. Fikri Mülkiyet', body: "SolviqLab'daki tüm içerik, tasarım, formüller ve yapay zeka koçluk deneyimleri SolviqLab'ın veya lisans verenlerinin mülkiyetindedir. Hesap makinesi sonuçlarını kişisel kullanım için paylaşabilirsiniz, ancak yazılı izin olmadan platform içeriğini ticari olarak çoğaltamazsınız." },
      { title: '6. Garanti Reddi', body: "SolviqLab, hiçbir garanti verilmeksizin \"olduğu gibi\" sunulmaktadır. Şunları garanti etmiyoruz:\n• Sonuçların her bireysel senaryo için doğru olacağını\n• Hizmetin kesintisiz kullanılabilir olacağını\n• Yapay zeka koç yanıtlarının hatasız olacağını" },
      { title: '7. Sorumluluk Sınırlaması', body: "Yasaların izin verdiği azami ölçüde, SolviqLab, hesap makinesi sonuçlarına veya yapay zeka koç çıktısına dayanma dahil, platformun kullanımından kaynaklanan dolaylı, arızi veya sonuçsal zararlardan sorumlu olmayacaktır." },
      { title: '8. Üçüncü Taraf Hizmetleri', body: "SolviqLab, DeepSeek (yapay zeka), Microsoft Clarity (analitik, onay ile) ve Vercel (barındırma) dahil üçüncü taraf hizmetleri kullanmaktadır. Bu hizmetlerin kullanımınız da kendi koşullarına tabidir." },
      { title: '9. Koşullardaki Değişiklikler', body: "Bu Koşulları istediğimiz zaman güncelleme hakkını saklı tutarız. Değişiklikler yayınlandıktan sonra SolviqLab kullanımına devam etmek revize edilmiş Koşulları kabul anlamına gelir." },
      { title: '10. Geçerli Hukuk', body: "Bu Koşullar yürürlükteki hukuka tabidir. Anlaşmazlıklar iyi niyet müzakeresi yoluyla çözülecektir. Hukuki sorular için: legal@solviqlab.com." },
      { title: '11. İletişim', body: "Bu Koşullar hakkında sorularınız mı var?\nE-posta: legal@solviqlab.com\nWeb sitesi: https://solviqlab.com/tr/contact" },
    ],
  },
  pt: {
    lastUpdated: '27 de julho de 2026',
    warning: 'Importante: as calculadoras e o coaching de IA do SolviqLab são apenas para fins informativos — não são aconselhamento médico ou financeiro.',
    sections: [
      { title: '1. Aceitação dos Termos', body: 'Ao acessar ou usar o SolviqLab (solviqlab.com), você concorda em estar vinculado a estes Termos de Serviço. Se não concordar, por favor não use a plataforma.' },
      { title: '2. Descrição do Serviço', body: 'SolviqLab oferece calculadoras online gratuitas para saúde, finanças, matemática e conversão de unidades. Também oferecemos coaching com IA através da Mia (saúde) e Alex (finanças), alimentado pela API DeepSeek.\n\nTodos os recursos principais são gratuitos e não exigem conta ou cadastro.' },
      { title: '3. Não é Aconselhamento Profissional', body: 'As calculadoras e o coaching de IA do SolviqLab são apenas para fins informativos e educacionais.\n\n• As calculadoras de saúde NÃO substituem aconselhamento médico profissional. Sempre consulte um profissional de saúde qualificado.\n• As calculadoras de finanças NÃO são aconselhamento financeiro. Consulte um assessor financeiro licenciado antes de tomar decisões.\n• Os resultados são estimativas baseadas em fórmulas amplamente aceitas.' },
      { title: '4. Uso Permitido', body: 'Você pode usar o SolviqLab para fins pessoais e não comerciais. Você concorda em não:\n• Tentar fazer engenharia reversa, scraping ou sobrecarregar nossos serviços\n• Usar ferramentas automatizadas para consultas em massa\n• Apresentar resultados do SolviqLab como avaliações médicas ou financeiras certificadas\n• Usar a plataforma para qualquer propósito ilegal' },
      { title: '5. Propriedade Intelectual', body: 'Todo o conteúdo, design, fórmulas e experiências de coaching de IA no SolviqLab são de propriedade do SolviqLab ou de seus licenciadores. Você pode compartilhar resultados para uso pessoal, mas não pode reproduzir ou redistribuir o conteúdo comercialmente sem permissão escrita.' },
      { title: '6. Isenção de Garantias', body: 'O SolviqLab é fornecido "como está" sem garantias de qualquer tipo. Não garantimos que:\n• Os resultados serão precisos para cada cenário individual\n• O serviço estará disponível sem interrupção\n• As respostas do coach de IA serão livres de erros' },
      { title: '7. Limitação de Responsabilidade', body: 'Na máxima extensão permitida por lei, o SolviqLab não será responsável por danos indiretos, incidentais ou consequentes decorrentes do uso da plataforma.' },
      { title: '8. Serviços de Terceiros', body: 'SolviqLab usa DeepSeek (IA), Microsoft Clarity (análises, com consentimento) e Vercel (hospedagem). O uso desses serviços também é regido pelos respectivos termos.' },
      { title: '9. Alterações nos Termos', body: 'Reservamo-nos o direito de atualizar estes Termos a qualquer momento. O uso continuado do SolviqLab após as alterações constitui sua aceitação dos Termos revisados.' },
      { title: '10. Lei Aplicável', body: 'Estes Termos são regidos pela lei aplicável. Quaisquer disputas serão resolvidas por negociação de boa fé. Para consultas jurídicas: legal@solviqlab.com.' },
      { title: '11. Contato', body: 'Dúvidas sobre estes Termos?\nEmail: legal@solviqlab.com\nSite: https://solviqlab.com/pt/contact' },
    ],
  },
  pl: {
    lastUpdated: '27 lipca 2026',
    warning: 'Ważne: kalkulatory i coaching AI SolviqLab służą wyłącznie celom informacyjnym — nie stanowią porady medycznej ani finansowej.',
    sections: [
      { title: '1. Akceptacja Warunków', body: 'Uzyskując dostęp do SolviqLab (solviqlab.com) lub korzystając z niego, zgadzasz się na przestrzeganie niniejszych Warunków Świadczenia Usług. Jeśli się nie zgadzasz, prosimy nie używać platformy.' },
      { title: '2. Opis Usługi', body: 'SolviqLab zapewnia bezpłatne kalkulatory online dla zdrowia, finansów, matematyki i konwersji jednostek. Oferujemy również coaching AI przez Mia (zdrowie) i Alex (finanse), zasilany przez API DeepSeek.\n\nWszystkie podstawowe funkcje są bezpłatne i nie wymagają konta ani rejestracji.' },
      { title: '3. Nie jest Poradą Profesjonalną', body: 'Kalkulatory i coaching AI SolviqLab służą wyłącznie celom informacyjnym i edukacyjnym.\n\n• Kalkulatory zdrowotne NIE zastępują profesjonalnej porady medycznej. Zawsze konsultuj się z wykwalifikowanym pracownikiem służby zdrowia.\n• Kalkulatory finansowe NIE są poradą finansową. Skonsultuj się z licencjonowanym doradcą przed podjęciem decyzji finansowych.\n• Wyniki są szacunkami opartymi na powszechnie akceptowanych formułach.' },
      { title: '4. Dozwolone Użycie', body: 'Możesz używać SolviqLab do celów osobistych i niekomercyjnych. Zgadzasz się nie:\n• Próbować inżynierii odwrotnej, scrapingu ani przeciążania naszych usług\n• Używać automatycznych narzędzi do masowych zapytań\n• Przedstawiać wyników SolviqLab jako certyfikowanych ocen medycznych lub finansowych\n• Używać platformy do jakichkolwiek celów niezgodnych z prawem' },
      { title: '5. Własność Intelektualna', body: 'Wszystkie treści, projekt, formuły i doświadczenia coachingu AI na SolviqLab są własnością SolviqLab lub jego licencjodawców. Możesz udostępniać wyniki do użytku osobistego, ale nie możesz reprodukować ani redystrybuować treści komercyjnie bez pisemnej zgody.' },
      { title: '6. Wyłączenie Gwarancji', body: 'SolviqLab jest dostarczany "w stanie takim, w jakim jest" bez jakichkolwiek gwarancji. Nie gwarantujemy, że:\n• Wyniki będą dokładne dla każdego scenariusza\n• Usługa będzie dostępna bez przerw\n• Odpowiedzi coacha AI będą wolne od błędów' },
      { title: '7. Ograniczenie Odpowiedzialności', body: 'W maksymalnym zakresie dozwolonym przez prawo, SolviqLab nie ponosi odpowiedzialności za pośrednie, przypadkowe ani wynikowe szkody wynikające z korzystania z platformy.' },
      { title: '8. Usługi Podmiotów Trzecich', body: 'SolviqLab korzysta z DeepSeek (AI), Microsoft Clarity (analityka, za zgodą) i Vercel (hosting). Korzystanie z tych usług podlega również ich własnym warunkom.' },
      { title: '9. Zmiany Warunków', body: 'Zastrzegamy sobie prawo do aktualizacji niniejszych Warunków w dowolnym momencie. Dalsze korzystanie z SolviqLab po zmianach oznacza akceptację zmienionych Warunków.' },
      { title: '10. Prawo Właściwe', body: 'Niniejsze Warunki podlegają obowiązującemu prawu. Wszelkie spory będą rozstrzygane w drodze negocjacji w dobrej wierze. W sprawach prawnych: legal@solviqlab.com.' },
      { title: '11. Kontakt', body: 'Pytania dotyczące niniejszych Warunków?\nEmail: legal@solviqlab.com\nStrona: https://solviqlab.com/pl/contact' },
    ],
  },
  nl: {
    lastUpdated: '27 juli 2026',
    warning: 'Belangrijk: de calculators en AI-coaching van SolviqLab zijn uitsluitend voor informatieve doeleinden — geen medisch of financieel advies.',
    sections: [
      { title: '1. Acceptatie van Voorwaarden', body: 'Door SolviqLab (solviqlab.com) te openen of te gebruiken, gaat u akkoord met deze Servicevoorwaarden. Als u niet akkoord gaat, gebruik de platform dan niet.' },
      { title: '2. Beschrijving van de Dienst', body: 'SolviqLab biedt gratis online calculators voor gezondheid, financiën, wiskunde en eenheidsconversie. We bieden ook AI-coaching via Mia (gezondheid) en Alex (financiën), aangedreven door de DeepSeek API.\n\nAlle kernfuncties zijn gratis en vereisen geen account of registratie.' },
      { title: '3. Geen Professioneel Advies', body: 'SolviqLab calculators en AI-coaching zijn uitsluitend voor informatieve en educatieve doeleinden.\n\n• Gezondheidscalculators zijn GEEN vervanging voor professioneel medisch advies. Raadpleeg altijd een gekwalificeerde zorgverlener.\n• Financiële calculators zijn GEEN financieel advies. Raadpleeg een erkend financieel adviseur voor financiële beslissingen.\n• Resultaten zijn schattingen op basis van algemeen aanvaarde formules.' },
      { title: '4. Toegestaan Gebruik', body: 'U mag SolviqLab gebruiken voor persoonlijke, niet-commerciële doeleinden. U stemt ermee in niet:\n• Reverse engineering, scraping of overbelasting van onze diensten te proberen\n• Geautomatiseerde tools te gebruiken voor massale zoekopdrachten\n• SolviqLab-resultaten voor te stellen als gecertificeerde medische of financiële beoordelingen\n• De platform te gebruiken voor onwettige doeleinden' },
      { title: '5. Intellectueel Eigendom', body: 'Alle inhoud, ontwerp, formules en AI-coachingservaringen op SolviqLab zijn eigendom van SolviqLab of haar licentiegevers. U mag resultaten delen voor persoonlijk gebruik, maar mag de inhoud niet commercieel reproduceren of verspreiden zonder schriftelijke toestemming.' },
      { title: '6. Uitsluiting van Garanties', body: 'SolviqLab wordt geleverd "zoals het is" zonder garanties van welke aard dan ook. We garanderen niet dat:\n• Resultaten voor elk individueel scenario nauwkeurig zijn\n• De dienst zonder onderbreking beschikbaar is\n• AI-coachreacties foutloos zijn' },
      { title: '7. Beperking van Aansprakelijkheid', body: 'Voor zover wettelijk toegestaan, is SolviqLab niet aansprakelijk voor indirecte, incidentele of gevolgschade voortvloeiend uit uw gebruik van de platform.' },
      { title: '8. Diensten van Derden', body: 'SolviqLab gebruikt DeepSeek (AI), Microsoft Clarity (analyses, met toestemming) en Vercel (hosting). Uw gebruik van deze diensten valt ook onder hun respectieve voorwaarden.' },
      { title: '9. Wijzigingen in Voorwaarden', body: 'Wij behouden ons het recht voor deze Voorwaarden op elk moment bij te werken. Voortgezet gebruik van SolviqLab na wijzigingen geldt als acceptatie van de herziene Voorwaarden.' },
      { title: '10. Toepasselijk Recht', body: 'Deze Voorwaarden worden beheerst door het toepasselijk recht. Geschillen worden opgelost via onderhandeling te goeder trouw. Voor juridische vragen: legal@solviqlab.com.' },
      { title: '11. Contact', body: 'Vragen over deze Voorwaarden?\nE-mail: legal@solviqlab.com\nWebsite: https://solviqlab.com/nl/contact' },
    ],
  },
}

// ===== CONTACT TOPICS =====
const contactTopicsData: Record<string, ContactTopic[]> = {
  en: [
    { icon: '🐛', label: 'Bug Report', email: 'support@solviqlab.com', desc: "Found something broken? Tell us and we'll fix it fast." },
    { icon: '💡', label: 'Feature Request', email: 'support@solviqlab.com', desc: "Have an idea for a new calculator or quiz? We'd love to hear it." },
    { icon: '🤝', label: 'Partnership', email: 'hello@solviqlab.com', desc: 'Interested in integrating SolviqLab into your platform or product?' },
    { icon: '🔒', label: 'Privacy & Data', email: 'privacy@solviqlab.com', desc: 'Questions about how we handle your data.' },
    { icon: '⚖️', label: 'Legal', email: 'legal@solviqlab.com', desc: 'Legal inquiries, licensing, or DMCA requests.' },
  ],
  uk: [
    { icon: '🐛', label: 'Звіт про помилку', email: 'support@solviqlab.com', desc: 'Знайшли щось зламане? Повідомте нас, і ми швидко виправимо.' },
    { icon: '💡', label: 'Запит функції', email: 'support@solviqlab.com', desc: 'Маєте ідею для нового калькулятора або тесту? Будемо раді почути.' },
    { icon: '🤝', label: 'Партнерство', email: 'hello@solviqlab.com', desc: 'Хочете інтегрувати SolviqLab у свою платформу або продукт?' },
    { icon: '🔒', label: 'Конфіденційність та дані', email: 'privacy@solviqlab.com', desc: 'Питання про те, як ми обробляємо ваші дані.' },
    { icon: '⚖️', label: 'Юридичні питання', email: 'legal@solviqlab.com', desc: 'Юридичні запити, ліцензування або DMCA.' },
  ],
  es: [
    { icon: '🐛', label: 'Informe de Error', email: 'support@solviqlab.com', desc: '¿Encontraste algo roto? Dínoslo y lo arreglaremos rápido.' },
    { icon: '💡', label: 'Solicitud de Función', email: 'support@solviqlab.com', desc: '¿Tienes una idea para una nueva calculadora o quiz? Nos encantaría escucharla.' },
    { icon: '🤝', label: 'Asociación', email: 'hello@solviqlab.com', desc: '¿Te interesa integrar SolviqLab en tu plataforma o producto?' },
    { icon: '🔒', label: 'Privacidad y Datos', email: 'privacy@solviqlab.com', desc: 'Preguntas sobre cómo gestionamos tus datos.' },
    { icon: '⚖️', label: 'Legal', email: 'legal@solviqlab.com', desc: 'Consultas legales, licencias o solicitudes DMCA.' },
  ],
  fr: [
    { icon: '🐛', label: 'Signalement de Bug', email: 'support@solviqlab.com', desc: 'Vous avez trouvé quelque chose de cassé ? Dites-le nous et nous le réglerons rapidement.' },
    { icon: '💡', label: 'Demande de Fonctionnalité', email: 'support@solviqlab.com', desc: 'Une idée pour une nouvelle calculatrice ou un quiz ? Nous serions ravis de vous entendre.' },
    { icon: '🤝', label: 'Partenariat', email: 'hello@solviqlab.com', desc: 'Intéressé par l\'intégration de SolviqLab dans votre plateforme ou produit ?' },
    { icon: '🔒', label: 'Confidentialité et Données', email: 'privacy@solviqlab.com', desc: 'Questions sur la façon dont nous gérons vos données.' },
    { icon: '⚖️', label: 'Juridique', email: 'legal@solviqlab.com', desc: 'Demandes juridiques, licences ou demandes DMCA.' },
  ],
  de: [
    { icon: '🐛', label: 'Fehlerbericht', email: 'support@solviqlab.com', desc: 'Etwas Defektes gefunden? Sagen Sie es uns und wir beheben es schnell.' },
    { icon: '💡', label: 'Funktionsanfrage', email: 'support@solviqlab.com', desc: 'Haben Sie eine Idee für einen neuen Rechner oder Quiz? Wir freuen uns darüber.' },
    { icon: '🤝', label: 'Partnerschaft', email: 'hello@solviqlab.com', desc: 'Möchten Sie SolviqLab in Ihre Plattform oder Ihr Produkt integrieren?' },
    { icon: '🔒', label: 'Datenschutz & Daten', email: 'privacy@solviqlab.com', desc: 'Fragen zum Umgang mit Ihren Daten.' },
    { icon: '⚖️', label: 'Rechtliches', email: 'legal@solviqlab.com', desc: 'Rechtliche Anfragen, Lizenzen oder DMCA-Anfragen.' },
  ],
  it: [
    { icon: '🐛', label: 'Segnalazione Bug', email: 'support@solviqlab.com', desc: 'Hai trovato qualcosa di rotto? Dimmelo e lo sistemeremo velocemente.' },
    { icon: '💡', label: 'Richiesta Funzionalità', email: 'support@solviqlab.com', desc: 'Hai un\'idea per una nuova calcolatrice o un quiz? Ci farebbe piacere sentirla.' },
    { icon: '🤝', label: 'Partnership', email: 'hello@solviqlab.com', desc: 'Sei interessato a integrare SolviqLab nella tua piattaforma o prodotto?' },
    { icon: '🔒', label: 'Privacy e Dati', email: 'privacy@solviqlab.com', desc: 'Domande su come gestiamo i tuoi dati.' },
    { icon: '⚖️', label: 'Legale', email: 'legal@solviqlab.com', desc: 'Richieste legali, licenze o richieste DMCA.' },
  ],
  tr: [
    { icon: '🐛', label: 'Hata Bildirimi', email: 'support@solviqlab.com', desc: 'Bozuk bir şey mi buldunuz? Bize bildirin, hemen düzeltelim.' },
    { icon: '💡', label: 'Özellik Talebi', email: 'support@solviqlab.com', desc: 'Yeni bir hesap makinesi veya quiz fikriniz mi var? Duymak isteriz.' },
    { icon: '🤝', label: 'Ortaklık', email: 'hello@solviqlab.com', desc: 'SolviqLab\'ı platformunuza veya ürününüze entegre etmek ister misiniz?' },
    { icon: '🔒', label: 'Gizlilik ve Veriler', email: 'privacy@solviqlab.com', desc: 'Verilerinizi nasıl işlediğimize dair sorularınız.' },
    { icon: '⚖️', label: 'Hukuki', email: 'legal@solviqlab.com', desc: 'Hukuki talepler, lisanslama veya DMCA talepleri.' },
  ],
  pt: [
    { icon: '🐛', label: 'Relato de Bug', email: 'support@solviqlab.com', desc: 'Encontrou algo quebrado? Nos diga e resolveremos rapidamente.' },
    { icon: '💡', label: 'Solicitação de Recurso', email: 'support@solviqlab.com', desc: 'Tem uma ideia para uma nova calculadora ou quiz? Adoraríamos ouvir.' },
    { icon: '🤝', label: 'Parceria', email: 'hello@solviqlab.com', desc: 'Interessado em integrar o SolviqLab na sua plataforma ou produto?' },
    { icon: '🔒', label: 'Privacidade e Dados', email: 'privacy@solviqlab.com', desc: 'Dúvidas sobre como tratamos seus dados.' },
    { icon: '⚖️', label: 'Jurídico', email: 'legal@solviqlab.com', desc: 'Consultas jurídicas, licenciamento ou solicitações DMCA.' },
  ],
  pl: [
    { icon: '🐛', label: 'Zgłoszenie Błędu', email: 'support@solviqlab.com', desc: 'Znalazłeś coś zepsutego? Powiedz nam, a szybko to naprawimy.' },
    { icon: '💡', label: 'Prośba o Funkcję', email: 'support@solviqlab.com', desc: 'Masz pomysł na nowy kalkulator lub quiz? Chętnie usłyszymy.' },
    { icon: '🤝', label: 'Partnerstwo', email: 'hello@solviqlab.com', desc: 'Chcesz zintegrować SolviqLab ze swoją platformą lub produktem?' },
    { icon: '🔒', label: 'Prywatność i Dane', email: 'privacy@solviqlab.com', desc: 'Pytania dotyczące sposobu obsługi Twoich danych.' },
    { icon: '⚖️', label: 'Sprawy Prawne', email: 'legal@solviqlab.com', desc: 'Zapytania prawne, licencjonowanie lub wnioski DMCA.' },
  ],
  nl: [
    { icon: '🐛', label: 'Foutrapport', email: 'support@solviqlab.com', desc: 'Iets gebroken gevonden? Laat het ons weten en we lossen het snel op.' },
    { icon: '💡', label: 'Functieverzoek', email: 'support@solviqlab.com', desc: 'Heeft u een idee voor een nieuwe calculator of quiz? We horen het graag.' },
    { icon: '🤝', label: 'Samenwerking', email: 'hello@solviqlab.com', desc: 'Geïnteresseerd in het integreren van SolviqLab in uw platform of product?' },
    { icon: '🔒', label: 'Privacy & Gegevens', email: 'privacy@solviqlab.com', desc: 'Vragen over hoe we uw gegevens verwerken.' },
    { icon: '⚖️', label: 'Juridisch', email: 'legal@solviqlab.com', desc: 'Juridische vragen, licenties of DMCA-verzoeken.' },
  ],
}

export function getPrivacyContent(lang: string) {
  return privacyData[lang] ?? privacyData.en
}

export function getTermsContent(lang: string) {
  return termsData[lang] ?? termsData.en
}

export function getContactTopics(lang: string): ContactTopic[] {
  return contactTopicsData[lang] ?? contactTopicsData.en
}
