const strings = {
  en: {
    heroTitle1: 'Calculate Anything.', heroTitle2: ' Instantly.',
    heroSubtitle: (n: number) => `${n}+ free professional calculators for health, finance, math, and unit conversions. No registration. No ads. Just answers.`,
    heroSources: 'Formulas sourced from:', heroCta1: 'Try BMI Calculator →', heroCta2: 'Mortgage Calculator',
    featuredTitle: 'Most Popular Calculators', featuredSubtitle: 'The tools millions of people use every day.',
    openCalc: 'Open Calculator →', sourcesLabel: 'Formulas sourced from:',
    searchPlaceholder: 'Search calculators...', tabAll: 'All', tabHealth: '❤️ Health', tabFinance: '💰 Finance', tabMath: '🧮 Math', tabConversion: '🔄 Converters',
    countSingle: (n: number) => `${n} calculator`, countPlural: (n: number) => `${n} calculators`, noResults: (q: string) => `No calculators found for "${q}"`,
    breadcrumbHome: 'Home', medicallyReviewed: 'Medically reviewed', expertReviewed: 'Expert reviewed', journeyTitle: 'Continue Your Journey',
    exploreAll: (cat: string) => `Explore all ${cat} calculators →`,
    categoryLabels: { health: 'Health', finance: 'Finance', math: 'Math', conversion: 'Converters' } as Record<string, string>,
    copyResult: '📋 Copy result', copied: '✅ Copied!', shareLink: '🔗 Share link', print: '🖨️ Print',
    whatThisMeans: 'What this means', whatToDoNext: 'What to do next',
    healthyWeightFor: 'Healthy weight for your height:', estBodyFat: 'Est. body fat:',
    bmiContext: (bmi: string, cat: string) => `Your BMI of ${bmi} falls in the ${cat} range.`,
    bmiRangeNormal: 'The healthy range is 18.5–24.9.', bmiRangeOverweight: 'The healthy range is 18.5–24.9. Overweight is 25–29.9.',
    bmiRangeUnder: 'The healthy range starts at 18.5.',
    bmiPrimeLabel: 'BMI Prime', bmiPrimeSub: '(1.0 = upper normal)', ponderalLabel: 'Ponderal Index',
    categoryLabel: 'Category', whoStandard: 'WHO standard', nextSteps: 'Next Steps', methodologySources: 'Methodology & Sources',
    ctaCalories: 'Calculate your daily calories →', ctaDeficit: 'Calculate your calorie deficit →', ctaIdealWeight: 'Calculate your ideal weight →',
    relatedTdee: 'TDEE Calculator', relatedTdeeDesc: 'Your total daily calorie needs',
    relatedBodyFat: 'Body Fat Calculator', relatedBodyFatDesc: 'Estimate your body fat %',
    relatedIdealWeight: 'Ideal Weight Calculator', relatedIdealWeightDesc: 'Your optimal weight range',
    relatedCalorieDeficit: 'Calorie Deficit', relatedCalorieDeficitDesc: 'Plan your weight loss safely',
    optional: 'optional',
    footerTagline: 'Free professional calculators for health, finance, math, and unit conversions. Formulas backed by WHO, CFPB, NIST, and ISO.',
    viewAll: 'View all →', footerCopyright: (year: number) => `© ${year} SolviqLab. All rights reserved. Not medical or financial advice.`,
    footerSources: 'Formulas sourced from WHO · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `All ${cat} Calculators`, categoryPageCount: (n: number) => `${n} free calculators`,
    categoryPageCalc: 'Calculate →', categoryPageBack: '← Explore all calculators',
    contentWhatIs: (kw: string) => `What is the ${kw}?`,
    contentFormula: (kw: string) => `${kw} Formula`,
    contentExample: (kw: string) => `${kw} Example`,
    contentHowTo: (kw: string) => `How to Use the ${kw}`,
    contentWhyMatters: (kw: string) => `Why ${kw} Matters`,
    contentLimitations: 'Limitations & Accuracy',
    contentTips: 'Practical Tips',
    apiAccess: 'API Access', apiComingSoon: 'Coming Soon',
    apiDeveloper: 'REST API for developers. Integrate this tool into your app.',
    trustedSources: 'Trusted Sources & Methodology',
    faqTitle: 'Frequently Asked Questions',
  },
  uk: {
    heroTitle1: 'Рахуйте будь-що.', heroTitle2: ' Миттєво.',
    heroSubtitle: (n: number) => `${n}+ безкоштовних професійних калькуляторів для здоров'я, фінансів, математики та одиниць виміру. Без реєстрації. Без реклами. Тільки відповіді.`,
    heroSources: 'Формули з джерел:', heroCta1: 'Спробувати BMI →', heroCta2: 'Іпотечний калькулятор',
    featuredTitle: 'Найпопулярніші калькулятори', featuredSubtitle: 'Інструменти, якими користуються мільйони щодня.',
    openCalc: 'Відкрити →', sourcesLabel: 'Формули з джерел:',
    searchPlaceholder: 'Пошук калькуляторів...', tabAll: 'Всі', tabHealth: "❤️ Здоров'я", tabFinance: '💰 Фінанси', tabMath: '🧮 Математика', tabConversion: '🔄 Конвертери',
    countSingle: (n: number) => `${n} калькулятор`, countPlural: (n: number) => `${n} калькуляторів`, noResults: (q: string) => `Калькуляторів для "${q}" не знайдено`,
    breadcrumbHome: 'Головна', medicallyReviewed: 'Медично перевірено', expertReviewed: 'Перевірено експертом', journeyTitle: 'Продовжити подорож',
    exploreAll: (cat: string) => `Всі калькулятори: ${cat} →`,
    categoryLabels: { health: "Здоров'я", finance: 'Фінанси', math: 'Математика', conversion: 'Конвертери' } as Record<string, string>,
    copyResult: '📋 Копіювати', copied: '✅ Скопійовано!', shareLink: '🔗 Поділитись', print: '🖨️ Друк',
    whatThisMeans: 'Що це означає', whatToDoNext: 'Що робити далі',
    healthyWeightFor: 'Здорова вага для вашого зросту:', estBodyFat: 'Приблизний % жиру:',
    bmiContext: (bmi: string, cat: string) => `Ваш ІМТ ${bmi} відповідає категорії "${cat}".`,
    bmiRangeNormal: 'Норма — 18.5–24.9.', bmiRangeOverweight: 'Норма — 18.5–24.9. Надмірна вага — 25–29.9.',
    bmiRangeUnder: 'Норма починається від 18.5.',
    bmiPrimeLabel: 'ІМТ-прайм', bmiPrimeSub: '(1.0 = верхня межа норми)', ponderalLabel: 'Понделяровий індекс',
    categoryLabel: 'Категорія', whoStandard: 'Стандарт ВООЗ', nextSteps: 'Наступні кроки', methodologySources: 'Методологія та джерела',
    ctaCalories: 'Розрахувати добову норму калорій →', ctaDeficit: 'Розрахувати дефіцит калорій →', ctaIdealWeight: 'Розрахувати ідеальну вагу →',
    relatedTdee: 'Калькулятор TDEE', relatedTdeeDesc: 'Ваша добова норма калорій',
    relatedBodyFat: 'Калькулятор % жиру', relatedBodyFatDesc: 'Оцініть відсоток жиру в тілі',
    relatedIdealWeight: 'Ідеальна вага', relatedIdealWeightDesc: 'Ваш оптимальний діапазон ваги',
    relatedCalorieDeficit: 'Дефіцит калорій', relatedCalorieDeficitDesc: 'Безпечне зниження ваги',
    optional: "необов'язково",
    footerTagline: "Безкоштовні професійні калькулятори для здоров'я, фінансів, математики та одиниць виміру. Формули ВООЗ, CFPB, NIST та ISO.",
    viewAll: 'Всі →', footerCopyright: (year: number) => `© ${year} SolviqLab. Всі права захищені. Не є медичною або фінансовою порадою.`,
    footerSources: 'Формули: ВООЗ · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Всі калькулятори: ${cat}`, categoryPageCount: (n: number) => `${n} безкоштовних калькуляторів`,
    categoryPageCalc: 'Розрахувати →', categoryPageBack: '← Всі калькулятори',
    contentWhatIs: (kw: string) => `Що таке ${kw}?`,
    contentFormula: (kw: string) => `Формула ${kw}`,
    contentExample: (kw: string) => `Приклад ${kw}`,
    contentHowTo: (kw: string) => `Як користуватись ${kw}`,
    contentWhyMatters: (kw: string) => `Чому ${kw} важливий`,
    contentLimitations: 'Обмеження та точність',
    contentTips: 'Практичні поради',
    apiAccess: 'API доступ', apiComingSoon: 'Незабаром',
    apiDeveloper: 'REST API для розробників. Інтегруйте цей інструмент у свій застосунок.',
    trustedSources: 'Джерела та методологія',
    faqTitle: 'Часті запитання',
  },
  es: {
    heroTitle1: 'Calcula Cualquier Cosa.', heroTitle2: ' Instantáneamente.',
    heroSubtitle: (n: number) => `${n}+ calculadoras profesionales gratuitas para salud, finanzas, matemáticas y conversiones. Sin registro. Sin anuncios. Solo respuestas.`,
    heroSources: 'Fórmulas obtenidas de:', heroCta1: 'Probar Calculadora de IMC →', heroCta2: 'Calculadora de Hipoteca',
    featuredTitle: 'Calculadoras Más Populares', featuredSubtitle: 'Las herramientas que millones de personas usan cada día.',
    openCalc: 'Abrir Calculadora →', sourcesLabel: 'Fórmulas obtenidas de:',
    searchPlaceholder: 'Buscar calculadoras...', tabAll: 'Todas', tabHealth: '❤️ Salud', tabFinance: '💰 Finanzas', tabMath: '🧮 Matemáticas', tabConversion: '🔄 Conversores',
    countSingle: (n: number) => `${n} calculadora`, countPlural: (n: number) => `${n} calculadoras`, noResults: (q: string) => `No se encontraron calculadoras para "${q}"`,
    breadcrumbHome: 'Inicio', medicallyReviewed: 'Revisado médicamente', expertReviewed: 'Revisado por expertos', journeyTitle: 'Continúa Tu Viaje',
    exploreAll: (cat: string) => `Ver todas las calculadoras de ${cat} →`,
    categoryLabels: { health: 'Salud', finance: 'Finanzas', math: 'Matemáticas', conversion: 'Conversores' } as Record<string, string>,
    copyResult: '📋 Copiar resultado', copied: '✅ ¡Copiado!', shareLink: '🔗 Compartir enlace', print: '🖨️ Imprimir',
    whatThisMeans: 'Qué significa esto', whatToDoNext: 'Qué hacer a continuación',
    healthyWeightFor: 'Peso saludable para tu altura:', estBodyFat: 'Grasa corporal estimada:',
    bmiContext: (bmi: string, cat: string) => `Tu IMC de ${bmi} está en el rango de ${cat}.`,
    bmiRangeNormal: 'El rango saludable es 18.5–24.9.', bmiRangeOverweight: 'El rango saludable es 18.5–24.9. Sobrepeso es 25–29.9.',
    bmiRangeUnder: 'El rango saludable comienza en 18.5.',
    bmiPrimeLabel: 'IMC Prime', bmiPrimeSub: '(1.0 = límite superior normal)', ponderalLabel: 'Índice Ponderal',
    categoryLabel: 'Categoría', whoStandard: 'Estándar OMS', nextSteps: 'Próximos Pasos', methodologySources: 'Metodología y Fuentes',
    ctaCalories: 'Calcular tus calorías diarias →', ctaDeficit: 'Calcular tu déficit calórico →', ctaIdealWeight: 'Calcular tu peso ideal →',
    relatedTdee: 'Calculadora TDEE', relatedTdeeDesc: 'Tus necesidades calóricas diarias totales',
    relatedBodyFat: 'Calculadora de Grasa Corporal', relatedBodyFatDesc: 'Estima tu porcentaje de grasa',
    relatedIdealWeight: 'Calculadora de Peso Ideal', relatedIdealWeightDesc: 'Tu rango de peso óptimo',
    relatedCalorieDeficit: 'Déficit Calórico', relatedCalorieDeficitDesc: 'Planifica tu pérdida de peso de forma segura',
    optional: 'opcional',
    footerTagline: 'Calculadoras profesionales gratuitas para salud, finanzas, matemáticas y conversiones. Fórmulas respaldadas por OMS, CFPB, NIST e ISO.',
    viewAll: 'Ver todas →', footerCopyright: (year: number) => `© ${year} SolviqLab. Todos los derechos reservados. No es consejo médico ni financiero.`,
    footerSources: 'Fórmulas de OMS · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Todas las Calculadoras de ${cat}`, categoryPageCount: (n: number) => `${n} calculadoras gratuitas`,
    categoryPageCalc: 'Calcular →', categoryPageBack: '← Ver todas las calculadoras',
    contentWhatIs: (kw: string) => `¿Qué es el ${kw}?`,
    contentFormula: (kw: string) => `Fórmula del ${kw}`,
    contentExample: (kw: string) => `Ejemplo del ${kw}`,
    contentHowTo: (kw: string) => `Cómo usar el ${kw}`,
    contentWhyMatters: (kw: string) => `Por Qué Importa el ${kw}`,
    contentLimitations: 'Limitaciones y Precisión',
    contentTips: 'Consejos Prácticos',
    apiAccess: 'Acceso API', apiComingSoon: 'Próximamente',
    apiDeveloper: 'API REST para desarrolladores. Integra esta herramienta en tu app.',
    trustedSources: 'Fuentes y Metodología',
    faqTitle: 'Preguntas Frecuentes',
  },
  pt: {
    heroTitle1: 'Calcule Qualquer Coisa.', heroTitle2: ' Instantaneamente.',
    heroSubtitle: (n: number) => `${n}+ calculadoras profissionais gratuitas para saúde, finanças, matemática e conversões. Sem registro. Sem anúncios. Só respostas.`,
    heroSources: 'Fórmulas obtidas de:', heroCta1: 'Experimentar Calculadora de IMC →', heroCta2: 'Calculadora de Hipoteca',
    featuredTitle: 'Calculadoras Mais Populares', featuredSubtitle: 'As ferramentas que milhões de pessoas usam todos os dias.',
    openCalc: 'Abrir Calculadora →', sourcesLabel: 'Fórmulas obtidas de:',
    searchPlaceholder: 'Pesquisar calculadoras...', tabAll: 'Todas', tabHealth: '❤️ Saúde', tabFinance: '💰 Finanças', tabMath: '🧮 Matemática', tabConversion: '🔄 Conversores',
    countSingle: (n: number) => `${n} calculadora`, countPlural: (n: number) => `${n} calculadoras`, noResults: (q: string) => `Nenhuma calculadora encontrada para "${q}"`,
    breadcrumbHome: 'Início', medicallyReviewed: 'Revisado medicamente', expertReviewed: 'Revisado por especialistas', journeyTitle: 'Continue Sua Jornada',
    exploreAll: (cat: string) => `Ver todas as calculadoras de ${cat} →`,
    categoryLabels: { health: 'Saúde', finance: 'Finanças', math: 'Matemática', conversion: 'Conversores' } as Record<string, string>,
    copyResult: '📋 Copiar resultado', copied: '✅ Copiado!', shareLink: '🔗 Compartilhar link', print: '🖨️ Imprimir',
    whatThisMeans: 'O que isso significa', whatToDoNext: 'O que fazer a seguir',
    healthyWeightFor: 'Peso saudável para sua altura:', estBodyFat: 'Gordura corporal estimada:',
    bmiContext: (bmi: string, cat: string) => `Seu IMC de ${bmi} está na faixa de ${cat}.`,
    bmiRangeNormal: 'A faixa saudável é 18.5–24.9.', bmiRangeOverweight: 'A faixa saudável é 18.5–24.9. Sobrepeso é 25–29.9.',
    bmiRangeUnder: 'A faixa saudável começa em 18.5.',
    bmiPrimeLabel: 'IMC Prime', bmiPrimeSub: '(1.0 = limite superior normal)', ponderalLabel: 'Índice Ponderal',
    categoryLabel: 'Categoria', whoStandard: 'Padrão OMS', nextSteps: 'Próximos Passos', methodologySources: 'Metodologia e Fontes',
    ctaCalories: 'Calcular suas calorias diárias →', ctaDeficit: 'Calcular seu déficit calórico →', ctaIdealWeight: 'Calcular seu peso ideal →',
    relatedTdee: 'Calculadora TDEE', relatedTdeeDesc: 'Suas necessidades calóricas diárias totais',
    relatedBodyFat: 'Calculadora de Gordura Corporal', relatedBodyFatDesc: 'Estime seu percentual de gordura',
    relatedIdealWeight: 'Calculadora de Peso Ideal', relatedIdealWeightDesc: 'Sua faixa de peso ideal',
    relatedCalorieDeficit: 'Déficit Calórico', relatedCalorieDeficitDesc: 'Planeje sua perda de peso com segurança',
    optional: 'opcional',
    footerTagline: 'Calculadoras profissionais gratuitas para saúde, finanças, matemática e conversões. Fórmulas respaldadas por OMS, CFPB, NIST e ISO.',
    viewAll: 'Ver todas →', footerCopyright: (year: number) => `© ${year} SolviqLab. Todos os direitos reservados. Não é conselho médico ou financeiro.`,
    footerSources: 'Fórmulas de OMS · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Todas as Calculadoras de ${cat}`, categoryPageCount: (n: number) => `${n} calculadoras gratuitas`,
    categoryPageCalc: 'Calcular →', categoryPageBack: '← Ver todas as calculadoras',
    contentWhatIs: (kw: string) => `O que é o ${kw}?`,
    contentFormula: (kw: string) => `Fórmula do ${kw}`,
    contentExample: (kw: string) => `Exemplo do ${kw}`,
    contentHowTo: (kw: string) => `Como usar o ${kw}`,
    contentWhyMatters: (kw: string) => `Por Que o ${kw} Importa`,
    contentLimitations: 'Limitações e Precisão',
    contentTips: 'Dicas Práticas',
    apiAccess: 'Acesso API', apiComingSoon: 'Em Breve',
    apiDeveloper: 'API REST para desenvolvedores. Integre esta ferramenta no seu app.',
    trustedSources: 'Fontes e Metodologia',
    faqTitle: 'Perguntas Frequentes',
  },
  fr: {
    heroTitle1: 'Calculez Tout.', heroTitle2: ' Instantanément.',
    heroSubtitle: (n: number) => `${n}+ calculatrices professionnelles gratuites pour la santé, les finances, les maths et les conversions. Sans inscription. Sans pub. Juste des réponses.`,
    heroSources: 'Formules issues de :', heroCta1: 'Essayer la calculatrice IMC →', heroCta2: 'Calculatrice Hypothèque',
    featuredTitle: 'Calculatrices les Plus Populaires', featuredSubtitle: 'Les outils utilisés par des millions de personnes chaque jour.',
    openCalc: 'Ouvrir →', sourcesLabel: 'Formules issues de :',
    searchPlaceholder: 'Rechercher des calculatrices...', tabAll: 'Toutes', tabHealth: '❤️ Santé', tabFinance: '💰 Finance', tabMath: '🧮 Maths', tabConversion: '🔄 Convertisseurs',
    countSingle: (n: number) => `${n} calculatrice`, countPlural: (n: number) => `${n} calculatrices`, noResults: (q: string) => `Aucune calculatrice trouvée pour « ${q} »`,
    breadcrumbHome: 'Accueil', medicallyReviewed: 'Validé médicalement', expertReviewed: 'Validé par des experts', journeyTitle: 'Continuez Votre Parcours',
    exploreAll: (cat: string) => `Voir toutes les calculatrices ${cat} →`,
    categoryLabels: { health: 'Santé', finance: 'Finance', math: 'Maths', conversion: 'Convertisseurs' } as Record<string, string>,
    copyResult: '📋 Copier le résultat', copied: '✅ Copié !', shareLink: '🔗 Partager le lien', print: '🖨️ Imprimer',
    whatThisMeans: 'Ce que cela signifie', whatToDoNext: 'Que faire ensuite',
    healthyWeightFor: 'Poids santé pour votre taille :', estBodyFat: 'Graisse corporelle estimée :',
    bmiContext: (bmi: string, cat: string) => `Votre IMC de ${bmi} se situe dans la plage ${cat}.`,
    bmiRangeNormal: 'La plage saine est 18,5–24,9.', bmiRangeOverweight: 'La plage saine est 18,5–24,9. Surpoids : 25–29,9.',
    bmiRangeUnder: 'La plage saine commence à 18,5.',
    bmiPrimeLabel: 'IMC Prime', bmiPrimeSub: '(1,0 = limite supérieure normale)', ponderalLabel: 'Indice Pondéral',
    categoryLabel: 'Catégorie', whoStandard: 'Norme OMS', nextSteps: 'Prochaines Étapes', methodologySources: 'Méthodologie et Sources',
    ctaCalories: 'Calculer vos calories quotidiennes →', ctaDeficit: 'Calculer votre déficit calorique →', ctaIdealWeight: 'Calculer votre poids idéal →',
    relatedTdee: 'Calculatrice TDEE', relatedTdeeDesc: 'Vos besoins caloriques journaliers totaux',
    relatedBodyFat: 'Calculatrice de Graisse Corporelle', relatedBodyFatDesc: 'Estimez votre pourcentage de graisse',
    relatedIdealWeight: 'Calculatrice de Poids Idéal', relatedIdealWeightDesc: 'Votre plage de poids optimale',
    relatedCalorieDeficit: 'Déficit Calorique', relatedCalorieDeficitDesc: 'Planifiez votre perte de poids en toute sécurité',
    optional: 'optionnel',
    footerTagline: 'Calculatrices professionnelles gratuites pour la santé, les finances, les maths et les conversions. Formules OMS, CFPB, NIST et ISO.',
    viewAll: 'Voir tout →', footerCopyright: (year: number) => `© ${year} SolviqLab. Tous droits réservés. Pas de conseil médical ou financier.`,
    footerSources: 'Formules de OMS · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Toutes les Calculatrices ${cat}`, categoryPageCount: (n: number) => `${n} calculatrices gratuites`,
    categoryPageCalc: 'Calculer →', categoryPageBack: '← Voir toutes les calculatrices',
    contentWhatIs: (kw: string) => `Qu'est-ce que le ${kw} ?`,
    contentFormula: (kw: string) => `Formule du ${kw}`,
    contentExample: (kw: string) => `Exemple du ${kw}`,
    contentHowTo: (kw: string) => `Comment utiliser le ${kw}`,
    contentWhyMatters: (kw: string) => `Pourquoi le ${kw} est Important`,
    contentLimitations: 'Limites et Précision',
    contentTips: 'Conseils Pratiques',
    apiAccess: 'Accès API', apiComingSoon: 'Bientôt disponible',
    apiDeveloper: 'API REST pour les développeurs. Intégrez cet outil dans votre application.',
    trustedSources: 'Sources et Méthodologie',
    faqTitle: 'Questions Fréquentes',
  },
  de: {
    heroTitle1: 'Alles Berechnen.', heroTitle2: ' Sofort.',
    heroSubtitle: (n: number) => `${n}+ kostenlose professionelle Rechner für Gesundheit, Finanzen, Mathematik und Einheitenumrechnung. Keine Anmeldung. Keine Werbung. Nur Antworten.`,
    heroSources: 'Formeln aus:', heroCta1: 'BMI-Rechner ausprobieren →', heroCta2: 'Hypothekenrechner',
    featuredTitle: 'Beliebteste Rechner', featuredSubtitle: 'Die Werkzeuge, die Millionen Menschen täglich nutzen.',
    openCalc: 'Rechner öffnen →', sourcesLabel: 'Formeln aus:',
    searchPlaceholder: 'Rechner suchen...', tabAll: 'Alle', tabHealth: '❤️ Gesundheit', tabFinance: '💰 Finanzen', tabMath: '🧮 Mathematik', tabConversion: '🔄 Umrechner',
    countSingle: (n: number) => `${n} Rechner`, countPlural: (n: number) => `${n} Rechner`, noResults: (q: string) => `Keine Rechner für „${q}" gefunden`,
    breadcrumbHome: 'Startseite', medicallyReviewed: 'Medizinisch geprüft', expertReviewed: 'Von Experten geprüft', journeyTitle: 'Ihre Reise Fortsetzen',
    exploreAll: (cat: string) => `Alle ${cat}-Rechner anzeigen →`,
    categoryLabels: { health: 'Gesundheit', finance: 'Finanzen', math: 'Mathematik', conversion: 'Umrechner' } as Record<string, string>,
    copyResult: '📋 Ergebnis kopieren', copied: '✅ Kopiert!', shareLink: '🔗 Link teilen', print: '🖨️ Drucken',
    whatThisMeans: 'Was das bedeutet', whatToDoNext: 'Was als nächstes zu tun ist',
    healthyWeightFor: 'Gesundes Gewicht für Ihre Größe:', estBodyFat: 'Geschätzter Körperfettanteil:',
    bmiContext: (bmi: string, cat: string) => `Ihr BMI von ${bmi} liegt im Bereich ${cat}.`,
    bmiRangeNormal: 'Der gesunde Bereich ist 18,5–24,9.', bmiRangeOverweight: 'Der gesunde Bereich ist 18,5–24,9. Übergewicht ist 25–29,9.',
    bmiRangeUnder: 'Der gesunde Bereich beginnt bei 18,5.',
    bmiPrimeLabel: 'BMI-Prime', bmiPrimeSub: '(1,0 = obere Normalgrenze)', ponderalLabel: 'Ponderaler Index',
    categoryLabel: 'Kategorie', whoStandard: 'WHO-Standard', nextSteps: 'Nächste Schritte', methodologySources: 'Methodik & Quellen',
    ctaCalories: 'Täglichen Kalorienbedarf berechnen →', ctaDeficit: 'Kaloriendefizit berechnen →', ctaIdealWeight: 'Idealgewicht berechnen →',
    relatedTdee: 'TDEE-Rechner', relatedTdeeDesc: 'Ihr gesamter täglicher Energiebedarf',
    relatedBodyFat: 'Körperfett-Rechner', relatedBodyFatDesc: 'Schätzen Sie Ihren Körperfettanteil',
    relatedIdealWeight: 'Idealgewicht-Rechner', relatedIdealWeightDesc: 'Ihr optimaler Gewichtsbereich',
    relatedCalorieDeficit: 'Kaloriendefizit', relatedCalorieDeficitDesc: 'Planen Sie Ihre Gewichtsabnahme sicher',
    optional: 'optional',
    footerTagline: 'Kostenlose professionelle Rechner für Gesundheit, Finanzen, Mathematik und Einheitenumrechnung. Formeln nach WHO, CFPB, NIST und ISO.',
    viewAll: 'Alle anzeigen →', footerCopyright: (year: number) => `© ${year} SolviqLab. Alle Rechte vorbehalten. Kein medizinischer oder finanzieller Rat.`,
    footerSources: 'Formeln von WHO · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Alle ${cat}-Rechner`, categoryPageCount: (n: number) => `${n} kostenlose Rechner`,
    categoryPageCalc: 'Berechnen →', categoryPageBack: '← Alle Rechner anzeigen',
    contentWhatIs: (kw: string) => `Was ist der ${kw}?`,
    contentFormula: (kw: string) => `Formel des ${kw}`,
    contentExample: (kw: string) => `Beispiel des ${kw}`,
    contentHowTo: (kw: string) => `So verwenden Sie den ${kw}`,
    contentWhyMatters: (kw: string) => `Warum der ${kw} Wichtig Ist`,
    contentLimitations: 'Einschränkungen & Genauigkeit',
    contentTips: 'Praktische Tipps',
    apiAccess: 'API-Zugang', apiComingSoon: 'Demnächst',
    apiDeveloper: 'REST-API für Entwickler. Integrieren Sie dieses Tool in Ihre App.',
    trustedSources: 'Quellen & Methodik',
    faqTitle: 'Häufige Fragen',
  },
  pl: {
    heroTitle1: 'Oblicz Wszystko.', heroTitle2: ' Natychmiast.',
    heroSubtitle: (n: number) => `${n}+ darmowych profesjonalnych kalkulatorów do zdrowia, finansów, matematyki i przeliczania jednostek. Bez rejestracji. Bez reklam. Tylko odpowiedzi.`,
    heroSources: 'Wzory z:', heroCta1: 'Wypróbuj Kalkulator BMI →', heroCta2: 'Kalkulator Kredytu Hipotecznego',
    featuredTitle: 'Najpopularniejsze Kalkulatory', featuredSubtitle: 'Narzędzia, których miliony ludzi używają każdego dnia.',
    openCalc: 'Otwórz Kalkulator →', sourcesLabel: 'Wzory z:',
    searchPlaceholder: 'Szukaj kalkulatorów...', tabAll: 'Wszystkie', tabHealth: '❤️ Zdrowie', tabFinance: '💰 Finanse', tabMath: '🧮 Matematyka', tabConversion: '🔄 Przeliczniki',
    countSingle: (n: number) => `${n} kalkulator`, countPlural: (n: number) => `${n} kalkulatorów`, noResults: (q: string) => `Nie znaleziono kalkulatorów dla „${q}"`,
    breadcrumbHome: 'Strona główna', medicallyReviewed: 'Zweryfikowane medycznie', expertReviewed: 'Zweryfikowane przez ekspertów', journeyTitle: 'Kontynuuj Swoją Podróż',
    exploreAll: (cat: string) => `Zobacz wszystkie kalkulatory ${cat} →`,
    categoryLabels: { health: 'Zdrowie', finance: 'Finanse', math: 'Matematyka', conversion: 'Przeliczniki' } as Record<string, string>,
    copyResult: '📋 Kopiuj wynik', copied: '✅ Skopiowano!', shareLink: '🔗 Udostępnij link', print: '🖨️ Drukuj',
    whatThisMeans: 'Co to oznacza', whatToDoNext: 'Co zrobić dalej',
    healthyWeightFor: 'Zdrowa waga dla Twojego wzrostu:', estBodyFat: 'Szacowana tkanka tłuszczowa:',
    bmiContext: (bmi: string, cat: string) => `Twoje BMI wynosi ${bmi} i mieści się w zakresie ${cat}.`,
    bmiRangeNormal: 'Zdrowy zakres to 18,5–24,9.', bmiRangeOverweight: 'Zdrowy zakres to 18,5–24,9. Nadwaga: 25–29,9.',
    bmiRangeUnder: 'Zdrowy zakres zaczyna się od 18,5.',
    bmiPrimeLabel: 'BMI Prime', bmiPrimeSub: '(1,0 = górna granica normy)', ponderalLabel: 'Wskaźnik Ponderalny',
    categoryLabel: 'Kategoria', whoStandard: 'Standard WHO', nextSteps: 'Następne Kroki', methodologySources: 'Metodologia i Źródła',
    ctaCalories: 'Oblicz dzienne zapotrzebowanie kaloryczne →', ctaDeficit: 'Oblicz deficyt kaloryczny →', ctaIdealWeight: 'Oblicz idealną wagę →',
    relatedTdee: 'Kalkulator TDEE', relatedTdeeDesc: 'Twoje całkowite dzienne zapotrzebowanie energetyczne',
    relatedBodyFat: 'Kalkulator Tkanki Tłuszczowej', relatedBodyFatDesc: 'Oszacuj swój procent tkanki tłuszczowej',
    relatedIdealWeight: 'Kalkulator Idealnej Wagi', relatedIdealWeightDesc: 'Twój optymalny zakres wagi',
    relatedCalorieDeficit: 'Deficyt Kaloryczny', relatedCalorieDeficitDesc: 'Zaplanuj bezpieczne odchudzanie',
    optional: 'opcjonalne',
    footerTagline: 'Darmowe profesjonalne kalkulatory do zdrowia, finansów, matematyki i przeliczania jednostek. Wzory wg WHO, CFPB, NIST i ISO.',
    viewAll: 'Zobacz wszystkie →', footerCopyright: (year: number) => `© ${year} SolviqLab. Wszelkie prawa zastrzeżone. Nie jest to porada medyczna ani finansowa.`,
    footerSources: 'Wzory z WHO · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Wszystkie Kalkulatory: ${cat}`, categoryPageCount: (n: number) => `${n} darmowych kalkulatorów`,
    categoryPageCalc: 'Oblicz →', categoryPageBack: '← Zobacz wszystkie kalkulatory',
    contentWhatIs: (kw: string) => `Czym jest ${kw}?`,
    contentFormula: (kw: string) => `Wzór ${kw}`,
    contentExample: (kw: string) => `Przykład ${kw}`,
    contentHowTo: (kw: string) => `Jak używać ${kw}`,
    contentWhyMatters: (kw: string) => `Dlaczego ${kw} Jest Ważny`,
    contentLimitations: 'Ograniczenia i Dokładność',
    contentTips: 'Praktyczne Wskazówki',
    apiAccess: 'Dostęp API', apiComingSoon: 'Wkrótce',
    apiDeveloper: 'REST API dla deweloperów. Zintegruj to narzędzie ze swoją aplikacją.',
    trustedSources: 'Źródła i Metodologia',
    faqTitle: 'Często zadawane pytania',
  },
}

export type UIStrings = typeof strings['en']
export type Lang = keyof typeof strings

export function t(lang: string): UIStrings {
  return strings[lang as Lang] ?? strings.en
}

export function tr(translations: Record<string, unknown>, path: string, fallback = ''): string {
  const parts = path.split('.')
  let cur: unknown = translations
  for (const p of parts) {
    if (cur == null || typeof cur !== 'object') return fallback
    cur = (cur as Record<string, unknown>)[p]
  }
  return typeof cur === 'string' ? cur : fallback
}
