const strings = {
  en: {
    navQuizzes: 'Quizzes', navMyAccount: 'My Account',
    quizNames: { 'sleep-quiz': 'Sleep Quality Quiz', 'stress-quiz': 'Stress Level Quiz', 'burnout-quiz': 'Burnout Risk Quiz', 'energy-quiz': 'Daily Energy Levels Quiz', 'bmi-quiz': 'BMI Assessment', 'depression-quiz': 'Depression Screening', 'anxiety-quiz': 'Anxiety Assessment', 'hydration-quiz': 'Hydration Check', 'lifestyle-quiz': 'Lifestyle Score', 'weight-readiness-quiz': 'Weight Loss Readiness' } as Record<string, string>,
    quizSectionTitle: 'Know Your Health Score',
    quizSectionSubtitle: 'Free science-backed quizzes · Under 3 min · No account needed',
    quizCta: 'See All Quizzes →',
    footerCompany: 'Company', footerAbout: 'About', footerContact: 'Contact', footerPrivacy: 'Privacy Policy', footerTerms: 'Terms of Service', footerCoachMia: 'Coach Mia', footerCoachAlex: 'Coach Alex',
    privacyTitle: 'Privacy Policy', privacyBreadcrumb: 'Privacy Policy',
    termsTitle: 'Terms of Service', termsBreadcrumb: 'Terms of Service',
    contactTitle: 'Get in Touch', contactBreadcrumb: 'Contact',
    contactSubtitle: "We're a small team and we read every message. We typically respond within 24–48 hours.",
    contactResponseNote: '⏱ We respond to all emails within 24–48 hours on business days.',
    heroTitle1: 'Calculators. Quizzes.', heroTitle2: ' AI Coaching.',
    heroSubtitle: (n: number) => `${n}+ free tools for health & finance — calculators, science-backed quizzes, and personal AI coaching. No registration. No ads.`,
    heroPillCalc: 'Calculators', heroPillQuiz: 'Science Quizzes', heroPillCoach: 'AI Coaching',
    coachOnlineNow: 'Online now', coachFreeSession: 'Free session', coachMiaRole: 'Health Coach', coachAlexRole: 'Finance Coach', coachMiaSpec: 'Sleep · Weight · Stress · Energy', coachAlexSpec: 'Budget · Savings · Taxes', coachTalkTo: (name: string) => `Talk to ${name} →`,
    heroSources: 'Formulas sourced from:', heroCta1: 'Try BMI Calculator →', heroCta2: 'Mortgage Calculator',
    featuredTitle: 'Most Popular Calculators', featuredSubtitle: 'The tools millions of people use every day.',
    openCalc: 'Open Calculator →', sourcesLabel: 'Formulas sourced from:',
    searchPlaceholder: 'Search tools...', tabAll: 'All', tabHealth: 'Health', tabFinance: 'Finance', tabMath: 'Math', tabConversion: 'Converters',
    countSingle: (n: number) => `${n} calculator`, countPlural: (n: number) => `${n} calculators`, noResults: (q: string) => `No calculators found for "${q}"`,
    breadcrumbHome: 'Home', medicallyReviewed: 'Medically reviewed', expertReviewed: 'Expert reviewed', journeyTitle: 'Continue Your Journey',
    exploreAll: (cat: string) => `Explore all ${cat} calculators →`,
    categoryLabels: { health: 'Health', finance: 'Finance', math: 'Math', conversion: 'Converters' } as Record<string, string>,
    copyResult: '📋 Copy result', copied: '✅ Copied!', shareLink: '🔗 Share link', print: '🖨️ Print',
    calcCopy: '⎘ Copy', calcCopied: '✓ Copied', calcShare: '↗ Share',
    whatThisMeans: 'What this means', whatToDoNext: 'What to do next',
    healthyWeightFor: 'Healthy weight for your height:', estBodyFat: 'Est. body fat:',
    bmiContext: (bmi: string, cat: string) => `Your BMI of ${bmi} falls in the ${cat} range.`,
    bmiRangeNormal: 'The healthy range is 18.5–24.9.', bmiRangeOverweight: 'The healthy range is 18.5–24.9. Overweight is 25–29.9.',
    bmiRangeUnder: 'The healthy range starts at 18.5.',
    bmiPrimeLabel: 'BMI Prime', bmiPrimeSub: '(1.0 = upper normal)', ponderalLabel: 'Ponderal Index',
    categoryLabel: 'Category', whoStandard: 'WHO standard', nextSteps: 'Next Steps', methodologySources: 'Methodology & Sources',
    ctaCalories: 'Calculate your daily calories →', ctaDeficit: 'Calculate your calorie deficit →', ctaIdealWeight: 'Calculate your ideal weight →',
    relatedTdee: 'TDEE Calculator', relatedTdeeDesc: 'Your total daily calorie needs',
    relatedBodyFat: 'Body Fat Calculator', relatedBodyFatDesc: 'Estimate your body fat %',
    relatedIdealWeight: 'Ideal Weight Calculator', relatedIdealWeightDesc: 'Your optimal weight range',
    relatedCalorieDeficit: 'Calorie Deficit', relatedCalorieDeficitDesc: 'Plan your weight loss safely',
    optional: 'optional',
    footerTagline: 'Free professional calculators for health, finance, math, and unit conversions. Formulas backed by WHO, CFPB, NIST, and ISO.',
    viewAll: 'View all →', footerCopyright: (year: number) => `© ${year} SolviqLab. All rights reserved. Not medical or financial advice.`,
    footerSources: 'Formulas sourced from WHO · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `All ${cat} Calculators`, categoryPageCount: (n: number) => `${n} free calculators`,
    categoryPageCalc: 'Calculate →', categoryPageBack: '← Explore all calculators',
    contentWhatIs: (kw: string) => `What is the ${kw}?`,
    contentFormula: (kw: string) => `${kw} Formula`,
    contentExample: (kw: string) => `${kw} Example`,
    contentHowTo: (kw: string) => `How to Use the ${kw}`,
    contentWhyMatters: (kw: string) => `Why ${kw} Matters`,
    contentLimitations: 'Limitations & Accuracy',
    contentTips: 'Practical Tips',
    apiAccess: 'API Access', apiComingSoon: 'Coming Soon',
    apiDeveloper: 'REST API for developers. Integrate this tool into your app.',
    trustedSources: 'Trusted Sources & Methodology',
    faqTitle: 'Frequently Asked Questions',
    miaGreeting: "Hi! I'm Mia — your personal health coach.",
    miaAskGoal: 'What would you like help with today? Tell me your problem or goal.',
    miaGetStarted: 'Get Started →', miaFree: 'Free · No account needed', miaMeetBtn: 'Meet Mia →',
    miaReviewedResults: 'Mia has reviewed your results.',
    miaReviewedSub: (score: number) => `She's already looking at what your ${score}-point score means for you specifically.`,
    quizFreeLabel: 'Free', quizQuestionsLabel: (n: number) => `${n} questions`,
    quizPageTitle: 'Free Health Quizzes', quizPageSubtitle: 'Honest, science-backed quizzes that give you a real snapshot of your health — in under 3 minutes. No sign-up required.', quizPageFooter: 'All quizzes are free. Results stay on your device. No account needed.', quizClusterLabels: { weight: 'Weight', sleep: 'Sleep', mental: 'Mental Health', lifestyle: 'Lifestyle', energy: 'Energy' } as Record<string, string>,
    miaTopicSleep: 'Sleep quality', miaTopicWeight: 'Weight loss', miaTopicStress: 'Stress', miaTopicEnergy: 'Energy',
    miaGenerating: (name: string) => `Mia is preparing your personal video${name ? `, ${name}` : ''}…`,
    miaGeneratingSub: 'This usually takes 1–2 minutes. Stay on this page.',
    miaClusterSleep: 'sleep quality', miaClusterWeight: 'weight loss',
    miaPlanInMotion: (name: string) => `Your plan is in motion${name ? `, ${name}` : ''}.`,
    miaPlanFooter: "Mia already has your data. She doesn't forget.",
    miaPlanItem1: (cluster: string) => `Your 7-day ${cluster} protocol — ready tomorrow`,
    miaPlanItem2: 'Personalized targets based on your data',
    miaPlanItem3: 'Daily check-in with Mia',
    miaRewatch: "Rewatch Mia's message",
  },
  uk: {
    navQuizzes: 'Тести', navMyAccount: 'Мій кабінет',
    quizNames: { 'sleep-quiz': 'Тест якості сну', 'stress-quiz': 'Тест рівня стресу', 'burnout-quiz': 'Тест на вигорання', 'energy-quiz': 'Тест рівня енергії', 'bmi-quiz': 'Оцінка ІМТ', 'depression-quiz': 'Скринінг депресії', 'anxiety-quiz': 'Оцінка тривожності', 'hydration-quiz': 'Рівень гідратації', 'lifestyle-quiz': 'Оцінка способу життя', 'weight-readiness-quiz': 'Готовність до схуднення' } as Record<string, string>,
    quizSectionTitle: "Дізнайся свій рівень здоров'я",
    quizSectionSubtitle: 'Безкоштовні наукові тести · До 3 хвилин · Без реєстрації',
    quizCta: 'Всі тести →',
    footerCompany: 'Компанія', footerAbout: 'Про нас', footerContact: 'Контакти', footerPrivacy: 'Конфіденційність', footerTerms: 'Умови використання', footerCoachMia: 'Коуч Mia', footerCoachAlex: 'Коуч Alex',
    privacyTitle: 'Політика конфіденційності', privacyBreadcrumb: 'Конфіденційність',
    termsTitle: 'Умови використання', termsBreadcrumb: 'Умови',
    contactTitle: "Зв'яжіться з нами", contactBreadcrumb: 'Контакти',
    contactSubtitle: 'Ми невелика команда і читаємо кожне повідомлення. Відповідаємо протягом 24–48 годин.',
    contactResponseNote: '⏱ Ми відповідаємо на всі листи протягом 24–48 годин у робочі дні.',
    heroTitle1: 'Калькулятори. Тести.', heroTitle2: ' ШІ-коучинг.',
    heroSubtitle: (n: number) => `${n}+ безкоштовних інструментів для здоров'я та фінансів — калькулятори, наукові тести та персональний ШІ-коучинг. Без реєстрації. Без реклами.`,
    heroPillCalc: 'Калькулятори', heroPillQuiz: 'Наукові тести', heroPillCoach: 'ШІ-коучинг',
    coachOnlineNow: 'Онлайн зараз', coachFreeSession: 'Безкоштовно', coachMiaRole: 'Тренер зі здоров\'я', coachAlexRole: 'Фінансовий тренер', coachMiaSpec: 'Сон · Вага · Стрес · Енергія', coachAlexSpec: 'Бюджет · Заощадження · Податки', coachTalkTo: (name: string) => `Поговорити з ${name} →`,
    heroSources: 'Формули з джерел:', heroCta1: 'Спробувати BMI →', heroCta2: 'Іпотечний калькулятор',
    featuredTitle: 'Найпопулярніші калькулятори', featuredSubtitle: 'Інструменти, якими користуються мільйони щодня.',
    openCalc: 'Відкрити →', sourcesLabel: 'Формули з джерел:',
    searchPlaceholder: 'Пошук...', tabAll: 'Всі', tabHealth: "Здоров'я", tabFinance: 'Фінанси', tabMath: 'Математика', tabConversion: 'Конвертери',
    countSingle: (n: number) => `${n} калькулятор`, countPlural: (n: number) => `${n} калькуляторів`, noResults: (q: string) => `Калькуляторів для "${q}" не знайдено`,
    breadcrumbHome: 'Головна', medicallyReviewed: 'Медично перевірено', expertReviewed: 'Перевірено експертом', journeyTitle: 'Продовжити подорож',
    exploreAll: (cat: string) => `Всі калькулятори: ${cat} →`,
    categoryLabels: { health: "Здоров'я", finance: 'Фінанси', math: 'Математика', conversion: 'Конвертери' } as Record<string, string>,
    copyResult: '📋 Копіювати', copied: '✅ Скопійовано!', shareLink: '🔗 Поділитись', print: '🖨️ Друк',
    calcCopy: '⎘ Копіювати', calcCopied: '✓ Скопійовано', calcShare: '↗ Поділитись',
    whatThisMeans: 'Що це означає', whatToDoNext: 'Що робити далі',
    healthyWeightFor: 'Здорова вага для вашого зросту:', estBodyFat: 'Приблизний % жиру:',
    bmiContext: (bmi: string, cat: string) => `Ваш ІМТ ${bmi} відповідає категорії "${cat}".`,
    bmiRangeNormal: 'Норма — 18.5–24.9.', bmiRangeOverweight: 'Норма — 18.5–24.9. Надмірна вага — 25–29.9.',
    bmiRangeUnder: 'Норма починається від 18.5.',
    bmiPrimeLabel: 'ІМТ-прайм', bmiPrimeSub: '(1.0 = верхня межа норми)', ponderalLabel: 'Понделяровий індекс',
    categoryLabel: 'Категорія', whoStandard: 'Стандарт ВООЗ', nextSteps: 'Наступні кроки', methodologySources: 'Методологія та джерела',
    ctaCalories: 'Розрахувати добову норму калорій →', ctaDeficit: 'Розрахувати дефіцит калорій →', ctaIdealWeight: 'Розрахувати ідеальну вагу →',
    relatedTdee: 'Калькулятор TDEE', relatedTdeeDesc: 'Ваша добова норма калорій',
    relatedBodyFat: 'Калькулятор % жиру', relatedBodyFatDesc: 'Оцініть відсоток жиру в тілі',
    relatedIdealWeight: 'Ідеальна вага', relatedIdealWeightDesc: 'Ваш оптимальний діапазон ваги',
    relatedCalorieDeficit: 'Дефіцит калорій', relatedCalorieDeficitDesc: 'Безпечне зниження ваги',
    optional: "необов'язково",
    footerTagline: "Безкоштовні професійні калькулятори для здоров'я, фінансів, математики та одиниць виміру. Формули ВООЗ, CFPB, NIST та ISO.",
    viewAll: 'Всі →', footerCopyright: (year: number) => `© ${year} SolviqLab. Всі права захищені. Не є медичною або фінансовою порадою.`,
    footerSources: 'Формули: ВООЗ · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Всі калькулятори: ${cat}`, categoryPageCount: (n: number) => `${n} безкоштовних калькуляторів`,
    categoryPageCalc: 'Розрахувати →', categoryPageBack: '← Всі калькулятори',
    contentWhatIs: (kw: string) => `Що таке ${kw}?`,
    contentFormula: (kw: string) => `Формула ${kw}`,
    contentExample: (kw: string) => `Приклад ${kw}`,
    contentHowTo: (kw: string) => `Як користуватись ${kw}`,
    contentWhyMatters: (kw: string) => `Чому ${kw} важливий`,
    contentLimitations: 'Обмеження та точність',
    contentTips: 'Практичні поради',
    apiAccess: 'API доступ', apiComingSoon: 'Незабаром',
    apiDeveloper: 'REST API для розробників. Інтегруйте цей інструмент у свій застосунок.',
    trustedSources: 'Джерела та методологія',
    faqTitle: 'Часті запитання',
    miaGreeting: "Привіт! Я Міа — твій тренер зі здоров'я.",
    miaAskGoal: 'Чим я можу тобі допомогти сьогодні? Розкажи про свою проблему або мету.',
    miaGetStarted: 'Розпочати →', miaFree: 'Безкоштовно · Без реєстрації', miaMeetBtn: 'Познайомитись з Міа →',
    miaReviewedResults: 'Міа переглянула твої результати.',
    miaReviewedSub: (score: number) => `Вона вже аналізує що означає твій результат ${score} балів саме для тебе.`,
    quizFreeLabel: 'Безкоштовно', quizQuestionsLabel: (n: number) => `${n} питань`,
    quizPageTitle: "Безкоштовні тести здоров'я", quizPageSubtitle: "Чесні науково обґрунтовані тести — реальний знімок вашого здоров'я за 3 хвилини. Без реєстрації.", quizPageFooter: 'Всі тести безкоштовні. Результати на вашому пристрої. Акаунт не потрібен.', quizClusterLabels: { weight: 'Вага', sleep: 'Сон', mental: "Психічне здоров'я", lifestyle: 'Спосіб життя', energy: 'Енергія' } as Record<string, string>,
    miaTopicSleep: 'Якість сну', miaTopicWeight: 'Схуднення', miaTopicStress: 'Стрес', miaTopicEnergy: 'Енергія',
    miaGenerating: (name: string) => `Міа готує твоє особисте відео${name ? `, ${name}` : ''}…`,
    miaGeneratingSub: 'Зазвичай це займає 1–2 хвилини. Залишайтесь на сторінці.',
    miaClusterSleep: 'якість сну', miaClusterWeight: 'схуднення',
    miaPlanInMotion: (name: string) => `Твій план вже в роботі${name ? `, ${name}` : ''}.`,
    miaPlanFooter: 'Міа вже має твої дані. Вона не забуває.',
    miaPlanItem1: (cluster: string) => `7-денний протокол для ${cluster} — готовий завтра`,
    miaPlanItem2: 'Персональні цілі на основі твоїх даних',
    miaPlanItem3: 'Щоденний чекін з Міа',
    miaRewatch: 'Переглянути відео ще раз',
  },
  es: {
    navQuizzes: 'Tests', navMyAccount: 'Mi Cuenta',
    quizNames: { 'sleep-quiz': 'Test de Calidad del Sueño', 'stress-quiz': 'Test de Nivel de Estrés', 'burnout-quiz': 'Test de Riesgo de Burnout', 'energy-quiz': 'Test de Niveles de Energía', 'bmi-quiz': 'Evaluación del IMC', 'depression-quiz': 'Detección de Depresión', 'anxiety-quiz': 'Evaluación de Ansiedad', 'hydration-quiz': 'Control de Hidratación', 'lifestyle-quiz': 'Puntuación de Estilo de Vida', 'weight-readiness-quiz': 'Preparación para Perder Peso' } as Record<string, string>,
    quizSectionTitle: 'Descubre Tu Puntuación de Salud',
    quizSectionSubtitle: 'Tests científicos gratuitos · Menos de 3 min · Sin cuenta',
    quizCta: 'Ver todos los tests →',
    footerCompany: 'Empresa', footerAbout: 'Acerca de', footerContact: 'Contacto', footerPrivacy: 'Privacidad', footerTerms: 'Términos de uso', footerCoachMia: 'Coach Mia', footerCoachAlex: 'Coach Alex',
    privacyTitle: 'Política de privacidad', privacyBreadcrumb: 'Privacidad',
    termsTitle: 'Términos de servicio', termsBreadcrumb: 'Términos',
    contactTitle: 'Contáctanos', contactBreadcrumb: 'Contacto',
    contactSubtitle: 'Somos un equipo pequeño y leemos cada mensaje. Respondemos en 24–48 horas.',
    contactResponseNote: '⏱ Respondemos a todos los correos en 24–48 horas en días hábiles.',
    heroTitle1: 'Calculadoras. Tests.', heroTitle2: ' Coaching IA.',
    heroSubtitle: (n: number) => `${n}+ herramientas gratuitas para salud y finanzas — calculadoras, tests científicos y coaching IA personal. Sin registro. Sin anuncios.`,
    heroPillCalc: 'Calculadoras', heroPillQuiz: 'Tests Científicos', heroPillCoach: 'Coaching IA',
    coachOnlineNow: 'En línea ahora', coachFreeSession: 'Gratis', coachMiaRole: 'Coach de Salud', coachAlexRole: 'Coach Financiero', coachMiaSpec: 'Sueño · Peso · Estrés · Energía', coachAlexSpec: 'Presupuesto · Ahorro · Impuestos', coachTalkTo: (name: string) => `Hablar con ${name} →`,
    heroSources: 'Fórmulas obtenidas de:', heroCta1: 'Probar Calculadora de IMC →', heroCta2: 'Calculadora de Hipoteca',
    featuredTitle: 'Calculadoras Más Populares', featuredSubtitle: 'Las herramientas que millones de personas usan cada día.',
    openCalc: 'Abrir Calculadora →', sourcesLabel: 'Fórmulas obtenidas de:',
    searchPlaceholder: 'Buscar...', tabAll: 'Todas', tabHealth: 'Salud', tabFinance: 'Finanzas', tabMath: 'Matemáticas', tabConversion: 'Conversores',
    countSingle: (n: number) => `${n} calculadora`, countPlural: (n: number) => `${n} calculadoras`, noResults: (q: string) => `No se encontraron calculadoras para "${q}"`,
    breadcrumbHome: 'Inicio', medicallyReviewed: 'Revisado médicamente', expertReviewed: 'Revisado por expertos', journeyTitle: 'Continúa Tu Viaje',
    exploreAll: (cat: string) => `Ver todas las calculadoras de ${cat} →`,
    categoryLabels: { health: 'Salud', finance: 'Finanzas', math: 'Matemáticas', conversion: 'Conversores' } as Record<string, string>,
    copyResult: '📋 Copiar resultado', copied: '✅ ¡Copiado!', shareLink: '🔗 Compartir enlace', print: '🖨️ Imprimir',
    calcCopy: '⎘ Copiar', calcCopied: '✓ Copiado', calcShare: '↗ Compartir',
    whatThisMeans: 'Qué significa esto', whatToDoNext: 'Qué hacer a continuación',
    healthyWeightFor: 'Peso saludable para tu altura:', estBodyFat: 'Grasa corporal estimada:',
    bmiContext: (bmi: string, cat: string) => `Tu IMC de ${bmi} está en el rango de ${cat}.`,
    bmiRangeNormal: 'El rango saludable es 18.5–24.9.', bmiRangeOverweight: 'El rango saludable es 18.5–24.9. Sobrepeso es 25–29.9.',
    bmiRangeUnder: 'El rango saludable comienza en 18.5.',
    bmiPrimeLabel: 'IMC Prime', bmiPrimeSub: '(1.0 = límite superior normal)', ponderalLabel: 'Índice Ponderal',
    categoryLabel: 'Categoría', whoStandard: 'Estándar OMS', nextSteps: 'Próximos Pasos', methodologySources: 'Metodología y Fuentes',
    ctaCalories: 'Calcular tus calorías diarias →', ctaDeficit: 'Calcular tu déficit calórico →', ctaIdealWeight: 'Calcular tu peso ideal →',
    relatedTdee: 'Calculadora TDEE', relatedTdeeDesc: 'Tus necesidades calóricas diarias totales',
    relatedBodyFat: 'Calculadora de Grasa Corporal', relatedBodyFatDesc: 'Estima tu porcentaje de grasa',
    relatedIdealWeight: 'Calculadora de Peso Ideal', relatedIdealWeightDesc: 'Tu rango de peso óptimo',
    relatedCalorieDeficit: 'Déficit Calórico', relatedCalorieDeficitDesc: 'Planifica tu pérdida de peso de forma segura',
    optional: 'opcional',
    footerTagline: 'Calculadoras profesionales gratuitas para salud, finanzas, matemáticas y conversiones. Fórmulas respaldadas por OMS, CFPB, NIST e ISO.',
    viewAll: 'Ver todas →', footerCopyright: (year: number) => `© ${year} SolviqLab. Todos los derechos reservados. No es consejo médico ni financiero.`,
    footerSources: 'Fórmulas de OMS · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Todas las Calculadoras de ${cat}`, categoryPageCount: (n: number) => `${n} calculadoras gratuitas`,
    categoryPageCalc: 'Calcular →', categoryPageBack: '← Ver todas las calculadoras',
    contentWhatIs: (kw: string) => `¿Qué es el ${kw}?`,
    contentFormula: (kw: string) => `Fórmula del ${kw}`,
    contentExample: (kw: string) => `Ejemplo del ${kw}`,
    contentHowTo: (kw: string) => `Cómo usar el ${kw}`,
    contentWhyMatters: (kw: string) => `Por Qué Importa el ${kw}`,
    contentLimitations: 'Limitaciones y Precisión',
    contentTips: 'Consejos Prácticos',
    apiAccess: 'Acceso API', apiComingSoon: 'Próximamente',
    apiDeveloper: 'API REST para desarrolladores. Integra esta herramienta en tu app.',
    trustedSources: 'Fuentes y Metodología',
    faqTitle: 'Preguntas Frecuentes',
    miaGreeting: '¡Hola! Soy Mia — tu coach de salud personal.',
    miaAskGoal: '¿Con qué te gustaría que te ayude hoy? Cuéntame tu problema o meta.',
    miaGetStarted: 'Comenzar →', miaFree: 'Gratis · Sin registro', miaMeetBtn: 'Conocer a Mia →',
    miaReviewedResults: 'Mia ha revisado tus resultados.',
    miaReviewedSub: (score: number) => `Ya está analizando lo que significa tu puntuación de ${score} puntos específicamente para ti.`,
    quizFreeLabel: 'Gratis', quizQuestionsLabel: (n: number) => `${n} preguntas`,
    quizPageTitle: 'Tests de Salud Gratuitos', quizPageSubtitle: 'Tests honestos y científicos que te dan una imagen real de tu salud — en menos de 3 minutos. Sin registro.', quizPageFooter: 'Todos los tests son gratuitos. Resultados en tu dispositivo. Sin cuenta.', quizClusterLabels: { weight: 'Peso', sleep: 'Sueño', mental: 'Salud Mental', lifestyle: 'Estilo de Vida', energy: 'Energía' } as Record<string, string>,
    miaTopicSleep: 'Calidad del sueño', miaTopicWeight: 'Pérdida de peso', miaTopicStress: 'Estrés', miaTopicEnergy: 'Energía',
    miaGenerating: (name: string) => `Mia está preparando tu video personal${name ? `, ${name}` : ''}…`,
    miaGeneratingSub: 'Esto suele tardar 1–2 minutos. Quédate en la página.',
    miaClusterSleep: 'calidad del sueño', miaClusterWeight: 'pérdida de peso',
    miaPlanInMotion: (name: string) => `Tu plan está en marcha${name ? `, ${name}` : ''}.`,
    miaPlanFooter: 'Mia ya tiene tus datos. Ella no olvida.',
    miaPlanItem1: (cluster: string) => `Tu protocolo de 7 días para ${cluster} — listo mañana`,
    miaPlanItem2: 'Objetivos personalizados basados en tus datos',
    miaPlanItem3: 'Check-in diario con Mia',
    miaRewatch: 'Volver a ver el mensaje de Mia',
  },
  pt: {
    navQuizzes: 'Testes', navMyAccount: 'Minha Conta',
    quizNames: { 'sleep-quiz': 'Teste de Qualidade do Sono', 'stress-quiz': 'Teste de Nível de Estresse', 'burnout-quiz': 'Teste de Risco de Burnout', 'energy-quiz': 'Teste de Níveis de Energia', 'bmi-quiz': 'Avaliação do IMC', 'depression-quiz': 'Rastreamento de Depressão', 'anxiety-quiz': 'Avaliação de Ansiedade', 'hydration-quiz': 'Verificação de Hidratação', 'lifestyle-quiz': 'Pontuação de Estilo de Vida', 'weight-readiness-quiz': 'Prontidão para Perda de Peso' } as Record<string, string>,
    quizSectionTitle: 'Descubra Sua Pontuação de Saúde',
    quizSectionSubtitle: 'Testes científicos gratuitos · Menos de 3 min · Sem conta',
    quizCta: 'Ver todos os testes →',
    footerCompany: 'Empresa', footerAbout: 'Sobre nós', footerContact: 'Contato', footerPrivacy: 'Privacidade', footerTerms: 'Termos de uso', footerCoachMia: 'Coach Mia', footerCoachAlex: 'Coach Alex',
    privacyTitle: 'Política de privacidade', privacyBreadcrumb: 'Privacidade',
    termsTitle: 'Termos de serviço', termsBreadcrumb: 'Termos',
    contactTitle: 'Entre em contato', contactBreadcrumb: 'Contato',
    contactSubtitle: 'Somos uma equipe pequena e lemos cada mensagem. Respondemos em 24–48 horas.',
    contactResponseNote: '⏱ Respondemos a todos os e-mails em 24–48 horas nos dias úteis.',
    heroTitle1: 'Calculadoras. Testes.', heroTitle2: ' Coaching com IA.',
    heroSubtitle: (n: number) => `${n}+ ferramentas gratuitas para saúde e finanças — calculadoras, testes científicos e coaching com IA pessoal. Sem registro. Sem anúncios.`,
    heroPillCalc: 'Calculadoras', heroPillQuiz: 'Testes Científicos', heroPillCoach: 'Coaching com IA',
    coachOnlineNow: 'Online agora', coachFreeSession: 'Gratuito', coachMiaRole: 'Coach de Saúde', coachAlexRole: 'Coach Financeiro', coachMiaSpec: 'Sono · Peso · Estresse · Energia', coachAlexSpec: 'Orçamento · Poupança · Impostos', coachTalkTo: (name: string) => `Falar com ${name} →`,
    heroSources: 'Fórmulas obtidas de:', heroCta1: 'Experimentar Calculadora de IMC →', heroCta2: 'Calculadora de Hipoteca',
    featuredTitle: 'Calculadoras Mais Populares', featuredSubtitle: 'As ferramentas que milhões de pessoas usam todos os dias.',
    openCalc: 'Abrir Calculadora →', sourcesLabel: 'Fórmulas obtidas de:',
    searchPlaceholder: 'Pesquisar...', tabAll: 'Todas', tabHealth: 'Saúde', tabFinance: 'Finanças', tabMath: 'Matemática', tabConversion: 'Conversores',
    countSingle: (n: number) => `${n} calculadora`, countPlural: (n: number) => `${n} calculadoras`, noResults: (q: string) => `Nenhuma calculadora encontrada para "${q}"`,
    breadcrumbHome: 'Início', medicallyReviewed: 'Revisado medicamente', expertReviewed: 'Revisado por especialistas', journeyTitle: 'Continue Sua Jornada',
    exploreAll: (cat: string) => `Ver todas as calculadoras de ${cat} →`,
    categoryLabels: { health: 'Saúde', finance: 'Finanças', math: 'Matemática', conversion: 'Conversores' } as Record<string, string>,
    copyResult: '📋 Copiar resultado', copied: '✅ Copiado!', shareLink: '🔗 Compartilhar link', print: '🖨️ Imprimir',
    calcCopy: '⎘ Copiar', calcCopied: '✓ Copiado', calcShare: '↗ Compartilhar',
    whatThisMeans: 'O que isso significa', whatToDoNext: 'O que fazer a seguir',
    healthyWeightFor: 'Peso saudável para sua altura:', estBodyFat: 'Gordura corporal estimada:',
    bmiContext: (bmi: string, cat: string) => `Seu IMC de ${bmi} está na faixa de ${cat}.`,
    bmiRangeNormal: 'A faixa saudável é 18.5–24.9.', bmiRangeOverweight: 'A faixa saudável é 18.5–24.9. Sobrepeso é 25–29.9.',
    bmiRangeUnder: 'A faixa saudável começa em 18.5.',
    bmiPrimeLabel: 'IMC Prime', bmiPrimeSub: '(1.0 = limite superior normal)', ponderalLabel: 'Índice Ponderal',
    categoryLabel: 'Categoria', whoStandard: 'Padrão OMS', nextSteps: 'Próximos Passos', methodologySources: 'Metodologia e Fontes',
    ctaCalories: 'Calcular suas calorias diárias →', ctaDeficit: 'Calcular seu déficit calórico →', ctaIdealWeight: 'Calcular seu peso ideal →',
    relatedTdee: 'Calculadora TDEE', relatedTdeeDesc: 'Suas necessidades calóricas diárias totais',
    relatedBodyFat: 'Calculadora de Gordura Corporal', relatedBodyFatDesc: 'Estime seu percentual de gordura',
    relatedIdealWeight: 'Calculadora de Peso Ideal', relatedIdealWeightDesc: 'Sua faixa de peso ideal',
    relatedCalorieDeficit: 'Déficit Calórico', relatedCalorieDeficitDesc: 'Planeje sua perda de peso com segurança',
    optional: 'opcional',
    footerTagline: 'Calculadoras profissionais gratuitas para saúde, finanças, matemática e conversões. Fórmulas respaldadas por OMS, CFPB, NIST e ISO.',
    viewAll: 'Ver todas →', footerCopyright: (year: number) => `© ${year} SolviqLab. Todos os direitos reservados. Não é conselho médico ou financeiro.`,
    footerSources: 'Fórmulas de OMS · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Todas as Calculadoras de ${cat}`, categoryPageCount: (n: number) => `${n} calculadoras gratuitas`,
    categoryPageCalc: 'Calcular →', categoryPageBack: '← Ver todas as calculadoras',
    contentWhatIs: (kw: string) => `O que é o ${kw}?`,
    contentFormula: (kw: string) => `Fórmula do ${kw}`,
    contentExample: (kw: string) => `Exemplo do ${kw}`,
    contentHowTo: (kw: string) => `Como usar o ${kw}`,
    contentWhyMatters: (kw: string) => `Por Que o ${kw} Importa`,
    contentLimitations: 'Limitações e Precisão',
    contentTips: 'Dicas Práticas',
    apiAccess: 'Acesso API', apiComingSoon: 'Em Breve',
    apiDeveloper: 'API REST para desenvolvedores. Integre esta ferramenta no seu app.',
    trustedSources: 'Fontes e Metodologia',
    faqTitle: 'Perguntas Frequentes',
    miaGreeting: 'Olá! Sou Mia — sua coach de saúde pessoal.',
    miaAskGoal: 'Com o que você gostaria de ajuda hoje? Me conte seu problema ou objetivo.',
    miaGetStarted: 'Começar →', miaFree: 'Grátis · Sem cadastro', miaMeetBtn: 'Conhecer a Mia →',
    miaReviewedResults: 'Mia analisou seus resultados.',
    miaReviewedSub: (score: number) => `Ela já está analisando o que significa sua pontuação de ${score} pontos especificamente para você.`,
    quizFreeLabel: 'Grátis', quizQuestionsLabel: (n: number) => `${n} perguntas`,
    quizPageTitle: 'Testes de Saúde Gratuitos', quizPageSubtitle: 'Testes honestos e científicos que dão uma visão real da sua saúde — em menos de 3 minutos. Sem cadastro.', quizPageFooter: 'Todos os testes são gratuitos. Resultados no dispositivo. Sem conta.', quizClusterLabels: { weight: 'Peso', sleep: 'Sono', mental: 'Saúde Mental', lifestyle: 'Estilo de Vida', energy: 'Energia' } as Record<string, string>,
    miaTopicSleep: 'Qualidade do sono', miaTopicWeight: 'Perda de peso', miaTopicStress: 'Estresse', miaTopicEnergy: 'Energia',
    miaGenerating: (name: string) => `Mia está preparando seu vídeo pessoal${name ? `, ${name}` : ''}…`,
    miaGeneratingSub: 'Isso geralmente leva 1–2 minutos. Fique na página.',
    miaClusterSleep: 'qualidade do sono', miaClusterWeight: 'perda de peso',
    miaPlanInMotion: (name: string) => `Seu plano está em andamento${name ? `, ${name}` : ''}.`,
    miaPlanFooter: 'Mia já tem seus dados. Ela não esquece.',
    miaPlanItem1: (cluster: string) => `Seu protocolo de 7 dias para ${cluster} — pronto amanhã`,
    miaPlanItem2: 'Metas personalizadas com base nos seus dados',
    miaPlanItem3: 'Check-in diário com Mia',
    miaRewatch: 'Assistir novamente à mensagem da Mia',
  },
  fr: {
    navQuizzes: 'Tests', navMyAccount: 'Mon Compte',
    quizNames: { 'sleep-quiz': 'Test de Qualité du Sommeil', 'stress-quiz': 'Test de Niveau de Stress', 'burnout-quiz': 'Test de Risque de Burnout', 'energy-quiz': "Test de Niveaux d'Énergie", 'bmi-quiz': "Évaluation de l'IMC", 'depression-quiz': 'Dépistage de la Dépression', 'anxiety-quiz': "Évaluation de l'Anxiété", 'hydration-quiz': "Contrôle de l'Hydratation", 'lifestyle-quiz': 'Score de Style de Vie', 'weight-readiness-quiz': 'Préparation à la Perte de Poids' } as Record<string, string>,
    quizSectionTitle: 'Découvrez Votre Score Santé',
    quizSectionSubtitle: 'Tests scientifiques gratuits · Moins de 3 min · Sans compte',
    quizCta: 'Voir tous les tests →',
    footerCompany: 'Société', footerAbout: 'À propos', footerContact: 'Contact', footerPrivacy: 'Confidentialité', footerTerms: "Conditions d'utilisation", footerCoachMia: 'Coach Mia', footerCoachAlex: 'Coach Alex',
    privacyTitle: 'Politique de confidentialité', privacyBreadcrumb: 'Confidentialité',
    termsTitle: "Conditions d'utilisation", termsBreadcrumb: 'Conditions',
    contactTitle: 'Contactez-nous', contactBreadcrumb: 'Contact',
    contactSubtitle: 'Nous sommes une petite équipe et lisons chaque message. Nous répondons en 24–48 heures.',
    contactResponseNote: '⏱ Nous répondons à tous les e-mails en 24–48 heures les jours ouvrables.',
    heroTitle1: 'Calculatrices. Tests.', heroTitle2: ' Coach IA.',
    heroSubtitle: (n: number) => `${n}+ outils gratuits pour la santé et les finances — calculatrices, tests scientifiques et coaching IA personnel. Sans inscription. Sans pub.`,
    heroPillCalc: 'Calculatrices', heroPillQuiz: 'Tests Scientifiques', heroPillCoach: 'Coach IA',
    coachOnlineNow: 'En ligne maintenant', coachFreeSession: 'Gratuit', coachMiaRole: 'Coach Santé', coachAlexRole: 'Coach Financier', coachMiaSpec: 'Sommeil · Poids · Stress · Énergie', coachAlexSpec: 'Budget · Épargne · Impôts', coachTalkTo: (name: string) => `Parler à ${name} →`,
    heroSources: 'Formules issues de :', heroCta1: 'Essayer la calculatrice IMC →', heroCta2: 'Calculatrice Hypothèque',
    featuredTitle: 'Calculatrices les Plus Populaires', featuredSubtitle: 'Les outils utilisés par des millions de personnes chaque jour.',
    openCalc: 'Ouvrir →', sourcesLabel: 'Formules issues de :',
    searchPlaceholder: 'Rechercher...', tabAll: 'Toutes', tabHealth: 'Santé', tabFinance: 'Finance', tabMath: 'Maths', tabConversion: 'Convertisseurs',
    countSingle: (n: number) => `${n} calculatrice`, countPlural: (n: number) => `${n} calculatrices`, noResults: (q: string) => `Aucune calculatrice trouvée pour « ${q} »`,
    breadcrumbHome: 'Accueil', medicallyReviewed: 'Validé médicalement', expertReviewed: 'Validé par des experts', journeyTitle: 'Continuez Votre Parcours',
    exploreAll: (cat: string) => `Voir toutes les calculatrices ${cat} →`,
    categoryLabels: { health: 'Santé', finance: 'Finance', math: 'Maths', conversion: 'Convertisseurs' } as Record<string, string>,
    copyResult: '📋 Copier le résultat', copied: '✅ Copié !', shareLink: '🔗 Partager le lien', print: '🖨️ Imprimer',
    calcCopy: '⎘ Copier', calcCopied: '✓ Copié', calcShare: '↗ Partager',
    whatThisMeans: 'Ce que cela signifie', whatToDoNext: 'Que faire ensuite',
    healthyWeightFor: 'Poids santé pour votre taille :', estBodyFat: 'Graisse corporelle estimée :',
    bmiContext: (bmi: string, cat: string) => `Votre IMC de ${bmi} se situe dans la plage ${cat}.`,
    bmiRangeNormal: 'La plage saine est 18,5–24,9.', bmiRangeOverweight: 'La plage saine est 18,5–24,9. Surpoids : 25–29,9.',
    bmiRangeUnder: 'La plage saine commence à 18,5.',
    bmiPrimeLabel: 'IMC Prime', bmiPrimeSub: '(1,0 = limite supérieure normale)', ponderalLabel: 'Indice Pondéral',
    categoryLabel: 'Catégorie', whoStandard: 'Norme OMS', nextSteps: 'Prochaines Étapes', methodologySources: 'Méthodologie et Sources',
    ctaCalories: 'Calculer vos calories quotidiennes →', ctaDeficit: 'Calculer votre déficit calorique →', ctaIdealWeight: 'Calculer votre poids idéal →',
    relatedTdee: 'Calculatrice TDEE', relatedTdeeDesc: 'Vos besoins caloriques journaliers totaux',
    relatedBodyFat: 'Calculatrice de Graisse Corporelle', relatedBodyFatDesc: 'Estimez votre pourcentage de graisse',
    relatedIdealWeight: 'Calculatrice de Poids Idéal', relatedIdealWeightDesc: 'Votre plage de poids optimale',
    relatedCalorieDeficit: 'Déficit Calorique', relatedCalorieDeficitDesc: 'Planifiez votre perte de poids en toute sécurité',
    optional: 'optionnel',
    footerTagline: 'Calculatrices professionnelles gratuites pour la santé, les finances, les maths et les conversions. Formules OMS, CFPB, NIST et ISO.',
    viewAll: 'Voir tout →', footerCopyright: (year: number) => `© ${year} SolviqLab. Tous droits réservés. Pas de conseil médical ou financier.`,
    footerSources: 'Formules de OMS · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Toutes les Calculatrices ${cat}`, categoryPageCount: (n: number) => `${n} calculatrices gratuites`,
    categoryPageCalc: 'Calculer →', categoryPageBack: '← Voir toutes les calculatrices',
    contentWhatIs: (kw: string) => `Qu'est-ce que le ${kw} ?`,
    contentFormula: (kw: string) => `Formule du ${kw}`,
    contentExample: (kw: string) => `Exemple du ${kw}`,
    contentHowTo: (kw: string) => `Comment utiliser le ${kw}`,
    contentWhyMatters: (kw: string) => `Pourquoi le ${kw} est Important`,
    contentLimitations: 'Limites et Précision',
    contentTips: 'Conseils Pratiques',
    apiAccess: 'Accès API', apiComingSoon: 'Bientôt disponible',
    apiDeveloper: 'API REST pour les développeurs. Intégrez cet outil dans votre application.',
    trustedSources: 'Sources et Méthodologie',
    faqTitle: 'Questions Fréquentes',
    miaGreeting: 'Bonjour ! Je suis Mia — votre coach santé personnel.',
    miaAskGoal: "Comment puis-je vous aider aujourd'hui ? Parlez-moi de votre problème ou objectif.",
    miaGetStarted: 'Commencer →', miaFree: 'Gratuit · Sans inscription', miaMeetBtn: 'Rencontrer Mia →',
    miaReviewedResults: 'Mia a examiné vos résultats.',
    miaReviewedSub: (score: number) => `Elle analyse déjà ce que signifie votre score de ${score} points spécifiquement pour vous.`,
    quizFreeLabel: 'Gratuit', quizQuestionsLabel: (n: number) => `${n} questions`,
    quizPageTitle: 'Tests de Santé Gratuits', quizPageSubtitle: 'Des tests honnêtes et scientifiques qui vous donnent un vrai aperçu de votre santé — en moins de 3 minutes. Sans inscription.', quizPageFooter: 'Tous les tests sont gratuits. Les résultats restent sur votre appareil. Sans compte.', quizClusterLabels: { weight: 'Poids', sleep: 'Sommeil', mental: 'Santé Mentale', lifestyle: 'Mode de Vie', energy: 'Énergie' } as Record<string, string>,
    miaTopicSleep: 'Qualité du sommeil', miaTopicWeight: 'Perte de poids', miaTopicStress: 'Stress', miaTopicEnergy: 'Énergie',
    miaGenerating: (name: string) => `Mia prépare votre vidéo personnelle${name ? `, ${name}` : ''}…`,
    miaGeneratingSub: 'Cela prend généralement 1–2 minutes. Restez sur la page.',
    miaClusterSleep: 'qualité du sommeil', miaClusterWeight: 'perte de poids',
    miaPlanInMotion: (name: string) => `Votre plan est en marche${name ? `, ${name}` : ''}.`,
    miaPlanFooter: 'Mia a déjà vos données. Elle n\'oublie pas.',
    miaPlanItem1: (cluster: string) => `Votre protocole de 7 jours pour ${cluster} — prêt demain`,
    miaPlanItem2: 'Objectifs personnalisés basés sur vos données',
    miaPlanItem3: 'Check-in quotidien avec Mia',
    miaRewatch: 'Revoir le message de Mia',
  },
  de: {
    navQuizzes: 'Tests', navMyAccount: 'Mein Konto',
    quizNames: { 'sleep-quiz': 'Schlafqualitätstest', 'stress-quiz': 'Stresslevel-Test', 'burnout-quiz': 'Burnout-Risiko-Test', 'energy-quiz': 'Energielevel-Test', 'bmi-quiz': 'BMI-Bewertung', 'depression-quiz': 'Depressions-Screening', 'anxiety-quiz': 'Angst-Bewertung', 'hydration-quiz': 'Hydrations-Check', 'lifestyle-quiz': 'Lebensstil-Score', 'weight-readiness-quiz': 'Gewichtsabnahme-Bereitschaft' } as Record<string, string>,
    quizSectionTitle: 'Entdecke Deinen Gesundheitsscore',
    quizSectionSubtitle: 'Kostenlose wissenschaftliche Tests · Unter 3 Min · Kein Konto nötig',
    quizCta: 'Alle Tests ansehen →',
    footerCompany: 'Unternehmen', footerAbout: 'Über uns', footerContact: 'Kontakt', footerPrivacy: 'Datenschutz', footerTerms: 'Nutzungsbedingungen', footerCoachMia: 'Coach Mia', footerCoachAlex: 'Coach Alex',
    privacyTitle: 'Datenschutzrichtlinie', privacyBreadcrumb: 'Datenschutz',
    termsTitle: 'Nutzungsbedingungen', termsBreadcrumb: 'Nutzungsbedingungen',
    contactTitle: 'Kontakt aufnehmen', contactBreadcrumb: 'Kontakt',
    contactSubtitle: 'Wir sind ein kleines Team und lesen jede Nachricht. Wir antworten innerhalb von 24–48 Stunden.',
    contactResponseNote: '⏱ Wir antworten auf alle E-Mails innerhalb von 24–48 Stunden an Werktagen.',
    heroTitle1: 'Rechner. Tests.', heroTitle2: ' KI-Coaching.',
    heroSubtitle: (n: number) => `${n}+ kostenlose Tools für Gesundheit und Finanzen — Rechner, wissenschaftliche Tests und persönliches KI-Coaching. Keine Anmeldung. Keine Werbung.`,
    heroPillCalc: 'Rechner', heroPillQuiz: 'Wissenschaftliche Tests', heroPillCoach: 'KI-Coaching',
    coachOnlineNow: 'Jetzt online', coachFreeSession: 'Kostenlos', coachMiaRole: 'Gesundheits-Coach', coachAlexRole: 'Finanz-Coach', coachMiaSpec: 'Schlaf · Gewicht · Stress · Energie', coachAlexSpec: 'Budget · Sparen · Steuern', coachTalkTo: (name: string) => `Mit ${name} sprechen →`,
    heroSources: 'Formeln aus:', heroCta1: 'BMI-Rechner ausprobieren →', heroCta2: 'Hypothekenrechner',
    featuredTitle: 'Beliebteste Rechner', featuredSubtitle: 'Die Werkzeuge, die Millionen Menschen täglich nutzen.',
    openCalc: 'Rechner öffnen →', sourcesLabel: 'Formeln aus:',
    searchPlaceholder: 'Suchen...', tabAll: 'Alle', tabHealth: 'Gesundheit', tabFinance: 'Finanzen', tabMath: 'Mathematik', tabConversion: 'Umrechner',
    countSingle: (n: number) => `${n} Rechner`, countPlural: (n: number) => `${n} Rechner`, noResults: (q: string) => `Keine Rechner für „${q}" gefunden`,
    breadcrumbHome: 'Startseite', medicallyReviewed: 'Medizinisch geprüft', expertReviewed: 'Von Experten geprüft', journeyTitle: 'Ihre Reise Fortsetzen',
    exploreAll: (cat: string) => `Alle ${cat}-Rechner anzeigen →`,
    categoryLabels: { health: 'Gesundheit', finance: 'Finanzen', math: 'Mathematik', conversion: 'Umrechner' } as Record<string, string>,
    copyResult: '📋 Ergebnis kopieren', copied: '✅ Kopiert!', shareLink: '🔗 Link teilen', print: '🖨️ Drucken',
    calcCopy: '⎘ Kopieren', calcCopied: '✓ Kopiert', calcShare: '↗ Teilen',
    whatThisMeans: 'Was das bedeutet', whatToDoNext: 'Was als nächstes zu tun ist',
    healthyWeightFor: 'Gesundes Gewicht für Ihre Größe:', estBodyFat: 'Geschätzter Körperfettanteil:',
    bmiContext: (bmi: string, cat: string) => `Ihr BMI von ${bmi} liegt im Bereich ${cat}.`,
    bmiRangeNormal: 'Der gesunde Bereich ist 18,5–24,9.', bmiRangeOverweight: 'Der gesunde Bereich ist 18,5–24,9. Übergewicht ist 25–29,9.',
    bmiRangeUnder: 'Der gesunde Bereich beginnt bei 18,5.',
    bmiPrimeLabel: 'BMI-Prime', bmiPrimeSub: '(1,0 = obere Normalgrenze)', ponderalLabel: 'Ponderaler Index',
    categoryLabel: 'Kategorie', whoStandard: 'WHO-Standard', nextSteps: 'Nächste Schritte', methodologySources: 'Methodik & Quellen',
    ctaCalories: 'Täglichen Kalorienbedarf berechnen →', ctaDeficit: 'Kaloriendefizit berechnen →', ctaIdealWeight: 'Idealgewicht berechnen →',
    relatedTdee: 'TDEE-Rechner', relatedTdeeDesc: 'Ihr gesamter täglicher Energiebedarf',
    relatedBodyFat: 'Körperfett-Rechner', relatedBodyFatDesc: 'Schätzen Sie Ihren Körperfettanteil',
    relatedIdealWeight: 'Idealgewicht-Rechner', relatedIdealWeightDesc: 'Ihr optimaler Gewichtsbereich',
    relatedCalorieDeficit: 'Kaloriendefizit', relatedCalorieDeficitDesc: 'Planen Sie Ihre Gewichtsabnahme sicher',
    optional: 'optional',
    footerTagline: 'Kostenlose professionelle Rechner für Gesundheit, Finanzen, Mathematik und Einheitenumrechnung. Formeln nach WHO, CFPB, NIST und ISO.',
    viewAll: 'Alle anzeigen →', footerCopyright: (year: number) => `© ${year} SolviqLab. Alle Rechte vorbehalten. Kein medizinischer oder finanzieller Rat.`,
    footerSources: 'Formeln von WHO · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Alle ${cat}-Rechner`, categoryPageCount: (n: number) => `${n} kostenlose Rechner`,
    categoryPageCalc: 'Berechnen →', categoryPageBack: '← Alle Rechner anzeigen',
    contentWhatIs: (kw: string) => `Was ist der ${kw}?`,
    contentFormula: (kw: string) => `Formel des ${kw}`,
    contentExample: (kw: string) => `Beispiel des ${kw}`,
    contentHowTo: (kw: string) => `So verwenden Sie den ${kw}`,
    contentWhyMatters: (kw: string) => `Warum der ${kw} Wichtig Ist`,
    contentLimitations: 'Einschränkungen & Genauigkeit',
    contentTips: 'Praktische Tipps',
    apiAccess: 'API-Zugang', apiComingSoon: 'Demnächst',
    apiDeveloper: 'REST-API für Entwickler. Integrieren Sie dieses Tool in Ihre App.',
    trustedSources: 'Quellen & Methodik',
    faqTitle: 'Häufige Fragen',
    miaGreeting: 'Hallo! Ich bin Mia — dein persönlicher Gesundheitscoach.',
    miaAskGoal: 'Womit kann ich dir heute helfen? Erzähl mir von deinem Problem oder Ziel.',
    miaGetStarted: 'Loslegen →', miaFree: 'Kostenlos · Keine Anmeldung', miaMeetBtn: 'Mia kennenlernen →',
    miaReviewedResults: 'Mia hat deine Ergebnisse überprüft.',
    miaReviewedSub: (score: number) => `Sie analysiert bereits, was dein ${score}-Punkte-Ergebnis speziell für dich bedeutet.`,
    quizFreeLabel: 'Kostenlos', quizQuestionsLabel: (n: number) => `${n} Fragen`,
    quizPageTitle: 'Kostenlose Gesundheitstests', quizPageSubtitle: 'Ehrliche, wissenschaftlich fundierte Tests — in unter 3 Minuten. Keine Anmeldung erforderlich.', quizPageFooter: 'Alle Tests sind kostenlos. Ergebnisse bleiben auf Ihrem Gerät. Kein Konto nötig.', quizClusterLabels: { weight: 'Gewicht', sleep: 'Schlaf', mental: 'Psychische Gesundheit', lifestyle: 'Lebensstil', energy: 'Energie' } as Record<string, string>,
    miaTopicSleep: 'Schlafqualität', miaTopicWeight: 'Gewichtsabnahme', miaTopicStress: 'Stress', miaTopicEnergy: 'Energie',
    miaGenerating: (name: string) => `Mia bereitet dein persönliches Video vor${name ? `, ${name}` : ''}…`,
    miaGeneratingSub: 'Das dauert normalerweise 1–2 Minuten. Bleib auf der Seite.',
    miaClusterSleep: 'Schlafqualität', miaClusterWeight: 'Gewichtsabnahme',
    miaPlanInMotion: (name: string) => `Dein Plan ist in Bewegung${name ? `, ${name}` : ''}.`,
    miaPlanFooter: 'Mia hat bereits deine Daten. Sie vergisst nicht.',
    miaPlanItem1: (cluster: string) => `Dein 7-Tage-Protokoll für ${cluster} — morgen bereit`,
    miaPlanItem2: 'Personalisierte Ziele basierend auf deinen Daten',
    miaPlanItem3: 'Tägliches Check-in mit Mia',
    miaRewatch: 'Mias Nachricht nochmal ansehen',
  },
  pl: {
    navQuizzes: 'Testy', navMyAccount: 'Moje Konto',
    quizNames: { 'sleep-quiz': 'Test Jakości Snu', 'stress-quiz': 'Test Poziomu Stresu', 'burnout-quiz': 'Test Ryzyka Wypalenia', 'energy-quiz': 'Test Poziomów Energii', 'bmi-quiz': 'Ocena BMI', 'depression-quiz': 'Badanie Depresji', 'anxiety-quiz': 'Ocena Lęku', 'hydration-quiz': 'Kontrola Nawodnienia', 'lifestyle-quiz': 'Wynik Stylu Życia', 'weight-readiness-quiz': 'Gotowość do Odchudzania' } as Record<string, string>,
    quizSectionTitle: 'Poznaj Swój Wynik Zdrowia',
    quizSectionSubtitle: 'Bezpłatne testy naukowe · Poniżej 3 min · Bez konta',
    quizCta: 'Zobacz wszystkie testy →',
    footerCompany: 'Firma', footerAbout: 'O nas', footerContact: 'Kontakt', footerPrivacy: 'Prywatność', footerTerms: 'Warunki użytkowania', footerCoachMia: 'Coach Mia', footerCoachAlex: 'Coach Alex',
    privacyTitle: 'Polityka prywatności', privacyBreadcrumb: 'Prywatność',
    termsTitle: 'Warunki korzystania', termsBreadcrumb: 'Warunki',
    contactTitle: 'Skontaktuj się', contactBreadcrumb: 'Kontakt',
    contactSubtitle: 'Jesteśmy małym zespołem i czytamy każdą wiadomość. Odpowiadamy w ciągu 24–48 godzin.',
    contactResponseNote: '⏱ Odpowiadamy na wszystkie e-maile w ciągu 24–48 godzin w dni robocze.',
    heroTitle1: 'Kalkulatory. Testy.', heroTitle2: ' Coaching AI.',
    heroSubtitle: (n: number) => `${n}+ darmowych narzędzi dla zdrowia i finansów — kalkulatory, naukowe testy i osobisty coaching AI. Bez rejestracji. Bez reklam.`,
    heroPillCalc: 'Kalkulatory', heroPillQuiz: 'Testy Naukowe', heroPillCoach: 'Coaching AI',
    coachOnlineNow: 'Teraz online', coachFreeSession: 'Bezpłatnie', coachMiaRole: 'Coach Zdrowia', coachAlexRole: 'Coach Finansowy', coachMiaSpec: 'Sen · Waga · Stres · Energia', coachAlexSpec: 'Budżet · Oszczędności · Podatki', coachTalkTo: (name: string) => `Porozmawiaj z ${name} →`,
    heroSources: 'Wzory z:', heroCta1: 'Wypróbuj Kalkulator BMI →', heroCta2: 'Kalkulator Kredytu Hipotecznego',
    featuredTitle: 'Najpopularniejsze Kalkulatory', featuredSubtitle: 'Narzędzia, których miliony ludzi używają każdego dnia.',
    openCalc: 'Otwórz Kalkulator →', sourcesLabel: 'Wzory z:',
    searchPlaceholder: 'Szukaj...', tabAll: 'Wszystkie', tabHealth: 'Zdrowie', tabFinance: 'Finanse', tabMath: 'Matematyka', tabConversion: 'Przeliczniki',
    countSingle: (n: number) => `${n} kalkulator`, countPlural: (n: number) => `${n} kalkulatorów`, noResults: (q: string) => `Nie znaleziono kalkulatorów dla „${q}"`,
    breadcrumbHome: 'Strona główna', medicallyReviewed: 'Zweryfikowane medycznie', expertReviewed: 'Zweryfikowane przez ekspertów', journeyTitle: 'Kontynuuj Swoją Podróż',
    exploreAll: (cat: string) => `Zobacz wszystkie kalkulatory ${cat} →`,
    categoryLabels: { health: 'Zdrowie', finance: 'Finanse', math: 'Matematyka', conversion: 'Przeliczniki' } as Record<string, string>,
    copyResult: '📋 Kopiuj wynik', copied: '✅ Skopiowano!', shareLink: '🔗 Udostępnij link', print: '🖨️ Drukuj',
    calcCopy: '⎘ Kopiuj', calcCopied: '✓ Skopiowano', calcShare: '↗ Udostępnij',
    whatThisMeans: 'Co to oznacza', whatToDoNext: 'Co zrobić dalej',
    healthyWeightFor: 'Zdrowa waga dla Twojego wzrostu:', estBodyFat: 'Szacowana tkanka tłuszczowa:',
    bmiContext: (bmi: string, cat: string) => `Twoje BMI wynosi ${bmi} i mieści się w zakresie ${cat}.`,
    bmiRangeNormal: 'Zdrowy zakres to 18,5–24,9.', bmiRangeOverweight: 'Zdrowy zakres to 18,5–24,9. Nadwaga: 25–29,9.',
    bmiRangeUnder: 'Zdrowy zakres zaczyna się od 18,5.',
    bmiPrimeLabel: 'BMI Prime', bmiPrimeSub: '(1,0 = górna granica normy)', ponderalLabel: 'Wskaźnik Ponderalny',
    categoryLabel: 'Kategoria', whoStandard: 'Standard WHO', nextSteps: 'Następne Kroki', methodologySources: 'Metodologia i Źródła',
    ctaCalories: 'Oblicz dzienne zapotrzebowanie kaloryczne →', ctaDeficit: 'Oblicz deficyt kaloryczny →', ctaIdealWeight: 'Oblicz idealną wagę →',
    relatedTdee: 'Kalkulator TDEE', relatedTdeeDesc: 'Twoje całkowite dzienne zapotrzebowanie energetyczne',
    relatedBodyFat: 'Kalkulator Tkanki Tłuszczowej', relatedBodyFatDesc: 'Oszacuj swój procent tkanki tłuszczowej',
    relatedIdealWeight: 'Kalkulator Idealnej Wagi', relatedIdealWeightDesc: 'Twój optymalny zakres wagi',
    relatedCalorieDeficit: 'Deficyt Kaloryczny', relatedCalorieDeficitDesc: 'Zaplanuj bezpieczne odchudzanie',
    optional: 'opcjonalne',
    footerTagline: 'Darmowe profesjonalne kalkulatory do zdrowia, finansów, matematyki i przeliczania jednostek. Wzory wg WHO, CFPB, NIST i ISO.',
    viewAll: 'Zobacz wszystkie →', footerCopyright: (year: number) => `© ${year} SolviqLab. Wszelkie prawa zastrzeżone. Nie jest to porada medyczna ani finansowa.`,
    footerSources: 'Wzory z WHO · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Wszystkie Kalkulatory: ${cat}`, categoryPageCount: (n: number) => `${n} darmowych kalkulatorów`,
    categoryPageCalc: 'Oblicz →', categoryPageBack: '← Zobacz wszystkie kalkulatory',
    contentWhatIs: (kw: string) => `Czym jest ${kw}?`,
    contentFormula: (kw: string) => `Wzór ${kw}`,
    contentExample: (kw: string) => `Przykład ${kw}`,
    contentHowTo: (kw: string) => `Jak używać ${kw}`,
    contentWhyMatters: (kw: string) => `Dlaczego ${kw} Jest Ważny`,
    contentLimitations: 'Ograniczenia i Dokładność',
    contentTips: 'Praktyczne Wskazówki',
    apiAccess: 'Dostęp API', apiComingSoon: 'Wkrótce',
    apiDeveloper: 'REST API dla deweloperów. Zintegruj to narzędzie ze swoją aplikacją.',
    trustedSources: 'Źródła i Metodologia',
    faqTitle: 'Często zadawane pytania',
    miaGreeting: 'Cześć! Jestem Mia — Twój osobisty coach zdrowia.',
    miaAskGoal: 'W czym mogę Ci pomóc dzisiaj? Opowiedz mi o swoim problemie lub celu.',
    miaGetStarted: 'Zaczynamy →', miaFree: 'Bezpłatnie · Bez rejestracji', miaMeetBtn: 'Poznaj Mię →',
    miaReviewedResults: 'Mia przejrzała Twoje wyniki.',
    miaReviewedSub: (score: number) => `Już analizuje, co oznacza Twój wynik ${score} punktów specjalnie dla Ciebie.`,
    quizFreeLabel: 'Bezpłatnie', quizQuestionsLabel: (n: number) => `${n} pytań`,
    quizPageTitle: 'Bezpłatne Testy Zdrowia', quizPageSubtitle: 'Uczciwe, poparte nauką testy — w mniej niż 3 minuty. Bez rejestracji.', quizPageFooter: 'Wszystkie testy są bezpłatne. Wyniki na urządzeniu. Bez konta.', quizClusterLabels: { weight: 'Waga', sleep: 'Sen', mental: 'Zdrowie Psychiczne', lifestyle: 'Styl Życia', energy: 'Energia' } as Record<string, string>,
    miaTopicSleep: 'Jakość snu', miaTopicWeight: 'Utrata wagi', miaTopicStress: 'Stres', miaTopicEnergy: 'Energia',
    miaGenerating: (name: string) => `Mia przygotowuje Twój osobisty film${name ? `, ${name}` : ''}…`,
    miaGeneratingSub: 'Zazwyczaj trwa to 1–2 minuty. Zostań na stronie.',
    miaClusterSleep: 'jakość snu', miaClusterWeight: 'utrata wagi',
    miaPlanInMotion: (name: string) => `Twój plan jest w toku${name ? `, ${name}` : ''}.`,
    miaPlanFooter: 'Mia ma już Twoje dane. Ona nie zapomina.',
    miaPlanItem1: (cluster: string) => `Twój 7-dniowy protokół dla ${cluster} — gotowy jutro`,
    miaPlanItem2: 'Spersonalizowane cele oparte na Twoich danych',
    miaPlanItem3: 'Codzienne check-in z Mią',
    miaRewatch: 'Obejrzyj wiadomość Mii ponownie',
  },
  tr: {
    navQuizzes: 'Testler', navMyAccount: 'Hesabım',
    quizNames: { 'sleep-quiz': 'Uyku Kalitesi Testi', 'stress-quiz': 'Stres Seviyesi Testi', 'burnout-quiz': 'Tükenmişlik Risk Testi', 'energy-quiz': 'Enerji Seviyesi Testi', 'bmi-quiz': 'VKİ Değerlendirmesi', 'depression-quiz': 'Depresyon Taraması', 'anxiety-quiz': 'Anksiyete Değerlendirmesi', 'hydration-quiz': 'Hidrasyon Kontrolü', 'lifestyle-quiz': 'Yaşam Tarzı Skoru', 'weight-readiness-quiz': 'Kilo Vermeye Hazırlık' } as Record<string, string>,
    quizSectionTitle: 'Sağlık Skorunu Keşfet',
    quizSectionSubtitle: 'Ücretsiz bilimsel testler · 3 dakikadan az · Hesap gerektirmez',
    quizCta: 'Tüm testleri gör →',
    footerCompany: 'Şirket', footerAbout: 'Hakkımızda', footerContact: 'İletişim', footerPrivacy: 'Gizlilik', footerTerms: 'Kullanım Koşulları', footerCoachMia: 'Coach Mia', footerCoachAlex: 'Coach Alex',
    privacyTitle: 'Gizlilik Politikası', privacyBreadcrumb: 'Gizlilik',
    termsTitle: 'Kullanım Koşulları', termsBreadcrumb: 'Koşullar',
    contactTitle: 'İletişime Geç', contactBreadcrumb: 'İletişim',
    contactSubtitle: 'Küçük bir ekibiz ve her mesajı okuyoruz. Genellikle 24–48 saat içinde yanıt veririz.',
    contactResponseNote: '⏱ Tüm e-postalara iş günlerinde 24–48 saat içinde yanıt veririz.',
    heroTitle1: 'Hesap Makineleri. Testler.', heroTitle2: ' Yapay Zeka Koçluğu.',
    heroSubtitle: (n: number) => `Sağlık ve finans için ${n}+ ücretsiz araç — hesap makineleri, bilimsel testler ve kişisel yapay zeka koçluğu. Kayıt yok. Reklam yok.`,
    heroPillCalc: 'Hesap Makineleri', heroPillQuiz: 'Bilimsel Testler', heroPillCoach: 'Yapay Zeka Koçluğu',
    coachOnlineNow: 'Şu an çevrimiçi', coachFreeSession: 'Ücretsiz', coachMiaRole: 'Sağlık Koçu', coachAlexRole: 'Finans Koçu', coachMiaSpec: 'Uyku · Kilo · Stres · Enerji', coachAlexSpec: 'Bütçe · Tasarruf · Vergiler', coachTalkTo: (name: string) => `${name} ile konuş →`,
    heroSources: 'Formüller kaynakları:', heroCta1: 'VKİ Hesaplayıcısını Dene →', heroCta2: 'Mortgage Hesaplayıcısı',
    featuredTitle: 'En Popüler Hesaplayıcılar', featuredSubtitle: 'Milyonlarca insanın her gün kullandığı araçlar.',
    openCalc: 'Hesaplayıcıyı Aç →', sourcesLabel: 'Formüller kaynakları:',
    searchPlaceholder: 'Ara...', tabAll: 'Tümü', tabHealth: 'Sağlık', tabFinance: 'Finans', tabMath: 'Matematik', tabConversion: 'Dönüştürücüler',
    countSingle: (n: number) => `${n} hesaplayıcı`, countPlural: (n: number) => `${n} hesaplayıcı`, noResults: (q: string) => `"${q}" için hesaplayıcı bulunamadı`,
    breadcrumbHome: 'Ana Sayfa', medicallyReviewed: 'Tıbbi onaylı', expertReviewed: 'Uzman onaylı', journeyTitle: 'Yolculuğuna Devam Et',
    exploreAll: (cat: string) => `Tüm ${cat} hesaplayıcılarını gör →`,
    categoryLabels: { health: 'Sağlık', finance: 'Finans', math: 'Matematik', conversion: 'Dönüştürücüler' } as Record<string, string>,
    copyResult: '📋 Sonucu kopyala', copied: '✅ Kopyalandı!', shareLink: '🔗 Linki paylaş', print: '🖨️ Yazdır',
    calcCopy: '⎘ Kopyala', calcCopied: '✓ Kopyalandı', calcShare: '↗ Paylaş',
    whatThisMeans: 'Bu ne anlama geliyor', whatToDoNext: 'Sırada ne var',
    healthyWeightFor: 'Boyunuz için sağlıklı kilo:', estBodyFat: 'Tahmini vücut yağı:',
    bmiContext: (bmi: string, cat: string) => `${bmi} VKİ değeriniz ${cat} aralığında.`,
    bmiRangeNormal: 'Sağlıklı aralık 18,5–24,9.', bmiRangeOverweight: 'Sağlıklı aralık 18,5–24,9. Fazla kilo: 25–29,9.',
    bmiRangeUnder: 'Sağlıklı aralık 18,5\'ten başlar.',
    bmiPrimeLabel: 'VKİ Prime', bmiPrimeSub: '(1,0 = normal üst sınır)', ponderalLabel: 'Ponderal İndeks',
    categoryLabel: 'Kategori', whoStandard: 'WHO standardı', nextSteps: 'Sonraki Adımlar', methodologySources: 'Metodoloji ve Kaynaklar',
    ctaCalories: 'Günlük kalori ihtiyacını hesapla →', ctaDeficit: 'Kalori açığını hesapla →', ctaIdealWeight: 'İdeal kilonu hesapla →',
    relatedTdee: 'TDEE Hesaplayıcısı', relatedTdeeDesc: 'Toplam günlük kalori ihtiyacın',
    relatedBodyFat: 'Vücut Yağı Hesaplayıcısı', relatedBodyFatDesc: 'Vücut yağı yüzdesini tahmin et',
    relatedIdealWeight: 'İdeal Kilo Hesaplayıcısı', relatedIdealWeightDesc: 'Optimal kilo aralığın',
    relatedCalorieDeficit: 'Kalori Açığı', relatedCalorieDeficitDesc: 'Kilo kaybını güvenle planla',
    optional: 'isteğe bağlı',
    footerTagline: 'Sağlık, finans, matematik ve birim dönüşümleri için ücretsiz profesyonel hesap makineleri. WHO, CFPB, NIST ve ISO destekli formüller.',
    viewAll: 'Tümünü gör →', footerCopyright: (year: number) => `© ${year} SolviqLab. Tüm hakları saklıdır. Tıbbi veya finansal tavsiye değildir.`,
    footerSources: 'Formüller: WHO · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Tüm ${cat} Hesaplayıcıları`, categoryPageCount: (n: number) => `${n} ücretsiz hesaplayıcı`,
    categoryPageCalc: 'Hesapla →', categoryPageBack: '← Tüm hesaplayıcılara dön',
    contentWhatIs: (kw: string) => `${kw} Nedir?`,
    contentFormula: (kw: string) => `${kw} Formülü`,
    contentExample: (kw: string) => `${kw} Örneği`,
    contentHowTo: (kw: string) => `${kw} Nasıl Kullanılır`,
    contentWhyMatters: (kw: string) => `${kw} Neden Önemlidir`,
    contentLimitations: 'Sınırlamalar ve Doğruluk',
    contentTips: 'Pratik İpuçları',
    apiAccess: 'API Erişimi', apiComingSoon: 'Yakında',
    apiDeveloper: 'Geliştiriciler için REST API. Bu aracı uygulamanıza entegre edin.',
    trustedSources: 'Güvenilir Kaynaklar ve Metodoloji',
    faqTitle: 'Sıkça Sorulan Sorular',
    miaGreeting: 'Merhaba! Ben Mia — kişisel sağlık koçun.',
    miaAskGoal: 'Bugün sana nasıl yardımcı olabilirim? Sorununu veya hedefini anlat.',
    miaGetStarted: 'Başla →', miaFree: 'Ücretsiz · Kayıt gerektirmez', miaMeetBtn: "Mia'yı tanı →",
    miaReviewedResults: 'Mia sonuçlarını inceledi.',
    miaReviewedSub: (score: number) => `${score} puanlık sonucunun senin için özel olarak ne anlama geldiğini zaten analiz ediyor.`,
    quizFreeLabel: 'Ücretsiz', quizQuestionsLabel: (n: number) => `${n} soru`,
    quizPageTitle: 'Ücretsiz Sağlık Testleri', quizPageSubtitle: 'Dürüst, bilimsel testler — 3 dakikadan az sürede sağlığınızın gerçek görünümü. Kayıt gerekmez.', quizPageFooter: 'Tüm testler ücretsizdir. Sonuçlar cihazınızda kalır. Hesap gerekmez.', quizClusterLabels: { weight: 'Kilo', sleep: 'Uyku', mental: 'Ruh Sağlığı', lifestyle: 'Yaşam Tarzı', energy: 'Enerji' } as Record<string, string>,
    miaTopicSleep: 'Uyku kalitesi', miaTopicWeight: 'Kilo kaybı', miaTopicStress: 'Stres', miaTopicEnergy: 'Enerji',
    miaGenerating: (name: string) => `Mia kişisel videonuzu hazırlıyor${name ? `, ${name}` : ''}…`,
    miaGeneratingSub: 'Bu genellikle 1–2 dakika sürer. Sayfada kalın.',
    miaClusterSleep: 'uyku kalitesi', miaClusterWeight: 'kilo kaybı',
    miaPlanInMotion: (name: string) => `Planın harekete geçti${name ? `, ${name}` : ''}.`,
    miaPlanFooter: 'Mia zaten verilerinize sahip. O unutmaz.',
    miaPlanItem1: (cluster: string) => `${cluster} için 7 günlük protokolün — yarın hazır`,
    miaPlanItem2: 'Verilerinize dayalı kişiselleştirilmiş hedefler',
    miaPlanItem3: "Mia ile günlük check-in",
    miaRewatch: "Mia'nın mesajını tekrar izle",
  },
  it: {
    navQuizzes: 'Test', navMyAccount: 'Il Mio Account',
    quizNames: { 'sleep-quiz': 'Test di Qualità del Sonno', 'stress-quiz': 'Test del Livello di Stress', 'burnout-quiz': 'Test di Rischio Burnout', 'energy-quiz': 'Test dei Livelli di Energia', 'bmi-quiz': 'Valutazione IMC', 'depression-quiz': 'Screening della Depressione', 'anxiety-quiz': "Valutazione dell'Ansia", 'hydration-quiz': "Controllo dell'Idratazione", 'lifestyle-quiz': 'Punteggio Stile di Vita', 'weight-readiness-quiz': 'Preparazione alla Perdita di Peso' } as Record<string, string>,
    quizSectionTitle: 'Scopri il Tuo Punteggio di Salute',
    quizSectionSubtitle: 'Test scientifici gratuiti · Meno di 3 min · Nessun account',
    quizCta: 'Vedi tutti i test →',
    footerCompany: 'Azienda', footerAbout: 'Chi siamo', footerContact: 'Contatti', footerPrivacy: 'Privacy', footerTerms: 'Termini di servizio', footerCoachMia: 'Coach Mia', footerCoachAlex: 'Coach Alex',
    privacyTitle: 'Informativa sulla privacy', privacyBreadcrumb: 'Privacy',
    termsTitle: 'Termini di servizio', termsBreadcrumb: 'Termini',
    contactTitle: 'Contattaci', contactBreadcrumb: 'Contatti',
    contactSubtitle: 'Siamo un piccolo team e leggiamo ogni messaggio. Rispondiamo entro 24–48 ore.',
    contactResponseNote: '⏱ Rispondiamo a tutte le email entro 24–48 ore nei giorni lavorativi.',
    heroTitle1: 'Calcolatori. Test.', heroTitle2: ' Coaching IA.',
    heroSubtitle: (n: number) => `${n}+ strumenti gratuiti per salute e finanza — calcolatori, test scientifici e coaching IA personale. Nessuna registrazione. Nessuna pubblicità.`,
    heroPillCalc: 'Calcolatori', heroPillQuiz: 'Test Scientifici', heroPillCoach: 'Coaching IA',
    coachOnlineNow: 'Online ora', coachFreeSession: 'Gratuito', coachMiaRole: 'Coach della Salute', coachAlexRole: 'Coach Finanziario', coachMiaSpec: 'Sonno · Peso · Stress · Energia', coachAlexSpec: 'Budget · Risparmio · Tasse', coachTalkTo: (name: string) => `Parla con ${name} →`,
    heroSources: 'Formule tratte da:', heroCta1: 'Prova il Calcolatore IMC →', heroCta2: 'Calcolatore Mutuo',
    featuredTitle: 'Calcolatori Più Popolari', featuredSubtitle: 'Gli strumenti che milioni di persone usano ogni giorno.',
    openCalc: 'Apri Calcolatore →', sourcesLabel: 'Formule tratte da:',
    searchPlaceholder: 'Cerca...', tabAll: 'Tutti', tabHealth: 'Salute', tabFinance: 'Finanza', tabMath: 'Matematica', tabConversion: 'Conversioni',
    countSingle: (n: number) => `${n} calcolatore`, countPlural: (n: number) => `${n} calcolatori`, noResults: (q: string) => `Nessun calcolatore trovato per "${q}"`,
    breadcrumbHome: 'Home', medicallyReviewed: 'Revisione medica', expertReviewed: 'Revisione esperto', journeyTitle: 'Continua il Percorso',
    exploreAll: (cat: string) => `Esplora tutti i calcolatori ${cat} →`,
    categoryLabels: { health: 'Salute', finance: 'Finanza', math: 'Matematica', conversion: 'Conversioni' } as Record<string, string>,
    copyResult: '📋 Copia risultato', copied: '✅ Copiato!', shareLink: '🔗 Condividi link', print: '🖨️ Stampa',
    calcCopy: '⎘ Copia', calcCopied: '✓ Copiato', calcShare: '↗ Condividi',
    whatThisMeans: 'Cosa significa', whatToDoNext: 'Prossimi passi',
    healthyWeightFor: 'Peso sano per la tua altezza:', estBodyFat: 'Grasso corporeo stimato:',
    bmiContext: (bmi: string, cat: string) => `Il tuo IMC di ${bmi} rientra nella categoria ${cat}.`,
    bmiRangeNormal: 'Il range sano è 18,5–24,9.', bmiRangeOverweight: 'Il range sano è 18,5–24,9. Sovrappeso: 25–29,9.',
    bmiRangeUnder: 'Il range sano inizia da 18,5.',
    bmiPrimeLabel: 'IMC Prime', bmiPrimeSub: '(1,0 = limite superiore normale)', ponderalLabel: 'Indice Ponderale',
    categoryLabel: 'Categoria', whoStandard: 'Standard OMS', nextSteps: 'Prossimi Passi', methodologySources: 'Metodologia e Fonti',
    ctaCalories: 'Calcola il tuo fabbisogno calorico →', ctaDeficit: 'Calcola il tuo deficit calorico →', ctaIdealWeight: 'Calcola il tuo peso ideale →',
    relatedTdee: 'Calcolatore TDEE', relatedTdeeDesc: 'Il tuo fabbisogno calorico giornaliero totale',
    relatedBodyFat: 'Calcolatore Grasso Corporeo', relatedBodyFatDesc: 'Stima la percentuale di grasso corporeo',
    relatedIdealWeight: 'Calcolatore Peso Ideale', relatedIdealWeightDesc: 'Il tuo intervallo di peso ottimale',
    relatedCalorieDeficit: 'Deficit Calorico', relatedCalorieDeficitDesc: 'Pianifica la perdita di peso in sicurezza',
    optional: 'opzionale',
    footerTagline: 'Calcolatori professionali gratuiti per salute, finanza, matematica e conversioni. Formule basate su OMS, CFPB, NIST e ISO.',
    viewAll: 'Vedi tutti →', footerCopyright: (year: number) => `© ${year} SolviqLab. Tutti i diritti riservati. Non è un consiglio medico o finanziario.`,
    footerSources: 'Formule tratte da OMS · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Tutti i Calcolatori ${cat}`, categoryPageCount: (n: number) => `${n} calcolatori gratuiti`,
    categoryPageCalc: 'Calcola →', categoryPageBack: '← Esplora tutti i calcolatori',
    contentWhatIs: (kw: string) => `Che cos\u2019è il ${kw}?`,
    contentFormula: (kw: string) => `Formula ${kw}`,
    contentExample: (kw: string) => `Esempio ${kw}`,
    contentHowTo: (kw: string) => `Come usare il ${kw}`,
    contentWhyMatters: (kw: string) => `Perché il ${kw} è importante`,
    contentLimitations: 'Limitazioni e Precisione',
    contentTips: 'Consigli Pratici',
    apiAccess: 'Accesso API', apiComingSoon: 'Prossimamente',
    apiDeveloper: 'REST API per sviluppatori. Integra questo strumento nella tua app.',
    trustedSources: 'Fonti Affidabili e Metodologia',
    faqTitle: 'Domande Frequenti',
    miaGreeting: 'Ciao! Sono Mia — la tua coach della salute personale.',
    miaAskGoal: 'Come posso aiutarti oggi? Raccontami il tuo problema o obiettivo.',
    miaGetStarted: 'Inizia →', miaFree: 'Gratuito · Senza registrazione', miaMeetBtn: 'Incontra Mia →',
    miaReviewedResults: 'Mia ha esaminato i tuoi risultati.',
    miaReviewedSub: (score: number) => `Sta già analizzando cosa significa il tuo punteggio di ${score} punti specificamente per te.`,
    quizFreeLabel: 'Gratuito', quizQuestionsLabel: (n: number) => `${n} domande`,
    quizPageTitle: 'Test di Salute Gratuiti', quizPageSubtitle: 'Test onesti e scientifici che ti danno un vero quadro della tua salute — in meno di 3 minuti. Senza registrazione.', quizPageFooter: 'Tutti i test sono gratuiti. I risultati rimangono sul dispositivo. Nessun account.', quizClusterLabels: { weight: 'Peso', sleep: 'Sonno', mental: 'Salute Mentale', lifestyle: 'Stile di Vita', energy: 'Energia' } as Record<string, string>,
    miaTopicSleep: 'Qualità del sonno', miaTopicWeight: 'Perdita di peso', miaTopicStress: 'Stress', miaTopicEnergy: 'Energia',
    miaGenerating: (name: string) => `Mia sta preparando il tuo video personale${name ? `, ${name}` : ''}…`,
    miaGeneratingSub: 'Di solito ci vogliono 1–2 minuti. Rimani sulla pagina.',
    miaClusterSleep: 'qualità del sonno', miaClusterWeight: 'perdita di peso',
    miaPlanInMotion: (name: string) => `Il tuo piano è in moto${name ? `, ${name}` : ''}.`,
    miaPlanFooter: 'Mia ha già i tuoi dati. Lei non dimentica.',
    miaPlanItem1: (cluster: string) => `Il tuo protocollo di 7 giorni per ${cluster} — pronto domani`,
    miaPlanItem2: 'Obiettivi personalizzati basati sui tuoi dati',
    miaPlanItem3: 'Check-in quotidiano con Mia',
    miaRewatch: 'Rivedi il messaggio di Mia',
  },
  nl: {
    navQuizzes: 'Testen', navMyAccount: 'Mijn Account',
    quizNames: { 'sleep-quiz': 'Slaapkwaliteitstest', 'stress-quiz': 'Stressniveautest', 'burnout-quiz': 'Burnoutrisico Test', 'energy-quiz': 'Energieniveautest', 'bmi-quiz': 'BMI-beoordeling', 'depression-quiz': 'Depressiescreening', 'anxiety-quiz': 'Angstbeoordeling', 'hydration-quiz': 'Hydratatie Check', 'lifestyle-quiz': 'Leefstijlscore', 'weight-readiness-quiz': 'Afvallen Gereedheid' } as Record<string, string>,
    quizSectionTitle: 'Ontdek Jouw Gezondheidsscore',
    quizSectionSubtitle: 'Gratis wetenschappelijke testen · Onder 3 min · Geen account nodig',
    quizCta: 'Bekijk alle testen →',
    footerCompany: 'Bedrijf', footerAbout: 'Over ons', footerContact: 'Contact', footerPrivacy: 'Privacy', footerTerms: 'Gebruiksvoorwaarden', footerCoachMia: 'Coach Mia', footerCoachAlex: 'Coach Alex',
    privacyTitle: 'Privacybeleid', privacyBreadcrumb: 'Privacy',
    termsTitle: 'Servicevoorwaarden', termsBreadcrumb: 'Voorwaarden',
    contactTitle: 'Contact opnemen', contactBreadcrumb: 'Contact',
    contactSubtitle: 'We zijn een klein team en lezen elk bericht. We reageren doorgaans binnen 24–48 uur.',
    contactResponseNote: '⏱ We reageren op alle e-mails binnen 24–48 uur op werkdagen.',
    heroTitle1: 'Rekenmachines. Tests.', heroTitle2: ' AI-coaching.',
    heroSubtitle: (n: number) => `${n}+ gratis tools voor gezondheid en financiën — rekenmachines, wetenschappelijke tests en persoonlijke AI-coaching. Geen registratie. Geen advertenties.`,
    heroPillCalc: 'Rekenmachines', heroPillQuiz: 'Wetenschappelijke Tests', heroPillCoach: 'AI-coaching',
    coachOnlineNow: 'Nu online', coachFreeSession: 'Gratis', coachMiaRole: 'Gezondheidscoach', coachAlexRole: 'Financiële Coach', coachMiaSpec: 'Slaap · Gewicht · Stress · Energie', coachAlexSpec: 'Budget · Sparen · Belastingen', coachTalkTo: (name: string) => `Praat met ${name} →`,
    heroSources: 'Formules afkomstig van:', heroCta1: 'Probeer BMI-calculator →', heroCta2: 'Hypotheekcalculator',
    featuredTitle: 'Meest Populaire Rekenmachines', featuredSubtitle: 'De tools die miljoenen mensen dagelijks gebruiken.',
    openCalc: 'Open Rekenmachine →', sourcesLabel: 'Formules afkomstig van:',
    searchPlaceholder: 'Zoeken...', tabAll: 'Alle', tabHealth: 'Gezondheid', tabFinance: 'Financiën', tabMath: 'Wiskunde', tabConversion: 'Converters',
    countSingle: (n: number) => `${n} rekenmachine`, countPlural: (n: number) => `${n} rekenmachines`, noResults: (q: string) => `Geen rekenmachines gevonden voor "${q}"`,
    breadcrumbHome: 'Home', medicallyReviewed: 'Medisch beoordeeld', expertReviewed: 'Beoordeeld door expert', journeyTitle: 'Ga Verder',
    exploreAll: (cat: string) => `Bekijk alle ${cat} rekenmachines →`,
    categoryLabels: { health: 'Gezondheid', finance: 'Financiën', math: 'Wiskunde', conversion: 'Converters' } as Record<string, string>,
    copyResult: '📋 Resultaat kopiëren', copied: '✅ Gekopieerd!', shareLink: '🔗 Link delen', print: '🖨️ Afdrukken',
    calcCopy: '⎘ Kopiëren', calcCopied: '✓ Gekopieerd', calcShare: '↗ Delen',
    whatThisMeans: 'Wat dit betekent', whatToDoNext: 'Wat nu te doen',
    healthyWeightFor: 'Gezond gewicht voor uw lengte:', estBodyFat: 'Geschat lichaamsvet:',
    bmiContext: (bmi: string, cat: string) => `Uw BMI van ${bmi} valt in de categorie ${cat}.`,
    bmiRangeNormal: 'Het gezonde bereik is 18,5–24,9.', bmiRangeOverweight: 'Het gezonde bereik is 18,5–24,9. Overgewicht: 25–29,9.',
    bmiRangeUnder: 'Het gezonde bereik begint bij 18,5.',
    bmiPrimeLabel: 'BMI Prime', bmiPrimeSub: '(1,0 = bovengrens normaal)', ponderalLabel: 'Ponderale Index',
    categoryLabel: 'Categorie', whoStandard: 'WHO-standaard', nextSteps: 'Volgende Stappen', methodologySources: 'Methodologie & Bronnen',
    ctaCalories: 'Bereken uw dagelijkse calorieën →', ctaDeficit: 'Bereken uw calorietekort →', ctaIdealWeight: 'Bereken uw ideale gewicht →',
    relatedTdee: 'TDEE-calculator', relatedTdeeDesc: 'Uw totale dagelijkse caloriebehoefte',
    relatedBodyFat: 'Lichaamsvetcalculator', relatedBodyFatDesc: 'Schat uw lichaamsvetpercentage',
    relatedIdealWeight: 'Ideaal Gewicht Calculator', relatedIdealWeightDesc: 'Uw optimale gewichtsbereik',
    relatedCalorieDeficit: 'Calorietekort', relatedCalorieDeficitDesc: 'Plan uw gewichtsverlies veilig',
    optional: 'optioneel',
    footerTagline: 'Gratis professionele rekenmachines voor gezondheid, financiën, wiskunde en eenheidsconversies. Formules gebaseerd op WHO, CFPB, NIST en ISO.',
    viewAll: 'Bekijk alles →', footerCopyright: (year: number) => `© ${year} SolviqLab. Alle rechten voorbehouden. Geen medisch of financieel advies.`,
    footerSources: 'Formules afkomstig van WHO · CFPB · NIST · ISO',
    categoryPageAll: (cat: string) => `Alle ${cat} Rekenmachines`, categoryPageCount: (n: number) => `${n} gratis rekenmachines`,
    categoryPageCalc: 'Bereken →', categoryPageBack: '← Bekijk alle rekenmachines',
    contentWhatIs: (kw: string) => `Wat is de ${kw}?`,
    contentFormula: (kw: string) => `${kw} Formule`,
    contentExample: (kw: string) => `${kw} Voorbeeld`,
    contentHowTo: (kw: string) => `Hoe de ${kw} te gebruiken`,
    contentWhyMatters: (kw: string) => `Waarom ${kw} belangrijk is`,
    contentLimitations: 'Beperkingen & Nauwkeurigheid',
    contentTips: 'Praktische Tips',
    apiAccess: 'API-toegang', apiComingSoon: 'Binnenkort',
    apiDeveloper: 'REST API voor ontwikkelaars. Integreer deze tool in uw app.',
    trustedSources: 'Vertrouwde Bronnen & Methodologie',
    faqTitle: 'Veelgestelde Vragen',
    miaGreeting: 'Hallo! Ik ben Mia — jouw persoonlijke gezondheidscoach.',
    miaAskGoal: 'Waarmee kan ik je vandaag helpen? Vertel me over je probleem of doel.',
    miaGetStarted: 'Aan de slag →', miaFree: 'Gratis · Geen registratie', miaMeetBtn: 'Ontmoet Mia →',
    miaReviewedResults: 'Mia heeft jouw resultaten bekeken.',
    miaReviewedSub: (score: number) => `Ze analyseert al wat jouw score van ${score} punten specifiek voor jou betekent.`,
    quizFreeLabel: 'Gratis', quizQuestionsLabel: (n: number) => `${n} vragen`,
    quizPageTitle: 'Gratis Gezondheidstests', quizPageSubtitle: 'Eerlijke, wetenschappelijke tests — in minder dan 3 minuten. Geen registratie.', quizPageFooter: 'Alle tests zijn gratis. Resultaten blijven op uw apparaat. Geen account nodig.', quizClusterLabels: { weight: 'Gewicht', sleep: 'Slaap', mental: 'Geestelijke Gezondheid', lifestyle: 'Leefstijl', energy: 'Energie' } as Record<string, string>,
    miaTopicSleep: 'Slaapkwaliteit', miaTopicWeight: 'Gewichtsverlies', miaTopicStress: 'Stress', miaTopicEnergy: 'Energie',
    miaGenerating: (name: string) => `Mia bereidt jouw persoonlijke video voor${name ? `, ${name}` : ''}…`,
    miaGeneratingSub: 'Dit duurt meestal 1–2 minuten. Blijf op de pagina.',
    miaClusterSleep: 'slaapkwaliteit', miaClusterWeight: 'gewichtsverlies',
    miaPlanInMotion: (name: string) => `Jouw plan is in beweging${name ? `, ${name}` : ''}.`,
    miaPlanFooter: 'Mia heeft al jouw gegevens. Ze vergeet niet.',
    miaPlanItem1: (cluster: string) => `Jouw 7-daags protocol voor ${cluster} — morgen klaar`,
    miaPlanItem2: 'Gepersonaliseerde doelen op basis van jouw gegevens',
    miaPlanItem3: 'Dagelijkse check-in met Mia',
    miaRewatch: "Bekijk Mia's bericht opnieuw",
  },
}

export type UIStrings = typeof strings['en']
export type Lang = keyof typeof strings

export function t(lang: string): UIStrings {
  return strings[lang as Lang] ?? strings.en
}

export function tr(translations: Record<string, unknown>, path: string, fallback = ''): string {
  const parts = path.split('.')
  let cur: unknown = translations
  for (const p of parts) {
    if (cur == null || typeof cur !== 'object') return fallback
    cur = (cur as Record<string, unknown>)[p]
  }
  return typeof cur === 'string' ? cur : fallback
}

// ── Registration Prompt strings ───────────────────────────────────────────────

export interface RegistrationPromptStrings {
  title: string
  cta: string
  sub: string
  dismiss: string
}

const REGISTRATION_PROMPT_STRINGS: Record<string, RegistrationPromptStrings> = {
  en: { title: 'Save Your Progress',           cta: 'Create Free Account',          sub: 'No credit card · Takes 10 seconds', dismiss: 'Not now'        },
  uk: { title: 'Зберегти прогрес',             cta: 'Створити безкоштовний акаунт', sub: 'Без картки · 10 секунд',           dismiss: 'Пізніше'        },
  es: { title: 'Guardar tu progreso',           cta: 'Crear cuenta gratis',           sub: 'Sin tarjeta · 10 segundos',        dismiss: 'Ahora no'       },
  pt: { title: 'Salvar seu progresso',          cta: 'Criar conta grátis',            sub: 'Sem cartão · 10 segundos',         dismiss: 'Agora não'      },
  fr: { title: 'Sauvegarder votre progression', cta: 'Créer un compte gratuit',       sub: 'Sans carte · 10 secondes',         dismiss: 'Pas maintenant' },
  de: { title: 'Fortschritt speichern',         cta: 'Kostenloses Konto erstellen',   sub: 'Keine Karte · 10 Sekunden',        dismiss: 'Jetzt nicht'    },
  pl: { title: 'Zapisz postęp',                 cta: 'Utwórz darmowe konto',          sub: 'Bez karty · 10 sekund',            dismiss: 'Nie teraz'      },
  tr: { title: 'İlerlemeyi Kaydet',             cta: 'Ücretsiz Hesap Oluştur',        sub: 'Kart yok · 10 saniye',             dismiss: 'Şimdi değil'    },
  it: { title: 'Salva i tuoi progressi',        cta: 'Crea un account gratuito',      sub: 'Senza carta · 10 secondi',         dismiss: 'Non ora'        },
  nl: { title: 'Bewaar je voortgang',           cta: 'Maak gratis account',           sub: 'Geen kaart · 10 seconden',         dismiss: 'Niet nu'        },
}

export function getRegistrationPromptStrings(lang: string): RegistrationPromptStrings {
  return REGISTRATION_PROMPT_STRINGS[lang] ?? REGISTRATION_PROMPT_STRINGS['en']!
}
