// Auto-generated by CALCO Factory
import type { CalorieDeficitCalculatorInput, CalorieDeficitCalculatorOutput } from './types.js'

export function calculateCalorieDeficitCalculator(input: CalorieDeficitCalculatorInput): CalorieDeficitCalculatorOutput {
  const { currentWeight, targetWeight, tdee, weeklyLossGoal } = input
  const weeklyLossKg = parseFloat(weeklyLossGoal)
const dailyDeficit = Math.round(weeklyLossKg * 7700 / 7)
const dailyTarget = Math.max(1200, tdee - dailyDeficit)
const totalFatKg = Math.abs(currentWeight - targetWeight)
const totalDeficit = Math.round(totalFatKg * 7700)
const weeksToGoal = Math.round(totalDeficit / (dailyDeficit * 7))
return { dailyDeficit, dailyTarget, weeksToGoal, totalDeficit }
}
