// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface CalorieDeficitCalculatorInput {
  currentWeight: number
  targetWeight: number
  tdee: number
  weeklyLossGoal: '0.25' | '0.5' | '0.75' | '1.0'
}

export interface CalorieDeficitCalculatorOutput {
  dailyDeficit: number
  dailyTarget: number
  weeksToGoal: number
  totalDeficit: number
}
