// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { CalorieDeficitCalculatorInput } from './types.js'

export const calorieDeficitCalculatorSchema = z.object({
  currentWeight: z.number().min(30).max(300),
  targetWeight: z.number().min(30).max(300),
  tdee: z.number().min(800).max(6000),
  weeklyLossGoal: z.enum(['0.25', '0.5', '0.75', '1.0']),
})

export type { CalorieDeficitCalculatorInput }

export function validate(raw: unknown): CalorieDeficitCalculatorInput {
  return calorieDeficitCalculatorSchema.parse(raw) as CalorieDeficitCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: CalorieDeficitCalculatorInput } | { success: false; errors: string[] } {
  const result = calorieDeficitCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as CalorieDeficitCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
