// Auto-generated by CALCO Factory
import type { MortgageCalculatorOutput } from './lib/types.js'

export function getInterpretation(_output: MortgageCalculatorOutput, _lang = 'en'): string {
  return ''
}
