// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/mortgage-calculator`

  return {
    title: 'Mortgage Calculator — Monthly Payment & Amortization',
    description: 'Calculate your monthly mortgage payment, total interest, and amortization schedule. Includes property tax and insurance estimates.',
    canonical,
    ogImage: `https://solviqlab.com/og/mortgage-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/mortgage-calculator`,
      es: `https://solviqlab.com/es/mortgage-calculator`,
      pt: `https://solviqlab.com/pt/mortgage-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Mortgage Calculator — Monthly Payment & Amortization',
        description: 'Calculate your monthly mortgage payment, total interest, and amortization schedule. Includes property tax and insurance estimates.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Mortgage Calculator — Monthly Payment & Amortization',
        description: 'Calculate your monthly mortgage payment, total interest, and amortization schedule. Includes property tax and insurance estimates.',
        keywords: 'mortgage calculator',
        url: canonical,
      },
    ],
  }
}
