// Auto-generated by CALCO Factory
import type { LengthConverterOutput } from './lib/types.js'

export function getInterpretation(_output: LengthConverterOutput, _lang = 'en'): string {
  return ''
}
