// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/length-converter`

  return {
    title: 'Length Converter — Convert Any Unit of Length',
    description: 'Convert between meters, feet, inches, centimeters, kilometers, miles, and more. Instant length unit converter with 15+ units.',
    canonical,
    ogImage: `https://solviqlab.com/og/length-converter.png`,
    alternates: {
      en: `https://solviqlab.com/en/length-converter`,
      es: `https://solviqlab.com/es/length-converter`,
      pt: `https://solviqlab.com/pt/length-converter`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Length Converter — Convert Any Unit of Length',
        description: 'Convert between meters, feet, inches, centimeters, kilometers, miles, and more. Instant length unit converter with 15+ units.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Length Converter — Convert Any Unit of Length',
        description: 'Convert between meters, feet, inches, centimeters, kilometers, miles, and more. Instant length unit converter with 15+ units.',
        keywords: 'length converter',
        url: canonical,
      },
    ],
  }
}
