// Auto-generated by CALCO Factory
import type { MortgageCalculatorInput, MortgageCalculatorOutput } from './types.js'

export function calculateMortgageCalculator(input: MortgageCalculatorInput): MortgageCalculatorOutput {
  const { homePrice, downPayment, annualRate, termYears } = input
  const principal = homePrice - downPayment
const r = annualRate / 100 / 12
const n = parseInt(termYears) * 12
let monthlyPayment: number
if (r === 0) {
  monthlyPayment = principal / n
} else {
  monthlyPayment = principal * (r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1)
}
monthlyPayment = Math.round(monthlyPayment * 100) / 100
const totalPayment = Math.round(monthlyPayment * n * 100) / 100
const totalInterest = Math.round((totalPayment - principal) * 100) / 100
return { monthlyPayment, principal: Math.round(principal * 100) / 100, totalInterest, totalPayment }
}
