// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface MortgageCalculatorInput {
  homePrice: number
  downPayment: number
  annualRate: number
  termYears: '1' | '2' | '3' | '5' | '7' | '10' | '15' | '20' | '25' | '30'
}

export interface MortgageCalculatorOutput {
  monthlyPayment: number
  principal: number
  totalInterest: number
  totalPayment: number
}
