// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { MortgageCalculatorInput } from './types.js'

export const mortgageCalculatorSchema = z.object({
  homePrice: z.number().min(10_000).max(10_000_000),
  downPayment: z.number().min(0).max(10_000_000),
  annualRate: z.number().min(0).max(30),
  termYears: z.enum(['10', '15', '20', '25', '30']),
})

export type { MortgageCalculatorInput }

export function validate(raw: unknown): MortgageCalculatorInput {
  return mortgageCalculatorSchema.parse(raw) as MortgageCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: MortgageCalculatorInput } | { success: false; errors: string[] } {
  const result = mortgageCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as MortgageCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
