// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { AreaCalculatorInput } from './types.js'

export const areaCalculatorSchema = z.object({
  shape: z.enum(['rectangle', 'square', 'circle', 'triangle', 'trapezoid', 'ellipse']),
  a: z.number().min(0).max(1e9),
  b: z.number().min(0).max(1e9).optional(),
})

export type { AreaCalculatorInput }

export function validate(raw: unknown): AreaCalculatorInput {
  return areaCalculatorSchema.parse(raw) as AreaCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: AreaCalculatorInput } | { success: false; errors: string[] } {
  const result = areaCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as AreaCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
