// Auto-generated by CALCO Factory
import type { TdeeCalculatorInput, TdeeCalculatorOutput } from './types.js'

export function calculateTdeeCalculator(input: TdeeCalculatorInput): TdeeCalculatorOutput {
  const { weight, height, age, sex, activityLevel } = input
  const base = (10 * weight) + (6.25 * height) - (5 * age)
const bmr = Math.round(sex === 'male' ? base + 5 : base - 161)
const multipliers: Record<string, number> = {
  sedentary: 1.2, light: 1.375, moderate: 1.55, active: 1.725, very_active: 1.9
}
const tdee = Math.round(bmr * (multipliers[activityLevel] ?? 1.2))
return { bmr, tdee, weightLoss: tdee - 500, weightGain: tdee + 500 }
}
