// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface TdeeCalculatorInput {
  weight: number
  height: number
  age: number
  sex: 'male' | 'female'
  activityLevel: 'sedentary' | 'light' | 'moderate' | 'active' | 'very_active'
}

export interface TdeeCalculatorOutput {
  bmr: number
  tdee: number
  weightLoss: number
  weightGain: number
}
