// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { TdeeCalculatorInput } from './types.js'

export const tdeeCalculatorSchema = z.object({
  weight: z.number().min(20).max(300),
  height: z.number().min(100).max(250),
  age: z.number().min(15).max(100),
  sex: z.enum(['male', 'female']),
  activityLevel: z.enum(['sedentary', 'light', 'moderate', 'active', 'very_active']),
})

export type { TdeeCalculatorInput }

export function validate(raw: unknown): TdeeCalculatorInput {
  return tdeeCalculatorSchema.parse(raw) as TdeeCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: TdeeCalculatorInput } | { success: false; errors: string[] } {
  const result = tdeeCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as TdeeCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
