'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateAreaConverter } from '../../instruments/area-converter/lib/calculate.js'
import type { AreaConverterOutput } from '../../instruments/area-converter/lib/types.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function AreaConverterClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [value, setValue] = useState('')
  const [fromUnit, setFromUnit] = useState('m2')
  const [result, setResult] = useState<AreaConverterOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  function calculate() {
    try {
      const input = {
    value: parseFloat(value),
    fromUnit: fromUnit as 'm2' | 'km2' | 'cm2' | 'mm2' | 'ft2' | 'in2' | 'yd2' | 'mi2' | 'acre' | 'ha',
      }
      setResult(calculateAreaConverter(input as Parameters<typeof calculateAreaConverter>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setValue('')
    setFromUnit('m2')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_value') ?? 'Value'}
          </label>
          <input
            type="number"
            value={value}
            onChange={e => setValue(e.target.value)} min={0} max={1000000000000000}
            placeholder="Value"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_fromUnit') ?? 'From'}</label>
          <select
            value={fromUnit}
            onChange={e => setFromUnit(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option key="m2" value="m2">M2</option>
          <option key="km2" value="km2">Km2</option>
          <option key="cm2" value="cm2">Cm2</option>
          <option key="mm2" value="mm2">Mm2</option>
          <option key="ft2" value="ft2">Ft2</option>
          <option key="in2" value="in2">In2</option>
          <option key="yd2" value="yd2">Yd2</option>
          <option key="mi2" value="mi2">Mi2</option>
          <option key="acre" value="acre">Acre</option>
          <option key="ha" value="ha">Ha</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_squareMeters') ?? 'Square Meters'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.squareMeters === 'number' ? result.squareMeters.toLocaleString() : result.squareMeters}<span className="text-sm text-content-secondary"> m²</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_squareFeet') ?? 'Square Feet'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.squareFeet === 'number' ? result.squareFeet.toLocaleString() : result.squareFeet}<span className="text-sm text-content-secondary"> ft²</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_squareKilometers') ?? 'Square Kilometers'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.squareKilometers === 'number' ? result.squareKilometers.toLocaleString() : result.squareKilometers}<span className="text-sm text-content-secondary"> km²</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_acres') ?? 'Acres'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.acres === 'number' ? result.acres.toLocaleString() : result.acres}<span className="text-sm text-content-secondary"> ac</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_hectares') ?? 'Hectares'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.hectares === 'number' ? result.hectares.toLocaleString() : result.hectares}<span className="text-sm text-content-secondary"> ha</span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
