'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateAverageCalculator } from '../../instruments/average-calculator/lib/calculate.js'
import type { AverageCalculatorOutput } from '../../instruments/average-calculator/lib/types.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function AverageCalculatorClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [numbers, setNumbers] = useState('')
  const [result, setResult] = useState<AverageCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  function calculate() {
    try {
      const parsed = numbers.split(/[,;\s]+/).map(s => parseFloat(s.trim())).filter(n => !isNaN(n))
      if (parsed.length === 0) {
        setError(t('error_no_numbers') ?? 'Please enter at least one number, separated by commas.')
        setResult(null)
        return
      }
      setResult(calculateAverageCalculator({ numbers: parsed }))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setNumbers('')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_numbers') ?? 'Numbers (comma-separated)'}
          </label>
          <input
            type="text"
            inputMode="decimal"
            value={numbers}
            onChange={e => setNumbers(e.target.value)}
            placeholder="22, 1023442, 30192"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_mean') ?? 'Mean (Average)'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.mean === 'number' ? result.mean.toLocaleString() : result.mean}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_median') ?? 'Median'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.median === 'number' ? result.median.toLocaleString() : result.median}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_mode') ?? 'Mode'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.mode === 'number' ? result.mode.toLocaleString() : result.mode}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_range') ?? 'Range'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.range === 'number' ? result.range.toLocaleString() : result.range}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_count') ?? 'Count'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.count === 'number' ? result.count.toLocaleString() : result.count}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_sum') ?? 'Sum'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.sum === 'number' ? result.sum.toLocaleString() : result.sum}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
