'use client'
// Auto-generated by CALCO Factory
import { useState, useEffect } from 'react'
import { calculateCalorieDeficitCalculator } from '../../instruments/calorie-deficit-calculator/lib/calculate.js'
import type { CalorieDeficitCalculatorOutput } from '../../instruments/calorie-deficit-calculator/lib/types.js'
import { ShareButtons } from '../ShareButtons.js'
interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function CalorieDeficitCalculatorClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [currentWeight, setCurrentWeight] = useState('')
  const [targetWeight, setTargetWeight] = useState('')
  const [tdee, setTdee] = useState('')
  const [weeklyLossGoal, setWeeklyLossGoal] = useState('0.25')
  const [result, setResult] = useState<CalorieDeficitCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!result) return
    window.dispatchEvent(new CustomEvent('solviqlab:result', {
      detail: { slug: 'calorie-deficit-calculator', name: 'Calorie Deficit Calculator', value: result.dailyTarget, label: 'Daily Target', unit: 'kcal', metadata: result }
    }))
  }, [result])

  function calculate() {
    try {
      const input = {
    currentWeight: parseFloat(currentWeight),
    targetWeight: parseFloat(targetWeight),
    tdee: parseFloat(tdee),
    weeklyLossGoal: weeklyLossGoal as '0.25' | '0.5' | '0.75' | '1.0',
      }
      setResult(calculateCalorieDeficitCalculator(input as Parameters<typeof calculateCalorieDeficitCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setCurrentWeight('')
    setTargetWeight('')
    setTdee('')
    setWeeklyLossGoal('0.25')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_currentWeight') ?? 'Current Weight'} <span className="text-content-tertiary">(kg)</span>
          </label>
          <input
            type="number"
            value={currentWeight}
            onChange={e => setCurrentWeight(e.target.value)} min={30} max={300}
            placeholder="Current Weight"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_targetWeight') ?? 'Target Weight'} <span className="text-content-tertiary">(kg)</span>
          </label>
          <input
            type="number"
            value={targetWeight}
            onChange={e => setTargetWeight(e.target.value)} min={30} max={300}
            placeholder="Target Weight"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_tdee') ?? 'Daily Calorie Needs (TDEE)'} <span className="text-content-tertiary">(kcal)</span>
          </label>
          <input
            type="number"
            value={tdee}
            onChange={e => setTdee(e.target.value)} min={800} max={6000}
            placeholder="Daily Calorie Needs (TDEE)"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_weeklyLossGoal') ?? 'Weekly Loss Goal'}</label>
          <select
            value={weeklyLossGoal}
            onChange={e => setWeeklyLossGoal(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option value="0.25">{t('opt_loss_025') ?? '0.25 kg/week — Mild'}</option>
          <option value="0.5">{t('opt_loss_05') ?? '0.5 kg/week — Moderate'}</option>
          <option value="0.75">{t('opt_loss_075') ?? '0.75 kg/week — Fast'}</option>
          <option value="1.0">{t('opt_loss_10') ?? '1.0 kg/week — Aggressive'}</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_dailyDeficit') ?? 'Daily Calorie Deficit'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.dailyDeficit === 'number' ? result.dailyDeficit.toLocaleString() : result.dailyDeficit}<span className="text-sm text-content-secondary"> kcal</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_dailyTarget') ?? 'Daily Calorie Target'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.dailyTarget === 'number' ? result.dailyTarget.toLocaleString() : result.dailyTarget}<span className="text-sm text-content-secondary"> kcal</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_weeksToGoal') ?? 'Weeks to Goal'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.weeksToGoal === 'number' ? result.weeksToGoal.toLocaleString() : result.weeksToGoal}<span className="text-sm text-content-secondary"> weeks</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_totalDeficit') ?? 'Total Calorie Deficit Needed'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.totalDeficit === 'number' ? result.totalDeficit.toLocaleString() : result.totalDeficit}<span className="text-sm text-content-secondary"> kcal</span>
              </div>
            </div>
          </div>
          <ShareButtons text={`My daily calorie deficit: ${typeof result.dailyDeficit === 'number' ? result.dailyDeficit.toLocaleString() : result.dailyDeficit} kcal — calculated free at SolviqLab`} className="mt-4" />
        </div>
      )}
    </div>
  )
}
