'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateCompoundInterestCalculator } from '../../instruments/compound-interest-calculator/lib/calculate.js'
import type { CompoundInterestCalculatorOutput } from '../../instruments/compound-interest-calculator/lib/types.js'
import { CurrencySelector, useCurrency } from '../ui/CurrencySelector'
import { formatAmount } from '../../lib/currencies'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function CompoundInterestCalculatorClient({ translations, lang }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [principal, setPrincipal] = useState('')
  const [annualRate, setAnnualRate] = useState('')
  const [years, setYears] = useState('')
  const [monthlyContribution, setMonthlyContribution] = useState('')
  const [compoundFrequency, setCompoundFrequency] = useState('annually')
  const [result, setResult] = useState<CompoundInterestCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [currency, setCurrency] = useCurrency(lang)

  function calculate() {
    try {
      const input = {
    principal: parseFloat(principal),
    annualRate: parseFloat(annualRate),
    years: parseFloat(years),

    ...(monthlyContribution ? { monthlyContribution: parseFloat(monthlyContribution) } : {}),
    compoundFrequency: compoundFrequency as 'annually' | 'quarterly' | 'monthly' | 'daily',
      }
      setResult(calculateCompoundInterestCalculator(input as Parameters<typeof calculateCompoundInterestCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setPrincipal('')
    setAnnualRate('')
    setYears('')
    setMonthlyContribution('')
    setCompoundFrequency('annually')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-end mb-4">
        <CurrencySelector lang={lang} currency={currency} onChange={setCurrency} />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_principal') ?? 'Initial Investment'} <span className="text-content-tertiary">({currency.symbol})</span>
          </label>
          <input
            type="number"
            value={principal}
            onChange={e => setPrincipal(e.target.value)} min={0} max={100000000}
            placeholder="Initial Investment"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_annualRate') ?? 'Annual Interest Rate'} <span className="text-content-tertiary">(%)</span>
          </label>
          <input
            type="number"
            value={annualRate}
            onChange={e => setAnnualRate(e.target.value)} min={0} max={100}
            placeholder="Annual Interest Rate"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_years') ?? 'Time Period'} <span className="text-content-tertiary">({t('unit_years') ?? 'years'})</span>
          </label>
          <input
            type="number"
            value={years}
            onChange={e => setYears(e.target.value)} min={1} max={100}
            placeholder="Time Period"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_monthlyContribution') ?? 'Monthly Contribution'} <span className="text-content-tertiary">({currency.symbol})</span>
          </label>
          <input
            type="number"
            value={monthlyContribution}
            onChange={e => setMonthlyContribution(e.target.value)} min={0} max={1000000}
            placeholder="Monthly Contribution"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_compoundFrequency') ?? 'Compound Frequency'}</label>
          <select
            value={compoundFrequency}
            onChange={e => setCompoundFrequency(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option value="annually">{t('freq_annually') ?? 'Annually'}</option>
          <option value="quarterly">{t('freq_quarterly') ?? 'Quarterly'}</option>
          <option value="monthly">{t('freq_monthly') ?? 'Monthly'}</option>
          <option value="daily">{t('freq_daily') ?? 'Daily'}</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_finalAmount') ?? 'Final Amount'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.finalAmount as number, currency, lang)}
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_totalContributions') ?? 'Total Contributions'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.totalContributions as number, currency, lang)}
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_totalInterest') ?? 'Total Interest Earned'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.totalInterest as number, currency, lang)}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
