'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateDiscountCalculator } from '../../instruments/discount-calculator/lib/calculate.js'
import type { DiscountCalculatorOutput } from '../../instruments/discount-calculator/lib/types.js'
import { CurrencySelector, useCurrency } from '../ui/CurrencySelector'
import { formatAmount } from '../../lib/currencies'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function DiscountCalculatorClient({ translations, lang }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [originalPrice, setOriginalPrice] = useState('')
  const [discountPercent, setDiscountPercent] = useState('')
  const [result, setResult] = useState<DiscountCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [currency, setCurrency] = useCurrency(lang)

  function calculate() {
    try {
      const input = {
    originalPrice: parseFloat(originalPrice),
    discountPercent: parseFloat(discountPercent),
      }
      setResult(calculateDiscountCalculator(input as Parameters<typeof calculateDiscountCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setOriginalPrice('')
    setDiscountPercent('')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-end mb-4">
        <CurrencySelector lang={lang} currency={currency} onChange={setCurrency} />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_originalPrice') ?? 'Original Price'} <span className="text-content-tertiary">({currency.symbol})</span>
          </label>
          <input
            type="number"
            value={originalPrice}
            onChange={e => setOriginalPrice(e.target.value)} min={0} max={1000000000}
            placeholder="Original Price"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_discountPercent') ?? 'Discount'} <span className="text-content-tertiary">(%)</span>
          </label>
          <input
            type="number"
            value={discountPercent}
            onChange={e => setDiscountPercent(e.target.value)} min={0} max={100}
            placeholder="Discount"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_discountAmount') ?? 'You Save'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.discountAmount as number, currency, lang)}
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_finalPrice') ?? 'Final Price'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.finalPrice as number, currency, lang)}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
