'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateFractionCalculator } from '../../instruments/fraction-calculator/lib/calculate.js'
import type { FractionCalculatorOutput } from '../../instruments/fraction-calculator/lib/types.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function FractionCalculatorClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [numerator1, setNumerator1] = useState('')
  const [denominator1, setDenominator1] = useState('')
  const [operation, setOperation] = useState('add')
  const [numerator2, setNumerator2] = useState('')
  const [denominator2, setDenominator2] = useState('')
  const [result, setResult] = useState<FractionCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  function calculate() {
    try {
      const input = {
    numerator1: parseFloat(numerator1),
    denominator1: parseFloat(denominator1),
    operation: operation as 'add' | 'subtract' | 'multiply' | 'divide',
    numerator2: parseFloat(numerator2),
    denominator2: parseFloat(denominator2),
      }
      setResult(calculateFractionCalculator(input as Parameters<typeof calculateFractionCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setNumerator1('')
    setDenominator1('')
    setOperation('add')
    setNumerator2('')
    setDenominator2('')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_numerator1') ?? 'Numerator 1'}
          </label>
          <input
            type="number"
            value={numerator1}
            onChange={e => setNumerator1(e.target.value)} min={-10000} max={10000}
            placeholder="Numerator 1"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_denominator1') ?? 'Denominator 1'}
          </label>
          <input
            type="number"
            value={denominator1}
            onChange={e => setDenominator1(e.target.value)} min={-10000} max={10000}
            placeholder="Denominator 1"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_operation') ?? 'Operation'}</label>
          <select
            value={operation}
            onChange={e => setOperation(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option value="add">{t('opt_add') ?? 'Add'}</option>
          <option value="subtract">{t('opt_subtract') ?? 'Subtract'}</option>
          <option value="multiply">{t('opt_multiply') ?? 'Multiply'}</option>
          <option value="divide">{t('opt_divide') ?? 'Divide'}</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_numerator2') ?? 'Numerator 2'}
          </label>
          <input
            type="number"
            value={numerator2}
            onChange={e => setNumerator2(e.target.value)} min={-10000} max={10000}
            placeholder="Numerator 2"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_denominator2') ?? 'Denominator 2'}
          </label>
          <input
            type="number"
            value={denominator2}
            onChange={e => setDenominator2(e.target.value)} min={-10000} max={10000}
            placeholder="Denominator 2"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_resultNumerator') ?? 'Result Numerator'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.resultNumerator === 'number' ? result.resultNumerator.toLocaleString() : result.resultNumerator}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_resultDenominator') ?? 'Result Denominator'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.resultDenominator === 'number' ? result.resultDenominator.toLocaleString() : result.resultDenominator}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_decimal') ?? 'Decimal'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.decimal === 'number' ? result.decimal.toLocaleString() : result.decimal}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
