'use client'
// Auto-generated by CALCO Factory
import { useState, useEffect } from 'react'
import { calculateIdealWeightCalculator } from '../../instruments/ideal-weight-calculator/lib/calculate.js'
import type { IdealWeightCalculatorOutput } from '../../instruments/ideal-weight-calculator/lib/types.js'
import { ShareButtons } from '../ShareButtons.js'
interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function IdealWeightCalculatorClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [height, setHeight] = useState('')
  const [sex, setSex] = useState('male')
  const [result, setResult] = useState<IdealWeightCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!result) return
    window.dispatchEvent(new CustomEvent('solviqlab:result', {
      detail: { slug: 'ideal-weight-calculator', name: 'Ideal Weight Calculator', value: result.average, label: 'Ideal Weight', unit: 'kg', metadata: result }
    }))
  }, [result])

  function calculate() {
    try {
      const input = {
    height: parseFloat(height),
    sex: sex as 'male' | 'female',
      }
      setResult(calculateIdealWeightCalculator(input as Parameters<typeof calculateIdealWeightCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setHeight('')
    setSex('male')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_height') ?? 'Height'} <span className="text-content-tertiary">(cm)</span>
          </label>
          <input
            type="number"
            value={height}
            onChange={e => setHeight(e.target.value)} min={100} max={250}
            placeholder="Height"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_sex') ?? 'Sex'}</label>
          <select
            value={sex}
            onChange={e => setSex(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option value="male">{t('opt_male') ?? 'Male'}</option>
          <option value="female">{t('opt_female') ?? 'Female'}</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_robinson') ?? 'Robinson Formula'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.robinson === 'number' ? result.robinson.toLocaleString() : result.robinson}<span className="text-sm text-content-secondary"> kg</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_miller') ?? 'Miller Formula'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.miller === 'number' ? result.miller.toLocaleString() : result.miller}<span className="text-sm text-content-secondary"> kg</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_devine') ?? 'Devine Formula'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.devine === 'number' ? result.devine.toLocaleString() : result.devine}<span className="text-sm text-content-secondary"> kg</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_average') ?? 'Average Ideal Weight'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.average === 'number' ? result.average.toLocaleString() : result.average}<span className="text-sm text-content-secondary"> kg</span>
              </div>
            </div>
          </div>
          <ShareButtons text={`My ideal weight: ${typeof result.average === 'number' ? result.average.toLocaleString() : result.average} kg — calculated free at SolviqLab`} className="mt-4" />
        </div>
      )}
    </div>
  )
}
