'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateLengthConverter } from '../../instruments/length-converter/lib/calculate.js'
import type { LengthConverterOutput } from '../../instruments/length-converter/lib/types.js'
import { ShareButtons } from '../ShareButtons.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function LengthConverterClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [value, setValue] = useState('')
  const [fromUnit, setFromUnit] = useState('m')
  const [result, setResult] = useState<LengthConverterOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  function calculate() {
    try {
      const input = {
    value: parseFloat(value),
    fromUnit: fromUnit as 'm' | 'km' | 'cm' | 'mm' | 'ft' | 'in' | 'yd' | 'mi' | 'nm' | 'μm',
      }
      setResult(calculateLengthConverter(input as Parameters<typeof calculateLengthConverter>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setValue('')
    setFromUnit('m')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_value') ?? 'Value'}
          </label>
          <input
            type="number"
            value={value}
            onChange={e => setValue(e.target.value)} min={0} max={1000000000000000}
            placeholder="Value"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_fromUnit') ?? 'From'}</label>
          <select
            value={fromUnit}
            onChange={e => setFromUnit(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option key="m" value="m">M</option>
          <option key="km" value="km">Km</option>
          <option key="cm" value="cm">Cm</option>
          <option key="mm" value="mm">Mm</option>
          <option key="ft" value="ft">Ft</option>
          <option key="in" value="in">In</option>
          <option key="yd" value="yd">Yd</option>
          <option key="mi" value="mi">Mi</option>
          <option key="nm" value="nm">Nm</option>
          <option key="μm" value="μm">Μm</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_meters') ?? 'Meters'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.meters === 'number' ? result.meters.toLocaleString() : result.meters}<span className="text-sm text-content-secondary"> m</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_kilometers') ?? 'Kilometers'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.kilometers === 'number' ? result.kilometers.toLocaleString() : result.kilometers}<span className="text-sm text-content-secondary"> km</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_centimeters') ?? 'Centimeters'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.centimeters === 'number' ? result.centimeters.toLocaleString() : result.centimeters}<span className="text-sm text-content-secondary"> cm</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_feet') ?? 'Feet'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.feet === 'number' ? result.feet.toLocaleString() : result.feet}<span className="text-sm text-content-secondary"> ft</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_inches') ?? 'Inches'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.inches === 'number' ? result.inches.toLocaleString() : result.inches}<span className="text-sm text-content-secondary"> in</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_miles') ?? 'Miles'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.miles === 'number' ? result.miles.toLocaleString() : result.miles}<span className="text-sm text-content-secondary"> mi</span>
              </div>
            </div>
          </div>
          <ShareButtons text={`${result.meters} m = ${result.feet} ft = ${result.kilometers} km — converted free at SolviqLab`} className="mt-4" />
        </div>
      )}
    </div>
  )
}
