'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateLoanCalculator } from '../../instruments/loan-calculator/lib/calculate.js'
import type { LoanCalculatorOutput } from '../../instruments/loan-calculator/lib/types.js'
import { CurrencySelector, useCurrency } from '../ui/CurrencySelector'
import { formatAmount } from '../../lib/currencies'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function LoanCalculatorClient({ translations, lang }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [principal, setPrincipal] = useState('')
  const [annualRate, setAnnualRate] = useState('')
  const [termMonths, setTermMonths] = useState('')
  const [result, setResult] = useState<LoanCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [currency, setCurrency] = useCurrency(lang)

  function calculate() {
    try {
      const input = {
    principal: parseFloat(principal),
    annualRate: parseFloat(annualRate),
    termMonths: parseFloat(termMonths),
      }
      setResult(calculateLoanCalculator(input as Parameters<typeof calculateLoanCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setPrincipal('')
    setAnnualRate('')
    setTermMonths('')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-end mb-4">
        <CurrencySelector lang={lang} currency={currency} onChange={setCurrency} />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_principal') ?? 'Loan Amount'} <span className="text-content-tertiary">({currency.symbol})</span>
          </label>
          <input
            type="number"
            value={principal}
            onChange={e => setPrincipal(e.target.value)} min={100} max={10000000}
            placeholder="Loan Amount"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_annualRate') ?? 'Annual Interest Rate'} <span className="text-content-tertiary">(%)</span>
          </label>
          <input
            type="number"
            value={annualRate}
            onChange={e => setAnnualRate(e.target.value)} min={0} max={50}
            placeholder="Annual Interest Rate"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_termMonths') ?? 'Loan Term'} <span className="text-content-tertiary">(months)</span>
          </label>
          <input
            type="number"
            value={termMonths}
            onChange={e => setTermMonths(e.target.value)} min={1} max={600}
            placeholder="Loan Term"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_monthlyPayment') ?? 'Monthly Payment'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.monthlyPayment as number, currency, lang)}
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_totalPayment') ?? 'Total Payment'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.totalPayment as number, currency, lang)}
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_totalInterest') ?? 'Total Interest'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.totalInterest as number, currency, lang)}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
