'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateMortgageCalculator } from '../../instruments/mortgage-calculator/lib/calculate.js'
import type { MortgageCalculatorOutput } from '../../instruments/mortgage-calculator/lib/types.js'
import { CurrencySelector, useCurrency } from '../ui/CurrencySelector'
import { formatAmount } from '../../lib/currencies'
import { ShareButtons } from '../ShareButtons.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function MortgageCalculatorClient({ translations, lang }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [homePrice, setHomePrice] = useState('')
  const [downPayment, setDownPayment] = useState('')
  const [annualRate, setAnnualRate] = useState('')
  const [termYears, setTermYears] = useState('30')
  const [result, setResult] = useState<MortgageCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [currency, setCurrency] = useCurrency(lang)

  function calculate() {
    try {
      const input = {
    homePrice: parseFloat(homePrice),
    downPayment: parseFloat(downPayment),
    annualRate: parseFloat(annualRate),
    termYears: termYears as '1' | '2' | '3' | '5' | '7' | '10' | '15' | '20' | '25' | '30',
      }
      setResult(calculateMortgageCalculator(input as Parameters<typeof calculateMortgageCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setHomePrice('')
    setDownPayment('')
    setAnnualRate('')
    setTermYears('30')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-end mb-4">
        <CurrencySelector lang={lang} currency={currency} onChange={setCurrency} />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_homePrice') ?? 'Home Price'} <span className="text-content-tertiary">({currency.symbol})</span>
          </label>
          <input
            type="number"
            value={homePrice}
            onChange={e => setHomePrice(e.target.value)} min={10000} max={10000000}
            placeholder="Home Price"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_downPayment') ?? 'Down Payment'} <span className="text-content-tertiary">({currency.symbol})</span>
          </label>
          <input
            type="number"
            value={downPayment}
            onChange={e => setDownPayment(e.target.value)} min={0} max={10000000}
            placeholder="Down Payment"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_annualRate') ?? 'Interest Rate'} <span className="text-content-tertiary">(%)</span>
          </label>
          <input
            type="number"
            value={annualRate}
            onChange={e => setAnnualRate(e.target.value)} min={0} max={30}
            placeholder="Interest Rate"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_termYears') ?? 'Loan Term'}</label>
          <select
            value={termYears}
            onChange={e => setTermYears(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option value="1">1 {t('unit_years') ?? 'year'}</option>
          <option value="2">2 {t('unit_years') ?? 'years'}</option>
          <option value="3">3 {t('unit_years') ?? 'years'}</option>
          <option value="5">5 {t('unit_years') ?? 'years'}</option>
          <option value="7">7 {t('unit_years') ?? 'years'}</option>
          <option value="10">10 {t('unit_years') ?? 'years'}</option>
          <option value="15">15 {t('unit_years') ?? 'years'}</option>
          <option value="20">20 {t('unit_years') ?? 'years'}</option>
          <option value="25">25 {t('unit_years') ?? 'years'}</option>
          <option value="30">30 {t('unit_years') ?? 'years'}</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_monthlyPayment') ?? 'Monthly Payment'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.monthlyPayment as number, currency, lang)}
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_principal') ?? 'Loan Amount'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.principal as number, currency, lang)}
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_totalInterest') ?? 'Total Interest'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.totalInterest as number, currency, lang)}
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_totalPayment') ?? 'Total Cost'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.totalPayment as number, currency, lang)}
              </div>
            </div>
          </div>
          <ShareButtons text={`My monthly mortgage payment: ${formatAmount(result.monthlyPayment as number, currency, lang)} — calculated free at SolviqLab`} className="mt-4" />
        </div>
      )}
    </div>
  )
}
