'use client'
// Auto-generated by CALCO Factory
import { useState, useEffect } from 'react'
import { calculateRatioCalculator } from '../../instruments/ratio-calculator/lib/calculate.js'
import type { RatioCalculatorOutput } from '../../instruments/ratio-calculator/lib/types.js'
import { ShareButtons } from '../ShareButtons.js'
interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function RatioCalculatorClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [a, setA] = useState('')
  const [b, setB] = useState('')
  const [c, setC] = useState('')
  const [result, setResult] = useState<RatioCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!result) return
    window.dispatchEvent(new CustomEvent('solviqlab:result', {
      detail: { slug: 'ratio-calculator', name: 'Ratio Calculator', value: result.decimal, label: 'Ratio', unit: '', metadata: result }
    }))
  }, [result])

  function calculate() {
    try {
      const input = {
    a: parseFloat(a),
    b: parseFloat(b),

    ...(c ? { c: parseFloat(c) } : {}),
      }
      setResult(calculateRatioCalculator(input as Parameters<typeof calculateRatioCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setA('')
    setB('')
    setC('')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_a') ?? 'A'}
          </label>
          <input
            type="number"
            value={a}
            onChange={e => setA(e.target.value)} min={-1000000000} max={1000000000}
            placeholder="A"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_b') ?? 'B'}
          </label>
          <input
            type="number"
            value={b}
            onChange={e => setB(e.target.value)} min={-1000000000} max={1000000000}
            placeholder="B"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_c') ?? 'C (optional, solve for D)'}
          </label>
          <input
            type="number"
            value={c}
            onChange={e => setC(e.target.value)} min={-1000000000} max={1000000000}
            placeholder="C (optional, solve for D)"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_simplifiedA') ?? 'Simplified A'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.simplifiedA === 'number' ? result.simplifiedA.toLocaleString() : result.simplifiedA}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_simplifiedB') ?? 'Simplified B'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.simplifiedB === 'number' ? result.simplifiedB.toLocaleString() : result.simplifiedB}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_d') ?? 'D (if C given)'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.d === 'number' ? result.d.toLocaleString() : result.d}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_decimal') ?? 'A/B as decimal'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.decimal === 'number' ? result.decimal.toLocaleString() : result.decimal}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
          </div>
          <ShareButtons text={`My simplified ratio: ${result.simplifiedA}:${result.simplifiedB} — calculated free at SolviqLab`} className="mt-4" />
        </div>
      )}
    </div>
  )
}
