'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateScientificNotationCalculator } from '../../instruments/scientific-notation-calculator/lib/calculate.js'
import type { ScientificNotationCalculatorOutput } from '../../instruments/scientific-notation-calculator/lib/types.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function ScientificNotationCalculatorClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [value, setValue] = useState('')
  const [result, setResult] = useState<ScientificNotationCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  function calculate() {
    try {
      const input = {
    value: parseFloat(value),
      }
      setResult(calculateScientificNotationCalculator(input as Parameters<typeof calculateScientificNotationCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setValue('')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_value') ?? 'Number'}
          </label>
          <input
            type="number"
            value={value}
            onChange={e => setValue(e.target.value)} min={-1e+300} max={1e+300}
            placeholder="Number"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_coefficient') ?? 'Coefficient'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.coefficient === 'number' ? result.coefficient.toLocaleString() : result.coefficient}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_exponent') ?? 'Exponent (power of 10)'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.exponent === 'number' ? result.exponent.toLocaleString() : result.exponent}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_scientific') ?? 'Scientific Notation'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.scientific === 'number' ? result.scientific.toLocaleString() : result.scientific}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_engineering') ?? 'Engineering Notation'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.engineering === 'number' ? result.engineering.toLocaleString() : result.engineering}<span className="text-sm text-content-secondary"></span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
