'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateTdeeCalculator } from '../../instruments/tdee-calculator/lib/calculate.js'
import type { TdeeCalculatorOutput } from '../../instruments/tdee-calculator/lib/types.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function TdeeCalculatorClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [weight, setWeight] = useState('')
  const [height, setHeight] = useState('')
  const [age, setAge] = useState('')
  const [sex, setSex] = useState('male')
  const [activityLevel, setActivityLevel] = useState('sedentary')
  const [result, setResult] = useState<TdeeCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  function calculate() {
    try {
      const input = {
    weight: parseFloat(weight),
    height: parseFloat(height),
    age: parseFloat(age),
    sex: sex as 'male' | 'female',
    activityLevel: activityLevel as 'sedentary' | 'light' | 'moderate' | 'active' | 'very_active',
      }
      setResult(calculateTdeeCalculator(input as Parameters<typeof calculateTdeeCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setWeight('')
    setHeight('')
    setAge('')
    setSex('male')
    setActivityLevel('sedentary')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_weight') ?? 'Weight'} <span className="text-content-tertiary">(kg)</span>
          </label>
          <input
            type="number"
            value={weight}
            onChange={e => setWeight(e.target.value)} min={20} max={300}
            placeholder="Weight"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_height') ?? 'Height'} <span className="text-content-tertiary">(cm)</span>
          </label>
          <input
            type="number"
            value={height}
            onChange={e => setHeight(e.target.value)} min={100} max={250}
            placeholder="Height"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_age') ?? 'Age'} <span className="text-content-tertiary">(years)</span>
          </label>
          <input
            type="number"
            value={age}
            onChange={e => setAge(e.target.value)} min={15} max={100}
            placeholder="Age"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_sex') ?? 'Sex'}</label>
          <select
            value={sex}
            onChange={e => setSex(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option value="male">{t('opt_male') ?? 'Male'}</option>
          <option value="female">{t('opt_female') ?? 'Female'}</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_activityLevel') ?? 'Activity Level'}</label>
          <select
            value={activityLevel}
            onChange={e => setActivityLevel(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option value="sedentary">{t('opt_sedentary') ?? 'Sedentary'}</option>
          <option value="light">{t('opt_light') ?? 'Lightly active'}</option>
          <option value="moderate">{t('opt_moderate') ?? 'Moderately active'}</option>
          <option value="active">{t('opt_active') ?? 'Very active'}</option>
          <option value="very_active">{t('opt_very_active') ?? 'Extremely active'}</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_bmr') ?? 'BMR'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.bmr === 'number' ? result.bmr.toLocaleString() : result.bmr}<span className="text-sm text-content-secondary"> kcal/day</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_tdee') ?? 'TDEE'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.tdee === 'number' ? result.tdee.toLocaleString() : result.tdee}<span className="text-sm text-content-secondary"> kcal/day</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_weightLoss') ?? 'Weight Loss Target'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.weightLoss === 'number' ? result.weightLoss.toLocaleString() : result.weightLoss}<span className="text-sm text-content-secondary"> kcal/day</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_weightGain') ?? 'Weight Gain Target'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.weightGain === 'number' ? result.weightGain.toLocaleString() : result.weightGain}<span className="text-sm text-content-secondary"> kcal/day</span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
