'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateTemperatureConverter } from '../../instruments/temperature-converter/lib/calculate.js'
import type { TemperatureConverterOutput } from '../../instruments/temperature-converter/lib/types.js'
import { ShareButtons } from '../ShareButtons.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function TemperatureConverterClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [value, setValue] = useState('')
  const [fromUnit, setFromUnit] = useState('C')
  const [result, setResult] = useState<TemperatureConverterOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  function calculate() {
    try {
      const input = {
    value: parseFloat(value),
    fromUnit: fromUnit as 'C' | 'F' | 'K' | 'R',
      }
      setResult(calculateTemperatureConverter(input as Parameters<typeof calculateTemperatureConverter>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setValue('')
    setFromUnit('C')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_value') ?? 'Temperature'}
          </label>
          <input
            type="number"
            value={value}
            onChange={e => setValue(e.target.value)} min={-1000} max={100000}
            placeholder="Temperature"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_fromUnit') ?? 'From'}</label>
          <select
            value={fromUnit}
            onChange={e => setFromUnit(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option key="C" value="C">C</option>
          <option key="F" value="F">F</option>
          <option key="K" value="K">K</option>
          <option key="R" value="R">R</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_celsius') ?? 'Celsius'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.celsius === 'number' ? result.celsius.toLocaleString() : result.celsius}<span className="text-sm text-content-secondary"> °C</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_fahrenheit') ?? 'Fahrenheit'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.fahrenheit === 'number' ? result.fahrenheit.toLocaleString() : result.fahrenheit}<span className="text-sm text-content-secondary"> °F</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_kelvin') ?? 'Kelvin'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.kelvin === 'number' ? result.kelvin.toLocaleString() : result.kelvin}<span className="text-sm text-content-secondary"> K</span>
              </div>
            </div>
          </div>
          <ShareButtons text={`${result.celsius}°C = ${result.fahrenheit}°F = ${result.kelvin}K — converted free at SolviqLab`} className="mt-4" />
        </div>
      )}
    </div>
  )
}
