'use client'
// Auto-generated by CALCO Factory
import { useState, useEffect } from 'react'
import { calculateVatCalculator } from '../../instruments/vat-calculator/lib/calculate.js'
import type { VatCalculatorOutput } from '../../instruments/vat-calculator/lib/types.js'
import { CurrencySelector, useCurrency } from '../ui/CurrencySelector'
import { formatAmount } from '../../lib/currencies'
import { ShareButtons } from '../ShareButtons.js'
interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function VatCalculatorClient({ translations, lang }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [amount, setAmount] = useState('')
  const [vatRate, setVatRate] = useState('')
  const [mode, setMode] = useState('add')
  const [result, setResult] = useState<VatCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [currency, setCurrency] = useCurrency(lang)

  useEffect(() => {
    if (!result) return
    window.dispatchEvent(new CustomEvent('solviqlab:result', {
      detail: { slug: 'vat-calculator', name: 'VAT Calculator', value: result.vatAmount, label: 'VAT Amount', unit: '', metadata: result }
    }))
  }, [result])

  function calculate() {
    try {
      const input = {
    amount: parseFloat(amount),
    vatRate: parseFloat(vatRate),
    mode: mode as 'add' | 'remove',
      }
      setResult(calculateVatCalculator(input as Parameters<typeof calculateVatCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setAmount('')
    setVatRate('')
    setMode('add')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-end mb-4">
        <CurrencySelector lang={lang} currency={currency} onChange={setCurrency} />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_amount') ?? 'Amount'} <span className="text-content-tertiary">({currency.symbol})</span>
          </label>
          <input
            type="number"
            value={amount}
            onChange={e => setAmount(e.target.value)} min={0} max={1000000000}
            placeholder="Amount"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_vatRate') ?? 'VAT Rate'} <span className="text-content-tertiary">(%)</span>
          </label>
          <input
            type="number"
            value={vatRate}
            onChange={e => setVatRate(e.target.value)} min={0} max={100}
            placeholder="VAT Rate"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_mode') ?? 'Mode'}</label>
          <select
            value={mode}
            onChange={e => setMode(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option value="add">{t('opt_add') ?? 'Add VAT'}</option>
          <option value="remove">{t('opt_remove') ?? 'Remove VAT'}</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_netAmount') ?? 'Net Amount (excl. VAT)'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.netAmount as number, currency, lang)}
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_vatAmount') ?? 'VAT Amount'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.vatAmount as number, currency, lang)}
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_grossAmount') ?? 'Gross Amount (incl. VAT)'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {formatAmount(result.grossAmount as number, currency, lang)}
              </div>
            </div>
          </div>
          <ShareButtons text={`VAT amount: ${formatAmount(result.vatAmount as number, currency, lang)} (gross: ${formatAmount(result.grossAmount as number, currency, lang)}) — calculated free at SolviqLab`} className="mt-4" />
        </div>
      )}
    </div>
  )
}
