'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateVolumeConverter } from '../../instruments/volume-converter/lib/calculate.js'
import type { VolumeConverterOutput } from '../../instruments/volume-converter/lib/types.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function VolumeConverterClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [value, setValue] = useState('')
  const [fromUnit, setFromUnit] = useState('l')
  const [result, setResult] = useState<VolumeConverterOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  function calculate() {
    try {
      const input = {
    value: parseFloat(value),
    fromUnit: fromUnit as 'l' | 'ml' | 'cl' | 'm3' | 'cm3' | 'gal' | 'qt' | 'pt' | 'cup' | 'floz' | 'tbsp' | 'tsp' | 'ft3' | 'in3',
      }
      setResult(calculateVolumeConverter(input as Parameters<typeof calculateVolumeConverter>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setValue('')
    setFromUnit('l')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_value') ?? 'Value'}
          </label>
          <input
            type="number"
            value={value}
            onChange={e => setValue(e.target.value)} min={0} max={1000000000000}
            placeholder="Value"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_fromUnit') ?? 'From'}</label>
          <select
            value={fromUnit}
            onChange={e => setFromUnit(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option key="l" value="l">L</option>
          <option key="ml" value="ml">Ml</option>
          <option key="cl" value="cl">Cl</option>
          <option key="m3" value="m3">M3</option>
          <option key="cm3" value="cm3">Cm3</option>
          <option key="gal" value="gal">Gal</option>
          <option key="qt" value="qt">Qt</option>
          <option key="pt" value="pt">Pt</option>
          <option key="cup" value="cup">Cup</option>
          <option key="floz" value="floz">Floz</option>
          <option key="tbsp" value="tbsp">Tbsp</option>
          <option key="tsp" value="tsp">Tsp</option>
          <option key="ft3" value="ft3">Ft3</option>
          <option key="in3" value="in3">In3</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_liters') ?? 'Liters'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.liters === 'number' ? result.liters.toLocaleString() : result.liters}<span className="text-sm text-content-secondary"> L</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_milliliters') ?? 'Milliliters'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.milliliters === 'number' ? result.milliliters.toLocaleString() : result.milliliters}<span className="text-sm text-content-secondary"> mL</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_gallons') ?? 'US Gallons'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.gallons === 'number' ? result.gallons.toLocaleString() : result.gallons}<span className="text-sm text-content-secondary"> gal</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_cups') ?? 'Cups'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.cups === 'number' ? result.cups.toLocaleString() : result.cups}<span className="text-sm text-content-secondary"> cups</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_fluidOunces') ?? 'Fluid Ounces'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.fluidOunces === 'number' ? result.fluidOunces.toLocaleString() : result.fluidOunces}<span className="text-sm text-content-secondary"> fl oz</span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
