'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateVolumeCalculator } from '../../instruments/volume-calculator/lib/calculate.js'
import type { VolumeCalculatorOutput } from '../../instruments/volume-calculator/lib/types.js'
import { ShareButtons } from '../ShareButtons.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function VolumeCalculatorClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [shape, setShape] = useState('cube')
  const [a, setA] = useState('')
  const [b, setB] = useState('')
  const [h, setH] = useState('')
  const [result, setResult] = useState<VolumeCalculatorOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  function calculate() {
    try {
      const input = {
    shape: shape as 'cube' | 'sphere' | 'cylinder' | 'cone' | 'rectangular_prism',
    a: parseFloat(a),

    ...(b ? { b: parseFloat(b) } : {}),

    ...(h ? { h: parseFloat(h) } : {}),
      }
      setResult(calculateVolumeCalculator(input as Parameters<typeof calculateVolumeCalculator>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setShape('cube')
    setA('')
    setB('')
    setH('')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_shape') ?? 'Shape'}</label>
          <select
            value={shape}
            onChange={e => setShape(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option value="cube">{t('opt_cube') ?? 'Cube'}</option>
          <option value="sphere">{t('opt_sphere') ?? 'Sphere'}</option>
          <option value="cylinder">{t('opt_cylinder') ?? 'Cylinder'}</option>
          <option value="cone">{t('opt_cone') ?? 'Cone'}</option>
          <option value="rectangular_prism">{t('opt_rect_prism') ?? 'Rectangular Prism'}</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_a') ?? 'Length / Radius / Side'}
          </label>
          <input
            type="number"
            value={a}
            onChange={e => setA(e.target.value)} min={0} max={1000000000}
            placeholder="Length / Radius / Side"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_b') ?? 'Width (if needed)'}
          </label>
          <input
            type="number"
            value={b}
            onChange={e => setB(e.target.value)} min={0} max={1000000000}
            placeholder="Width (if needed)"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_h') ?? 'Height (if needed)'}
          </label>
          <input
            type="number"
            value={h}
            onChange={e => setH(e.target.value)} min={0} max={1000000000}
            placeholder="Height (if needed)"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_volume') ?? 'Volume'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.volume === 'number' ? result.volume.toLocaleString() : result.volume}<span className="text-sm text-content-secondary"> units³</span>
              </div>
            </div>
          </div>
          <ShareButtons text={`Volume: ${result.volume.toLocaleString()} — calculated free at SolviqLab`} className="mt-4" />
        </div>
      )}
    </div>
  )
}
