'use client'
// Auto-generated by CALCO Factory
import { useState } from 'react'
import { calculateWeightConverter } from '../../instruments/weight-converter/lib/calculate.js'
import type { WeightConverterOutput } from '../../instruments/weight-converter/lib/types.js'
import { ShareButtons } from '../ShareButtons.js'

interface Props {
  translations: Record<string, unknown>
  lang: string
}

export function WeightConverterClient({ translations }: Props) {
  const t = (key: string) => translations[key] as string | undefined

  const [value, setValue] = useState('')
  const [fromUnit, setFromUnit] = useState('kg')
  const [result, setResult] = useState<WeightConverterOutput | null>(null)
  const [error, setError] = useState<string | null>(null)

  function calculate() {
    try {
      const input = {
    value: parseFloat(value),
    fromUnit: fromUnit as 'kg' | 'g' | 'mg' | 'lb' | 'oz' | 'st' | 't' | 'ton',
      }
      setResult(calculateWeightConverter(input as Parameters<typeof calculateWeightConverter>[0]))
      setError(null)
    } catch (err) {
      setError((err as Error).message)
      setResult(null)
    }
  }

  function reset() {
    setValue('')
    setFromUnit('kg')
    setResult(null)
    setError(null)
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">
            {t('label_value') ?? 'Value'}
          </label>
          <input
            type="number"
            value={value}
            onChange={e => setValue(e.target.value)} min={0} max={1000000000000}
            placeholder="Value"
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-content-secondary mb-1">{t('label_fromUnit') ?? 'From'}</label>
          <select
            value={fromUnit}
            onChange={e => setFromUnit(e.target.value)}
            className="w-full bg-surface-input border border-border-default rounded-lg px-3 py-2 text-content-primary focus:outline-none focus:ring-2 focus:ring-accent-primary"
          >
          <option key="kg" value="kg">Kg</option>
          <option key="g" value="g">G</option>
          <option key="mg" value="mg">Mg</option>
          <option key="lb" value="lb">Lb</option>
          <option key="oz" value="oz">Oz</option>
          <option key="st" value="st">St</option>
          <option key="t" value="t">T</option>
          <option key="ton" value="ton">Ton</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={calculate}
          className="flex-1 bg-accent-primary hover:bg-accent-primary-hover text-white font-semibold py-2.5 px-6 rounded-lg transition-colors"
        >
          {t('calculate') ?? 'Calculate'}
        </button>
        <button
          onClick={reset}
          className="px-4 py-2.5 border border-border-default text-content-secondary hover:text-content-primary hover:border-border-hover rounded-lg transition-colors"
        >
          {t('reset') ?? 'Reset'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="bg-surface-card border border-border-default rounded-xl p-5">
          <h3 className="text-sm font-medium text-content-secondary mb-4">{t('result') ?? 'Result'}</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_kilograms') ?? 'Kilograms'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.kilograms === 'number' ? result.kilograms.toLocaleString() : result.kilograms}<span className="text-sm text-content-secondary"> kg</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_grams') ?? 'Grams'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.grams === 'number' ? result.grams.toLocaleString() : result.grams}<span className="text-sm text-content-secondary"> g</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_pounds') ?? 'Pounds'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.pounds === 'number' ? result.pounds.toLocaleString() : result.pounds}<span className="text-sm text-content-secondary"> lb</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_ounces') ?? 'Ounces'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.ounces === 'number' ? result.ounces.toLocaleString() : result.ounces}<span className="text-sm text-content-secondary"> oz</span>
              </div>
            </div>
            <div className="bg-surface-elevated rounded-lg p-3">
              <div className="text-xs text-content-tertiary mb-1">{t('label_stones') ?? 'Stones'}</div>
              <div className="text-lg font-semibold text-content-primary">
                {typeof result.stones === 'number' ? result.stones.toLocaleString() : result.stones}<span className="text-sm text-content-secondary"> st</span>
              </div>
            </div>
          </div>
          <ShareButtons text={`${result.kilograms} kg = ${result.pounds} lbs = ${result.grams} g — converted free at SolviqLab`} className="mt-4" />
        </div>
      )}
    </div>
  )
}
