// Auto-generated by CALCO Factory
import type { TdeeCalculatorOutput } from './lib/types.js'

const BUCKETS = [
  {
    "key": "low",
    "label": "Low Activity",
    "range": "sedentary",
    "interpretation": "Desk job with little to no exercise."
  },
  {
    "key": "moderate",
    "label": "Moderate",
    "range": "moderate",
    "interpretation": "Moderate exercise 3-5 days/week."
  },
  {
    "key": "high",
    "label": "Very Active",
    "range": "very_active",
    "interpretation": "Hard exercise daily or twice per day."
  }
]

export function getInterpretation(output: TdeeCalculatorOutput, _lang = 'en'): string {
  // Return first matching bucket interpretation
  // Instruments override this with specific logic
  const firstOutput = Object.values(output as Record<string, unknown>)[0]
  if (typeof firstOutput === 'string') {
    const bucket = BUCKETS.find(b => b.key === firstOutput)
    return bucket?.interpretation ?? ''
  }
  return BUCKETS[0]?.interpretation ?? ''
}
