// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/tdee-calculator`

  return {
    title: 'TDEE Calculator — Total Daily Energy Expenditure',
    description: 'Calculate your Total Daily Energy Expenditure (TDEE) based on your BMR and activity level. Know exactly how many calories you need per day.',
    canonical,
    ogImage: `https://solviqlab.com/og/tdee-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/tdee-calculator`,
      es: `https://solviqlab.com/es/tdee-calculator`,
      pt: `https://solviqlab.com/pt/tdee-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'TDEE Calculator — Total Daily Energy Expenditure',
        description: 'Calculate your Total Daily Energy Expenditure (TDEE) based on your BMR and activity level. Know exactly how many calories you need per day.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'TDEE Calculator — Total Daily Energy Expenditure',
        description: 'Calculate your Total Daily Energy Expenditure (TDEE) based on your BMR and activity level. Know exactly how many calories you need per day.',
        keywords: 'tdee calculator',
        url: canonical,
      },
    ],
  }
}
