// Auto-generated by CALCO Factory
import type { AverageCalculatorInput, AverageCalculatorOutput } from './types.js'

export function calculateAverageCalculator(input: AverageCalculatorInput): AverageCalculatorOutput {
  const { numbers } = input
  const nums = Array.isArray(numbers) ? numbers : [numbers]
const sorted = [...nums].sort((a, b) => a - b)
const count = nums.length
const sum = nums.reduce((a, b) => a + b, 0)
const mean = sum / count
const median = count % 2 === 0 ? (sorted[count/2-1]! + sorted[count/2]!) / 2 : sorted[Math.floor(count/2)]!
const freq = new Map<number, number>()
nums.forEach(n => freq.set(n, (freq.get(n) ?? 0) + 1))
const maxFreq = Math.max(...freq.values())
const mode = [...freq.entries()].filter(([, f]) => f === maxFreq).map(([n]) => n)[0] ?? mean
const range = sorted[sorted.length - 1]! - sorted[0]!
const r = (v: number) => Math.round(v * 10000) / 10000
return { mean: r(mean), median: r(median), mode: r(mode), range: r(range), count, sum: r(sum) }
}
