// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface AverageCalculatorInput {
  numbers: number[]
}

export interface AverageCalculatorOutput {
  mean: number
  median: number
  mode: number
  range: number
  count: number | string
  sum: number
}
