// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { AverageCalculatorInput } from './types.js'

export const averageCalculatorSchema = z.object({ numbers: z.array(z.number()).min(1).max(1000) })

export type { AverageCalculatorInput }

export function validate(raw: unknown): AverageCalculatorInput {
  return averageCalculatorSchema.parse(raw) as AverageCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: AverageCalculatorInput } | { success: false; errors: string[] } {
  const result = averageCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as AverageCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
