// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/area-converter`

  return {
    title: 'Area Converter — Convert m², ft², acres, hectares & more',
    description: 'Convert area units instantly: square meters, square feet, acres, hectares, square kilometers, square miles. Free area unit converter.',
    canonical,
    ogImage: `https://solviqlab.com/og/area-converter.png`,
    alternates: {
      en: `https://solviqlab.com/en/area-converter`,
      es: `https://solviqlab.com/es/area-converter`,
      pt: `https://solviqlab.com/pt/area-converter`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Area Converter — Convert m², ft², acres, hectares & more',
        description: 'Convert area units instantly: square meters, square feet, acres, hectares, square kilometers, square miles. Free area unit converter.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Area Converter — Convert m², ft², acres, hectares & more',
        description: 'Convert area units instantly: square meters, square feet, acres, hectares, square kilometers, square miles. Free area unit converter.',
        keywords: 'area converter',
        url: canonical,
      },
    ],
  }
}
