// Auto-generated by CALCO Factory
import type { WeightConverterInput, WeightConverterOutput } from './types.js'

export function calculateWeightConverter(input: WeightConverterInput): WeightConverterOutput {
  const { value, fromUnit } = input
  const toKg: Record<string, number> = {
  kg: 1, g: 0.001, mg: 0.000001, lb: 0.453592, oz: 0.0283495, st: 6.35029, t: 1000, ton: 907.185,
}
const inKg = value * (toKg[fromUnit] ?? 1)
const r = (v: number, d: number) => Math.round(v * Math.pow(10, d)) / Math.pow(10, d)
return {
  kilograms: r(inKg, 4),
  grams: r(inKg * 1000, 2),
  pounds: r(inKg / 0.453592, 4),
  ounces: r(inKg / 0.0283495, 3),
  stones: r(inKg / 6.35029, 4),
}
}
