// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface WeightConverterInput {
  value: number
  fromUnit: 'kg' | 'g' | 'mg' | 'lb' | 'oz' | 'st' | 't' | 'ton'
}

export interface WeightConverterOutput {
  kilograms: number
  grams: number
  pounds: number
  ounces: number
  stones: number
}
