// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { WeightConverterInput } from './types.js'

export const weightConverterSchema = z.object({
  value: z.number().min(0).max(1e12),
  fromUnit: z.enum(['kg', 'g', 'mg', 'lb', 'oz', 'st', 't', 'ton']),
})

export type { WeightConverterInput }

export function validate(raw: unknown): WeightConverterInput {
  return weightConverterSchema.parse(raw) as WeightConverterInput
}

export function safeValidate(raw: unknown): { success: true; data: WeightConverterInput } | { success: false; errors: string[] } {
  const result = weightConverterSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as WeightConverterInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
