// Auto-generated by CALCO Factory
import type { IdealWeightCalculatorInput, IdealWeightCalculatorOutput } from './types.js'

export function calculateIdealWeightCalculator(input: IdealWeightCalculatorInput): IdealWeightCalculatorOutput {
  const { height, sex } = input
  const heightInInches = height / 2.54
const inchesOver5Feet = Math.max(0, heightInInches - 60)
let robinson: number, miller: number, devine: number
if (sex === 'male') {
  robinson = 52 + 1.9 * inchesOver5Feet
  miller = 56.2 + 1.41 * inchesOver5Feet
  devine = 50 + 2.3 * inchesOver5Feet
} else {
  robinson = 49 + 1.7 * inchesOver5Feet
  miller = 53.1 + 1.36 * inchesOver5Feet
  devine = 45.5 + 2.3 * inchesOver5Feet
}
const average = Math.round(((robinson + miller + devine) / 3) * 10) / 10
return {
  robinson: Math.round(robinson * 10) / 10,
  miller: Math.round(miller * 10) / 10,
  devine: Math.round(devine * 10) / 10,
  average,
}
}
