// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface IdealWeightCalculatorInput {
  height: number
  sex: 'male' | 'female'
}

export interface IdealWeightCalculatorOutput {
  robinson: number
  miller: number
  devine: number
  average: number
}
