// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { IdealWeightCalculatorInput } from './types.js'

export const idealWeightCalculatorSchema = z.object({
  height: z.number().min(100).max(250),
  sex: z.enum(['male', 'female']),
})

export type { IdealWeightCalculatorInput }

export function validate(raw: unknown): IdealWeightCalculatorInput {
  return idealWeightCalculatorSchema.parse(raw) as IdealWeightCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: IdealWeightCalculatorInput } | { success: false; errors: string[] } {
  const result = idealWeightCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as IdealWeightCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
