// Auto-generated by CALCO Factory
import type { CompoundInterestCalculatorInput, CompoundInterestCalculatorOutput } from './types.js'

export function calculateCompoundInterestCalculator(input: CompoundInterestCalculatorInput): CompoundInterestCalculatorOutput {
  const { principal, annualRate, years, monthlyContribution, compoundFrequency } = input
  const freq: Record<string, number> = { annually: 1, quarterly: 4, monthly: 12, daily: 365 }
const n = freq[compoundFrequency] ?? 12
const r = annualRate / 100
const monthly = monthlyContribution ?? 0
// Compound principal
const compoundedPrincipal = principal * Math.pow(1 + r / n, n * years)
// Future value of monthly contributions
const monthlyRate = r / 12
const months = years * 12
const fvContributions = monthly > 0
  ? monthly * (Math.pow(1 + monthlyRate, months) - 1) / monthlyRate
  : 0
const finalAmount = Math.round((compoundedPrincipal + fvContributions) * 100) / 100
const totalContributions = Math.round((principal + monthly * months) * 100) / 100
const totalInterest = Math.round((finalAmount - totalContributions) * 100) / 100
return { finalAmount, totalContributions, totalInterest }
}
