// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface CompoundInterestCalculatorInput {
  principal: number
  annualRate: number
  years: number
  monthlyContribution?: number
  compoundFrequency: 'annually' | 'quarterly' | 'monthly' | 'daily'
}

export interface CompoundInterestCalculatorOutput {
  finalAmount: number
  totalContributions: number
  totalInterest: number
}
