// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { CompoundInterestCalculatorInput } from './types.js'

export const compoundInterestCalculatorSchema = z.object({
  principal: z.number().min(0).max(100_000_000),
  annualRate: z.number().min(0).max(100),
  years: z.number().min(1).max(100),
  monthlyContribution: z.number().min(0).max(1_000_000).optional(),
  compoundFrequency: z.enum(['annually', 'quarterly', 'monthly', 'daily']),
})

export type { CompoundInterestCalculatorInput }

export function validate(raw: unknown): CompoundInterestCalculatorInput {
  return compoundInterestCalculatorSchema.parse(raw) as CompoundInterestCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: CompoundInterestCalculatorInput } | { success: false; errors: string[] } {
  const result = compoundInterestCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as CompoundInterestCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
