// Auto-generated by CALCO Factory
import type { LengthConverterInput, LengthConverterOutput } from './types.js'

export function calculateLengthConverter(input: LengthConverterInput): LengthConverterOutput {
  const { value, fromUnit } = input
  const toMeters: Record<string, number> = {
  m: 1, km: 1000, cm: 0.01, mm: 0.001, ft: 0.3048,
  in: 0.0254, yd: 0.9144, mi: 1609.344, nm: 1852, μm: 0.000001,
}
const inMeters = value * (toMeters[fromUnit] ?? 1)
const r = (v: number, d: number) => Math.round(v * Math.pow(10, d)) / Math.pow(10, d)
return {
  meters: r(inMeters, 6),
  kilometers: r(inMeters / 1000, 6),
  centimeters: r(inMeters * 100, 4),
  feet: r(inMeters / 0.3048, 4),
  inches: r(inMeters / 0.0254, 4),
  miles: r(inMeters / 1609.344, 6),
}
}
