// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface LengthConverterInput {
  value: number
  fromUnit: 'm' | 'km' | 'cm' | 'mm' | 'ft' | 'in' | 'yd' | 'mi' | 'nm' | 'μm'
}

export interface LengthConverterOutput {
  meters: number
  kilometers: number
  centimeters: number
  feet: number
  inches: number
  miles: number
}
