// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { LengthConverterInput } from './types.js'

export const lengthConverterSchema = z.object({
  value: z.number().min(0).max(1e15),
  fromUnit: z.enum(['m', 'km', 'cm', 'mm', 'ft', 'in', 'yd', 'mi', 'nm', 'μm']),
})

export type { LengthConverterInput }

export function validate(raw: unknown): LengthConverterInput {
  return lengthConverterSchema.parse(raw) as LengthConverterInput
}

export function safeValidate(raw: unknown): { success: true; data: LengthConverterInput } | { success: false; errors: string[] } {
  const result = lengthConverterSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as LengthConverterInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
