// Auto-generated by CALCO Factory
import type { VolumeConverterOutput } from './lib/types.js'

export function getInterpretation(_output: VolumeConverterOutput, _lang = 'en'): string {
  return ''
}
