// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/volume-converter`

  return {
    title: 'Volume Converter — Liters, Gallons, ml, Cups & more',
    description: 'Convert volume units instantly: liters, gallons, milliliters, cups, fluid ounces, cubic meters, cubic feet. Free volume unit converter.',
    canonical,
    ogImage: `https://solviqlab.com/og/volume-converter.png`,
    alternates: {
      en: `https://solviqlab.com/en/volume-converter`,
      es: `https://solviqlab.com/es/volume-converter`,
      pt: `https://solviqlab.com/pt/volume-converter`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Volume Converter — Liters, Gallons, ml, Cups & more',
        description: 'Convert volume units instantly: liters, gallons, milliliters, cups, fluid ounces, cubic meters, cubic feet. Free volume unit converter.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Volume Converter — Liters, Gallons, ml, Cups & more',
        description: 'Convert volume units instantly: liters, gallons, milliliters, cups, fluid ounces, cubic meters, cubic feet. Free volume unit converter.',
        keywords: 'volume converter',
        url: canonical,
      },
    ],
  }
}
