// Auto-generated by CALCO Factory
import type { RatioCalculatorOutput } from './lib/types.js'

export function getInterpretation(_output: RatioCalculatorOutput, _lang = 'en'): string {
  return ''
}
