// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/ratio-calculator`

  return {
    title: 'Ratio Calculator — Simplify & Solve Ratios',
    description: 'Simplify ratios, solve proportions, and scale recipes or measurements. The fastest ratio calculator online with step-by-step solutions.',
    canonical,
    ogImage: `https://solviqlab.com/og/ratio-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/ratio-calculator`,
      es: `https://solviqlab.com/es/ratio-calculator`,
      pt: `https://solviqlab.com/pt/ratio-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Ratio Calculator — Simplify & Solve Ratios',
        description: 'Simplify ratios, solve proportions, and scale recipes or measurements. The fastest ratio calculator online with step-by-step solutions.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Ratio Calculator — Simplify & Solve Ratios',
        description: 'Simplify ratios, solve proportions, and scale recipes or measurements. The fastest ratio calculator online with step-by-step solutions.',
        keywords: 'ratio calculator',
        url: canonical,
      },
    ],
  }
}
