// Auto-generated by CALCO Factory
import type { TemperatureConverterInput, TemperatureConverterOutput } from './types.js'

export function calculateTemperatureConverter(input: TemperatureConverterInput): TemperatureConverterOutput {
  const { value, fromUnit } = input
  let celsius: number
if (fromUnit === 'C') celsius = value
else if (fromUnit === 'F') celsius = (value - 32) * 5 / 9
else if (fromUnit === 'K') celsius = value - 273.15
else celsius = (value - 491.67) * 5 / 9
const r = (v: number) => Math.round(v * 100) / 100
return { celsius: r(celsius), fahrenheit: r(celsius * 9/5 + 32), kelvin: r(celsius + 273.15) }
}
