// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface TemperatureConverterInput {
  value: number
  fromUnit: 'C' | 'F' | 'K' | 'R'
}

export interface TemperatureConverterOutput {
  celsius: number
  fahrenheit: number
  kelvin: number
}
