// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { TemperatureConverterInput } from './types.js'

export const temperatureConverterSchema = z.object({
  value: z.number().min(-1000).max(100000),
  fromUnit: z.enum(['C', 'F', 'K', 'R']),
})

export type { TemperatureConverterInput }

export function validate(raw: unknown): TemperatureConverterInput {
  return temperatureConverterSchema.parse(raw) as TemperatureConverterInput
}

export function safeValidate(raw: unknown): { success: true; data: TemperatureConverterInput } | { success: false; errors: string[] } {
  const result = temperatureConverterSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as TemperatureConverterInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
