// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/area-calculator`

  return {
    title: 'Area Calculator — Rectangle, Circle, Triangle & More',
    description: 'Calculate the area of any shape: rectangle, square, circle, triangle, trapezoid, and more. Instant results with formula explanations.',
    canonical,
    ogImage: `https://solviqlab.com/og/area-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/area-calculator`,
      es: `https://solviqlab.com/es/area-calculator`,
      pt: `https://solviqlab.com/pt/area-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Area Calculator — Rectangle, Circle, Triangle & More',
        description: 'Calculate the area of any shape: rectangle, square, circle, triangle, trapezoid, and more. Instant results with formula explanations.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Area Calculator — Rectangle, Circle, Triangle & More',
        description: 'Calculate the area of any shape: rectangle, square, circle, triangle, trapezoid, and more. Instant results with formula explanations.',
        keywords: 'area calculator',
        url: canonical,
      },
    ],
  }
}
