// Auto-generated by CALCO Factory
import type { BmrCalculatorOutput } from './lib/types.js'

const BUCKETS = [
  {
    "key": "low",
    "label": "Low",
    "range": "< 1200",
    "interpretation": "Your BMR is lower than average, suggesting a smaller body frame or lower muscle mass."
  },
  {
    "key": "average",
    "label": "Average",
    "range": "1200–1800",
    "interpretation": "Your BMR is in the typical range for your demographics."
  },
  {
    "key": "high",
    "label": "High",
    "range": "> 1800",
    "interpretation": "Your BMR is above average, often associated with greater muscle mass or larger body frame."
  }
]

export function getInterpretation(output: BmrCalculatorOutput, _lang = 'en'): string {
  // Return first matching bucket interpretation
  // Instruments override this with specific logic
  const firstOutput = Object.values(output as Record<string, unknown>)[0]
  if (typeof firstOutput === 'string') {
    const bucket = BUCKETS.find(b => b.key === firstOutput)
    return bucket?.interpretation ?? ''
  }
  return BUCKETS[0]?.interpretation ?? ''
}
