// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/bmr-calculator`

  return {
    title: 'BMR Calculator — Basal Metabolic Rate',
    description: 'Calculate your Basal Metabolic Rate (BMR) using the Mifflin-St Jeor equation. Find how many calories your body burns at complete rest.',
    canonical,
    ogImage: `https://solviqlab.com/og/bmr-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/bmr-calculator`,
      es: `https://solviqlab.com/es/bmr-calculator`,
      pt: `https://solviqlab.com/pt/bmr-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'BMR Calculator — Basal Metabolic Rate',
        description: 'Calculate your Basal Metabolic Rate (BMR) using the Mifflin-St Jeor equation. Find how many calories your body burns at complete rest.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'BMR Calculator — Basal Metabolic Rate',
        description: 'Calculate your Basal Metabolic Rate (BMR) using the Mifflin-St Jeor equation. Find how many calories your body burns at complete rest.',
        keywords: 'bmr calculator',
        url: canonical,
      },
    ],
  }
}
