// Journey Engine — i18n strings for the journey UI
// Covers all 10 supported languages.
// Per-instrument reasons (in config.ts) are English-only in V3 Sprint 01.

export interface JourneyStrings {
  // NextStepCard
  readonly recommendedNextStep: string
  readonly minutesLabel: (n: number) => string
  readonly continueJourney: string
  readonly profileContribution: (label: string, pct: number) => string

  // JourneyProgressCard
  readonly journeyProgress: string
  readonly stepN: (n: number, total: number) => string
  readonly completedLabel: string
  readonly currentLabel: string
  readonly upcomingLabel: string

  // UnlockCard
  readonly stepsToUnlock: (n: number, reward: string) => string
  readonly stepsRemaining: (n: number) => string
  readonly keepGoing: string

  // AIConsultCard
  readonly aiConsultTitle: string
  readonly aiConsultDescription: string
  readonly aiConsultLocked: string
  readonly aiUnlockHint: (nextSlug: string) => string

  // UI labels
  readonly freeNoSignup: string
  readonly signIn: string
  readonly nextStepBadge: string
  readonly veryHighImpact: string
  readonly highImpact: string
  readonly mediumImpact: string
  readonly lowImpact: string
  readonly aiConsultationLabel: string

  // Registration widget
  readonly saveHealthProfile: string
  readonly regDescription: string
  readonly profileCompletePercent: (n: number) => string
  readonly signalsCollected: (n: number, domains: number) => string
  readonly nameOptional: string
  readonly emailRequired: string
  readonly saveProfileBtn: string
  readonly savingBtn: string
  readonly freeForever: string
  readonly regBenefit1: string
  readonly regBenefit2: string
  readonly regBenefit3: string
  readonly regBenefit4: string
  readonly profileSavedTitle: string
  readonly profileSavedSubtitle: string
}

type Lang = 'en' | 'uk' | 'es' | 'pt' | 'fr' | 'de' | 'pl' | 'tr' | 'it' | 'nl'

const STRINGS: Record<Lang, JourneyStrings> = {
  en: {
    recommendedNextStep: 'Recommended Next Step',
    minutesLabel: (n) => `${n} min`,
    continueJourney: 'Continue Your Journey',
    profileContribution: (label, pct) => `+${pct}% ${label}`,
    journeyProgress: 'Journey Progress',
    stepN: (n, total) => `Step ${n} of ${total}`,
    completedLabel: 'Completed',
    currentLabel: 'Current',
    upcomingLabel: 'Up next',
    stepsToUnlock: (n, reward) => `Complete ${n} more ${n === 1 ? 'step' : 'steps'} to unlock your ${reward}`,
    stepsRemaining: (n) => `${n} ${n === 1 ? 'step' : 'steps'} remaining`,
    keepGoing: 'Keep Going',
    aiConsultTitle: 'Personal AI Consultation',
    aiConsultDescription: 'Get a personalized analysis based on your complete profile, with actionable insights tailored to your results.',
    aiConsultLocked: 'Locked',
    aiUnlockHint: () => 'Complete your next step to unlock',
    freeNoSignup: 'free · no signup',
    signIn: 'Sign In',
    nextStepBadge: 'Next Step',
    veryHighImpact: 'Very High Impact',
    highImpact: 'High Impact',
    mediumImpact: 'Medium Impact',
    lowImpact: 'Low Impact',
    aiConsultationLabel: 'AI Consultation',
    saveHealthProfile: 'Save Your Health Profile',
    regDescription: 'Your results are building a personal health picture. Save it for free — no credit card required.',
    profileCompletePercent: (n) => `Your Health Profile — ${n}% complete`,
    signalsCollected: (n, d) => `${n} signal${n === 1 ? '' : 's'} collected across ${d} domain${d === 1 ? '' : 's'} — don't lose this.`,
    nameOptional: 'Name (optional)',
    emailRequired: 'Email',
    saveProfileBtn: 'Save My Health Profile →',
    savingBtn: 'Saving…',
    freeForever: 'Free forever. No credit card. All your data stays local until you choose to sync.',
    regBenefit1: '✓ All your calculator results in one place',
    regBenefit2: '✓ Personalized next-step recommendations',
    regBenefit3: '✓ Track your health journey over time',
    regBenefit4: '✓ AI consultation unlocked at 80% readiness',
    profileSavedTitle: 'Profile saved!',
    profileSavedSubtitle: 'Your results are synced. Check your email to verify.',
  },

  uk: {
    recommendedNextStep: 'Рекомендований наступний крок',
    minutesLabel: (n) => `${n} хв`,
    continueJourney: 'Продовжити шлях',
    profileContribution: (label, pct) => `+${pct}% ${label}`,
    journeyProgress: 'Прогрес шляху',
    stepN: (n, total) => `Крок ${n} з ${total}`,
    completedLabel: 'Завершено',
    currentLabel: 'Поточний',
    upcomingLabel: 'Далі',
    stepsToUnlock: (n, reward) => `Зробіть ще ${n} ${n === 1 ? 'крок' : 'кроки'}, щоб розблокувати ${reward}`,
    stepsRemaining: (n) => `Залишилось ${n} ${n === 1 ? 'крок' : 'кроки'}`,
    keepGoing: 'Продовжуй',
    aiConsultTitle: 'Персональна консультація AI',
    aiConsultDescription: 'Отримайте персоналізований аналіз на основі вашого повного профілю з практичними рекомендаціями.',
    aiConsultLocked: 'Заблоковано',
    aiUnlockHint: () => 'Завершіть наступний крок для розблокування',
    freeNoSignup: 'безкоштовно · без реєстрації',
    signIn: 'Увійти',
    nextStepBadge: 'Наступний крок',
    veryHighImpact: 'Дуже висока ефективність',
    highImpact: 'Висока ефективність',
    mediumImpact: 'Середня ефективність',
    lowImpact: 'Низька ефективність',
    aiConsultationLabel: 'AI Консультація',
    saveHealthProfile: 'Збережіть свій Профіль здоров\'я',
    regDescription: 'Ваші результати формують персональну картину здоров\'я. Збережіть безкоштовно — без кредитної картки.',
    profileCompletePercent: (n) => `Ваш Профіль здоров\'я — ${n}% завершено`,
    signalsCollected: (n, d) => `${n} сигнал${n === 1 ? '' : 'и'} зібрано в ${d} ${d === 1 ? 'сфері' : 'сферах'} — не втрачайте це.`,
    nameOptional: 'Ім\'я (необов\'язково)',
    emailRequired: 'Email',
    saveProfileBtn: 'Зберегти Профіль здоров\'я →',
    savingBtn: 'Збереження…',
    freeForever: 'Безкоштовно назавжди. Без кредитної картки. Усі дані залишаються локально до синхронізації.',
    regBenefit1: '✓ Усі ваші результати в одному місці',
    regBenefit2: '✓ Персоналізовані рекомендації наступних кроків',
    regBenefit3: '✓ Відстежуйте своє здоров\'я з часом',
    regBenefit4: '✓ AI консультація розблокована при 80% готовності',
    profileSavedTitle: 'Профіль збережено!',
    profileSavedSubtitle: 'Ваші результати синхронізовані. Перевірте email для підтвердження.',
  },

  es: {
    recommendedNextStep: 'Siguiente paso recomendado',
    minutesLabel: (n) => `${n} min`,
    continueJourney: 'Continúa tu camino',
    profileContribution: (label, pct) => `+${pct}% ${label}`,
    journeyProgress: 'Progreso del camino',
    stepN: (n, total) => `Paso ${n} de ${total}`,
    completedLabel: 'Completado',
    currentLabel: 'Actual',
    upcomingLabel: 'Siguiente',
    stepsToUnlock: (n, reward) => `Completa ${n} ${n === 1 ? 'paso' : 'pasos'} más para desbloquear tu ${reward}`,
    stepsRemaining: (n) => `${n} ${n === 1 ? 'paso' : 'pasos'} restantes`,
    keepGoing: 'Sigue adelante',
    aiConsultTitle: 'Consulta Personal con IA',
    aiConsultDescription: 'Obtén un análisis personalizado basado en tu perfil completo con perspectivas prácticas.',
    aiConsultLocked: 'Bloqueado',
    aiUnlockHint: () => 'Completa tu próximo paso para desbloquear',
    freeNoSignup: 'free · no signup',
    signIn: 'Sign In',
    nextStepBadge: 'Next Step',
    veryHighImpact: 'Very High Impact',
    highImpact: 'High Impact',
    mediumImpact: 'Medium Impact',
    lowImpact: 'Low Impact',
    aiConsultationLabel: 'AI Consultation',
    saveHealthProfile: 'Save Your Health Profile',
    regDescription: 'Your results are building a personal health picture. Save it for free — no credit card required.',
    profileCompletePercent: (n) => `Your Health Profile — ${n}% complete`,
    signalsCollected: (n, d) => `${n} signal${n === 1 ? '' : 's'} collected across ${d} domain${d === 1 ? '' : 's'} — don't lose this.`,
    nameOptional: 'Name (optional)',
    emailRequired: 'Email',
    saveProfileBtn: 'Save My Health Profile →',
    savingBtn: 'Saving…',
    freeForever: 'Free forever. No credit card. All your data stays local until you choose to sync.',
    regBenefit1: '✓ All your calculator results in one place',
    regBenefit2: '✓ Personalized next-step recommendations',
    regBenefit3: '✓ Track your health journey over time',
    regBenefit4: '✓ AI consultation unlocked at 80% readiness',
    profileSavedTitle: 'Profile saved!',
    profileSavedSubtitle: 'Your results are synced. Check your email to verify.',
  },

  pt: {
    recommendedNextStep: 'Próximo passo recomendado',
    minutesLabel: (n) => `${n} min`,
    continueJourney: 'Continue sua jornada',
    profileContribution: (label, pct) => `+${pct}% ${label}`,
    journeyProgress: 'Progresso da jornada',
    stepN: (n, total) => `Passo ${n} de ${total}`,
    completedLabel: 'Concluído',
    currentLabel: 'Atual',
    upcomingLabel: 'A seguir',
    stepsToUnlock: (n, reward) => `Complete mais ${n} ${n === 1 ? 'passo' : 'passos'} para desbloquear seu ${reward}`,
    stepsRemaining: (n) => `${n} ${n === 1 ? 'passo' : 'passos'} restantes`,
    keepGoing: 'Continue',
    aiConsultTitle: 'Consulta Pessoal com IA',
    aiConsultDescription: 'Obtenha uma análise personalizada baseada no seu perfil completo com insights práticos.',
    aiConsultLocked: 'Bloqueado',
    aiUnlockHint: () => 'Complete o próximo passo para desbloquear',
    freeNoSignup: 'free · no signup',
    signIn: 'Sign In',
    nextStepBadge: 'Next Step',
    veryHighImpact: 'Very High Impact',
    highImpact: 'High Impact',
    mediumImpact: 'Medium Impact',
    lowImpact: 'Low Impact',
    aiConsultationLabel: 'AI Consultation',
    saveHealthProfile: 'Save Your Health Profile',
    regDescription: 'Your results are building a personal health picture. Save it for free — no credit card required.',
    profileCompletePercent: (n) => `Your Health Profile — ${n}% complete`,
    signalsCollected: (n, d) => `${n} signal${n === 1 ? '' : 's'} collected across ${d} domain${d === 1 ? '' : 's'} — don't lose this.`,
    nameOptional: 'Name (optional)',
    emailRequired: 'Email',
    saveProfileBtn: 'Save My Health Profile →',
    savingBtn: 'Saving…',
    freeForever: 'Free forever. No credit card. All your data stays local until you choose to sync.',
    regBenefit1: '✓ All your calculator results in one place',
    regBenefit2: '✓ Personalized next-step recommendations',
    regBenefit3: '✓ Track your health journey over time',
    regBenefit4: '✓ AI consultation unlocked at 80% readiness',
    profileSavedTitle: 'Profile saved!',
    profileSavedSubtitle: 'Your results are synced. Check your email to verify.',
  },

  fr: {
    recommendedNextStep: 'Prochaine étape recommandée',
    minutesLabel: (n) => `${n} min`,
    continueJourney: 'Continuer votre parcours',
    profileContribution: (label, pct) => `+${pct}% ${label}`,
    journeyProgress: 'Progression du parcours',
    stepN: (n, total) => `Étape ${n} sur ${total}`,
    completedLabel: 'Complété',
    currentLabel: 'Actuel',
    upcomingLabel: 'Suivant',
    stepsToUnlock: (n, reward) => `Complétez ${n} ${n === 1 ? 'étape' : 'étapes'} de plus pour débloquer votre ${reward}`,
    stepsRemaining: (n) => `${n} ${n === 1 ? 'étape' : 'étapes'} restante${n === 1 ? '' : 's'}`,
    keepGoing: 'Continuez',
    aiConsultTitle: 'Consultation IA Personnelle',
    aiConsultDescription: 'Obtenez une analyse personnalisée basée sur votre profil complet avec des insights concrets.',
    aiConsultLocked: 'Verrouillé',
    aiUnlockHint: () => 'Complétez votre prochaine étape pour débloquer',
    freeNoSignup: 'free · no signup',
    signIn: 'Sign In',
    nextStepBadge: 'Next Step',
    veryHighImpact: 'Very High Impact',
    highImpact: 'High Impact',
    mediumImpact: 'Medium Impact',
    lowImpact: 'Low Impact',
    aiConsultationLabel: 'AI Consultation',
    saveHealthProfile: 'Save Your Health Profile',
    regDescription: 'Your results are building a personal health picture. Save it for free — no credit card required.',
    profileCompletePercent: (n) => `Your Health Profile — ${n}% complete`,
    signalsCollected: (n, d) => `${n} signal${n === 1 ? '' : 's'} collected across ${d} domain${d === 1 ? '' : 's'} — don't lose this.`,
    nameOptional: 'Name (optional)',
    emailRequired: 'Email',
    saveProfileBtn: 'Save My Health Profile →',
    savingBtn: 'Saving…',
    freeForever: 'Free forever. No credit card. All your data stays local until you choose to sync.',
    regBenefit1: '✓ All your calculator results in one place',
    regBenefit2: '✓ Personalized next-step recommendations',
    regBenefit3: '✓ Track your health journey over time',
    regBenefit4: '✓ AI consultation unlocked at 80% readiness',
    profileSavedTitle: 'Profile saved!',
    profileSavedSubtitle: 'Your results are synced. Check your email to verify.',
  },

  de: {
    recommendedNextStep: 'Empfohlener nächster Schritt',
    minutesLabel: (n) => `${n} Min`,
    continueJourney: 'Reise fortsetzen',
    profileContribution: (label, pct) => `+${pct}% ${label}`,
    journeyProgress: 'Reisefortschritt',
    stepN: (n, total) => `Schritt ${n} von ${total}`,
    completedLabel: 'Abgeschlossen',
    currentLabel: 'Aktuell',
    upcomingLabel: 'Als nächstes',
    stepsToUnlock: (n, reward) => `Schließe ${n} weitere${n === 1 ? 'n Schritt' : ' Schritte'} ab, um dein ${reward} freizuschalten`,
    stepsRemaining: (n) => `${n} ${n === 1 ? 'Schritt' : 'Schritte'} verbleibend`,
    keepGoing: 'Weitermachen',
    aiConsultTitle: 'Persönliche KI-Beratung',
    aiConsultDescription: 'Erhalte eine personalisierte Analyse basierend auf deinem vollständigen Profil mit umsetzbaren Erkenntnissen.',
    aiConsultLocked: 'Gesperrt',
    aiUnlockHint: () => 'Schließe den nächsten Schritt ab, um freizuschalten',
    freeNoSignup: 'free · no signup',
    signIn: 'Sign In',
    nextStepBadge: 'Next Step',
    veryHighImpact: 'Very High Impact',
    highImpact: 'High Impact',
    mediumImpact: 'Medium Impact',
    lowImpact: 'Low Impact',
    aiConsultationLabel: 'AI Consultation',
    saveHealthProfile: 'Save Your Health Profile',
    regDescription: 'Your results are building a personal health picture. Save it for free — no credit card required.',
    profileCompletePercent: (n) => `Your Health Profile — ${n}% complete`,
    signalsCollected: (n, d) => `${n} signal${n === 1 ? '' : 's'} collected across ${d} domain${d === 1 ? '' : 's'} — don't lose this.`,
    nameOptional: 'Name (optional)',
    emailRequired: 'Email',
    saveProfileBtn: 'Save My Health Profile →',
    savingBtn: 'Saving…',
    freeForever: 'Free forever. No credit card. All your data stays local until you choose to sync.',
    regBenefit1: '✓ All your calculator results in one place',
    regBenefit2: '✓ Personalized next-step recommendations',
    regBenefit3: '✓ Track your health journey over time',
    regBenefit4: '✓ AI consultation unlocked at 80% readiness',
    profileSavedTitle: 'Profile saved!',
    profileSavedSubtitle: 'Your results are synced. Check your email to verify.',
  },

  pl: {
    recommendedNextStep: 'Zalecany następny krok',
    minutesLabel: (n) => `${n} min`,
    continueJourney: 'Kontynuuj podróż',
    profileContribution: (label, pct) => `+${pct}% ${label}`,
    journeyProgress: 'Postęp podróży',
    stepN: (n, total) => `Krok ${n} z ${total}`,
    completedLabel: 'Ukończono',
    currentLabel: 'Aktualny',
    upcomingLabel: 'Następny',
    stepsToUnlock: (n, reward) => `Ukończ jeszcze ${n} ${n === 1 ? 'krok' : 'kroki'}, aby odblokować ${reward}`,
    stepsRemaining: (n) => `Pozostało ${n} ${n === 1 ? 'krok' : 'kroki'}`,
    keepGoing: 'Idź dalej',
    aiConsultTitle: 'Osobista Konsultacja AI',
    aiConsultDescription: 'Uzyskaj spersonalizowaną analizę opartą na pełnym profilu z praktycznymi wskazówkami.',
    aiConsultLocked: 'Zablokowano',
    aiUnlockHint: () => 'Ukończ następny krok, aby odblokować',
    freeNoSignup: 'free · no signup',
    signIn: 'Sign In',
    nextStepBadge: 'Next Step',
    veryHighImpact: 'Very High Impact',
    highImpact: 'High Impact',
    mediumImpact: 'Medium Impact',
    lowImpact: 'Low Impact',
    aiConsultationLabel: 'AI Consultation',
    saveHealthProfile: 'Save Your Health Profile',
    regDescription: 'Your results are building a personal health picture. Save it for free — no credit card required.',
    profileCompletePercent: (n) => `Your Health Profile — ${n}% complete`,
    signalsCollected: (n, d) => `${n} signal${n === 1 ? '' : 's'} collected across ${d} domain${d === 1 ? '' : 's'} — don't lose this.`,
    nameOptional: 'Name (optional)',
    emailRequired: 'Email',
    saveProfileBtn: 'Save My Health Profile →',
    savingBtn: 'Saving…',
    freeForever: 'Free forever. No credit card. All your data stays local until you choose to sync.',
    regBenefit1: '✓ All your calculator results in one place',
    regBenefit2: '✓ Personalized next-step recommendations',
    regBenefit3: '✓ Track your health journey over time',
    regBenefit4: '✓ AI consultation unlocked at 80% readiness',
    profileSavedTitle: 'Profile saved!',
    profileSavedSubtitle: 'Your results are synced. Check your email to verify.',
  },

  tr: {
    recommendedNextStep: 'Önerilen Sonraki Adım',
    minutesLabel: (n) => `${n} dk`,
    continueJourney: 'Yolculuğuna Devam Et',
    profileContribution: (label, pct) => `+%${pct} ${label}`,
    journeyProgress: 'Yolculuk İlerlemesi',
    stepN: (n, total) => `${total} adımın ${n}. adımı`,
    completedLabel: 'Tamamlandı',
    currentLabel: 'Mevcut',
    upcomingLabel: 'Sıradaki',
    stepsToUnlock: (n, reward) => `${reward} kilidini açmak için ${n} adım daha tamamla`,
    stepsRemaining: (n) => `${n} adım kaldı`,
    keepGoing: 'Devam Et',
    aiConsultTitle: 'Kişisel AI Danışmanlığı',
    aiConsultDescription: 'Tüm profiline dayalı kişiselleştirilmiş analiz ve uygulanabilir öneriler al.',
    aiConsultLocked: 'Kilitli',
    aiUnlockHint: () => 'Kilidini açmak için sonraki adımı tamamla',
    freeNoSignup: 'free · no signup',
    signIn: 'Sign In',
    nextStepBadge: 'Next Step',
    veryHighImpact: 'Very High Impact',
    highImpact: 'High Impact',
    mediumImpact: 'Medium Impact',
    lowImpact: 'Low Impact',
    aiConsultationLabel: 'AI Consultation',
    saveHealthProfile: 'Save Your Health Profile',
    regDescription: 'Your results are building a personal health picture. Save it for free — no credit card required.',
    profileCompletePercent: (n) => `Your Health Profile — ${n}% complete`,
    signalsCollected: (n, d) => `${n} signal${n === 1 ? '' : 's'} collected across ${d} domain${d === 1 ? '' : 's'} — don't lose this.`,
    nameOptional: 'Name (optional)',
    emailRequired: 'Email',
    saveProfileBtn: 'Save My Health Profile →',
    savingBtn: 'Saving…',
    freeForever: 'Free forever. No credit card. All your data stays local until you choose to sync.',
    regBenefit1: '✓ All your calculator results in one place',
    regBenefit2: '✓ Personalized next-step recommendations',
    regBenefit3: '✓ Track your health journey over time',
    regBenefit4: '✓ AI consultation unlocked at 80% readiness',
    profileSavedTitle: 'Profile saved!',
    profileSavedSubtitle: 'Your results are synced. Check your email to verify.',
  },

  it: {
    recommendedNextStep: 'Prossimo passo consigliato',
    minutesLabel: (n) => `${n} min`,
    continueJourney: 'Continua il tuo percorso',
    profileContribution: (label, pct) => `+${pct}% ${label}`,
    journeyProgress: 'Progresso del percorso',
    stepN: (n, total) => `Passo ${n} di ${total}`,
    completedLabel: 'Completato',
    currentLabel: 'Attuale',
    upcomingLabel: 'Prossimo',
    stepsToUnlock: (n, reward) => `Completa altri ${n} ${n === 1 ? 'passo' : 'passi'} per sbloccare il tuo ${reward}`,
    stepsRemaining: (n) => `${n} ${n === 1 ? 'passo' : 'passi'} rimanenti`,
    keepGoing: 'Continua',
    aiConsultTitle: 'Consulenza AI Personale',
    aiConsultDescription: 'Ottieni un\'analisi personalizzata basata sul tuo profilo completo con approfondimenti pratici.',
    aiConsultLocked: 'Bloccato',
    aiUnlockHint: () => 'Completa il prossimo passo per sbloccare',
    freeNoSignup: 'free · no signup',
    signIn: 'Sign In',
    nextStepBadge: 'Next Step',
    veryHighImpact: 'Very High Impact',
    highImpact: 'High Impact',
    mediumImpact: 'Medium Impact',
    lowImpact: 'Low Impact',
    aiConsultationLabel: 'AI Consultation',
    saveHealthProfile: 'Save Your Health Profile',
    regDescription: 'Your results are building a personal health picture. Save it for free — no credit card required.',
    profileCompletePercent: (n) => `Your Health Profile — ${n}% complete`,
    signalsCollected: (n, d) => `${n} signal${n === 1 ? '' : 's'} collected across ${d} domain${d === 1 ? '' : 's'} — don't lose this.`,
    nameOptional: 'Name (optional)',
    emailRequired: 'Email',
    saveProfileBtn: 'Save My Health Profile →',
    savingBtn: 'Saving…',
    freeForever: 'Free forever. No credit card. All your data stays local until you choose to sync.',
    regBenefit1: '✓ All your calculator results in one place',
    regBenefit2: '✓ Personalized next-step recommendations',
    regBenefit3: '✓ Track your health journey over time',
    regBenefit4: '✓ AI consultation unlocked at 80% readiness',
    profileSavedTitle: 'Profile saved!',
    profileSavedSubtitle: 'Your results are synced. Check your email to verify.',
  },

  nl: {
    recommendedNextStep: 'Aanbevolen volgende stap',
    minutesLabel: (n) => `${n} min`,
    continueJourney: 'Ga verder met je reis',
    profileContribution: (label, pct) => `+${pct}% ${label}`,
    journeyProgress: 'Reisvoortgang',
    stepN: (n, total) => `Stap ${n} van ${total}`,
    completedLabel: 'Voltooid',
    currentLabel: 'Huidig',
    upcomingLabel: 'Volgende',
    stepsToUnlock: (n, reward) => `Voltooi nog ${n} ${n === 1 ? 'stap' : 'stappen'} om je ${reward} te ontgrendelen`,
    stepsRemaining: (n) => `${n} ${n === 1 ? 'stap' : 'stappen'} resterend`,
    keepGoing: 'Ga door',
    aiConsultTitle: 'Persoonlijke AI-Consultatie',
    aiConsultDescription: 'Ontvang een gepersonaliseerde analyse op basis van je volledige profiel met bruikbare inzichten.',
    aiConsultLocked: 'Vergrendeld',
    aiUnlockHint: () => 'Voltooi je volgende stap om te ontgrendelen',
    freeNoSignup: 'free · no signup',
    signIn: 'Sign In',
    nextStepBadge: 'Next Step',
    veryHighImpact: 'Very High Impact',
    highImpact: 'High Impact',
    mediumImpact: 'Medium Impact',
    lowImpact: 'Low Impact',
    aiConsultationLabel: 'AI Consultation',
    saveHealthProfile: 'Save Your Health Profile',
    regDescription: 'Your results are building a personal health picture. Save it for free — no credit card required.',
    profileCompletePercent: (n) => `Your Health Profile — ${n}% complete`,
    signalsCollected: (n, d) => `${n} signal${n === 1 ? '' : 's'} collected across ${d} domain${d === 1 ? '' : 's'} — don't lose this.`,
    nameOptional: 'Name (optional)',
    emailRequired: 'Email',
    saveProfileBtn: 'Save My Health Profile →',
    savingBtn: 'Saving…',
    freeForever: 'Free forever. No credit card. All your data stays local until you choose to sync.',
    regBenefit1: '✓ All your calculator results in one place',
    regBenefit2: '✓ Personalized next-step recommendations',
    regBenefit3: '✓ Track your health journey over time',
    regBenefit4: '✓ AI consultation unlocked at 80% readiness',
    profileSavedTitle: 'Profile saved!',
    profileSavedSubtitle: 'Your results are synced. Check your email to verify.',
  },
}

export function getJourneyStrings(lang: string): JourneyStrings {
  return STRINGS[(lang as Lang)] ?? STRINGS.en
}
