// Auto-generated by CALCO Factory
import type { BodyFatCalculatorOutput } from './lib/types.js'

const BUCKETS = [
  {
    "key": "essential",
    "label": "Essential Fat",
    "range": "< 14% (M) / < 21% (F)",
    "interpretation": "Minimum fat needed for basic body functions."
  },
  {
    "key": "athletic",
    "label": "Athletic",
    "range": "14-21% (M) / 21-28% (F)",
    "interpretation": "Typical for athletes with regular training."
  },
  {
    "key": "fitness",
    "label": "Fitness",
    "range": "21-25% (M) / 28-35% (F)",
    "interpretation": "Good fitness level, healthy range."
  },
  {
    "key": "obese",
    "label": "Obese",
    "range": "> 32% (M) / > 42% (F)",
    "interpretation": "Health risks associated. Consult a healthcare provider."
  }
]

export function getInterpretation(output: BodyFatCalculatorOutput, _lang = 'en'): string {
  // Return first matching bucket interpretation
  // Instruments override this with specific logic
  const firstOutput = Object.values(output as Record<string, unknown>)[0]
  if (typeof firstOutput === 'string') {
    const bucket = BUCKETS.find(b => b.key === firstOutput)
    return bucket?.interpretation ?? ''
  }
  return BUCKETS[0]?.interpretation ?? ''
}
