// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/body-fat-calculator`

  return {
    title: 'Body Fat Calculator — Estimate Your Body Fat %',
    description: 'Calculate body fat percentage using the US Navy method. Enter neck, waist, and hip measurements for an accurate body composition estimate.',
    canonical,
    ogImage: `https://solviqlab.com/og/body-fat-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/body-fat-calculator`,
      es: `https://solviqlab.com/es/body-fat-calculator`,
      pt: `https://solviqlab.com/pt/body-fat-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Body Fat Calculator — Estimate Your Body Fat %',
        description: 'Calculate body fat percentage using the US Navy method. Enter neck, waist, and hip measurements for an accurate body composition estimate.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Body Fat Calculator — Estimate Your Body Fat %',
        description: 'Calculate body fat percentage using the US Navy method. Enter neck, waist, and hip measurements for an accurate body composition estimate.',
        keywords: 'body fat calculator',
        url: canonical,
      },
    ],
  }
}
