// Auto-generated by CALCO Factory
import type { IdealWeightCalculatorOutput } from './lib/types.js'

export function getInterpretation(_output: IdealWeightCalculatorOutput, _lang = 'en'): string {
  return ''
}
