// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/ideal-weight-calculator`

  return {
    title: 'Ideal Weight Calculator — Find Your Healthy Weight',
    description: 'Calculate your ideal body weight using 4 medical formulas (Robinson, Miller, Devine, Hamwi). Get your healthy weight range by height and sex.',
    canonical,
    ogImage: `https://solviqlab.com/og/ideal-weight-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/ideal-weight-calculator`,
      es: `https://solviqlab.com/es/ideal-weight-calculator`,
      pt: `https://solviqlab.com/pt/ideal-weight-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Ideal Weight Calculator — Find Your Healthy Weight',
        description: 'Calculate your ideal body weight using 4 medical formulas (Robinson, Miller, Devine, Hamwi). Get your healthy weight range by height and sex.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Ideal Weight Calculator — Find Your Healthy Weight',
        description: 'Calculate your ideal body weight using 4 medical formulas (Robinson, Miller, Devine, Hamwi). Get your healthy weight range by height and sex.',
        keywords: 'ideal weight calculator',
        url: canonical,
      },
    ],
  }
}
