// Auto-generated by CALCO Factory
import type { VatCalculatorInput, VatCalculatorOutput } from './types.js'

export function calculateVatCalculator(input: VatCalculatorInput): VatCalculatorOutput {
  const { amount, vatRate, mode } = input
  let netAmount: number, vatAmount: number, grossAmount: number
if (mode === 'add') {
  netAmount = amount
  vatAmount = amount * vatRate / 100
  grossAmount = amount + vatAmount
} else {
  grossAmount = amount
  netAmount = amount / (1 + vatRate / 100)
  vatAmount = grossAmount - netAmount
}
return {
  netAmount: Math.round(netAmount * 100) / 100,
  vatAmount: Math.round(vatAmount * 100) / 100,
  grossAmount: Math.round(grossAmount * 100) / 100,
}
}
