// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface VatCalculatorInput {
  amount: number
  vatRate: number
  mode: 'add' | 'remove'
}

export interface VatCalculatorOutput {
  netAmount: number
  vatAmount: number
  grossAmount: number
}
