// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { VatCalculatorInput } from './types.js'

export const vatCalculatorSchema = z.object({
  amount: z.number().min(0).max(1_000_000_000),
  vatRate: z.number().min(0).max(100),
  mode: z.enum(['add', 'remove']),
})

export type { VatCalculatorInput }

export function validate(raw: unknown): VatCalculatorInput {
  return vatCalculatorSchema.parse(raw) as VatCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: VatCalculatorInput } | { success: false; errors: string[] } {
  const result = vatCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as VatCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
