// Auto-generated by CALCO Factory
import type { AreaConverterInput, AreaConverterOutput } from './types.js'

export function calculateAreaConverter(input: AreaConverterInput): AreaConverterOutput {
  const { value, fromUnit } = input
  const toM2: Record<string, number> = {
  m2: 1, km2: 1_000_000, cm2: 0.0001, mm2: 0.000001,
  ft2: 0.092903, in2: 0.00064516, yd2: 0.836127, mi2: 2_589_988.11,
  acre: 4046.8564, ha: 10_000,
}
const inM2 = value * (toM2[fromUnit] ?? 1)
const r = (v: number, d: number) => Math.round(v * Math.pow(10, d)) / Math.pow(10, d)
return {
  squareMeters: r(inM2, 4),
  squareFeet: r(inM2 / 0.092903, 4),
  squareKilometers: r(inM2 / 1_000_000, 6),
  acres: r(inM2 / 4046.8564, 4),
  hectares: r(inM2 / 10_000, 4),
}
}
