// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface AreaConverterInput {
  value: number
  fromUnit: 'm2' | 'km2' | 'cm2' | 'mm2' | 'ft2' | 'in2' | 'yd2' | 'mi2' | 'acre' | 'ha'
}

export interface AreaConverterOutput {
  squareMeters: number
  squareFeet: number
  squareKilometers: number
  acres: number
  hectares: number
}
