// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { AreaConverterInput } from './types.js'

export const areaConverterSchema = z.object({
  value: z.number().min(0).max(1e15),
  fromUnit: z.enum(['m2', 'km2', 'cm2', 'mm2', 'ft2', 'in2', 'yd2', 'mi2', 'acre', 'ha']),
})

export type { AreaConverterInput }

export function validate(raw: unknown): AreaConverterInput {
  return areaConverterSchema.parse(raw) as AreaConverterInput
}

export function safeValidate(raw: unknown): { success: true; data: AreaConverterInput } | { success: false; errors: string[] } {
  const result = areaConverterSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as AreaConverterInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
