// Auto-generated by CALCO Factory
import type { FractionCalculatorOutput } from './lib/types.js'

export function getInterpretation(_output: FractionCalculatorOutput, _lang = 'en'): string {
  return ''
}
