// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/fraction-calculator`

  return {
    title: 'Fraction Calculator — Add, Subtract, Multiply, Divide',
    description: 'Calculate fractions instantly. Add, subtract, multiply, and divide fractions with step-by-step solutions. Simplifies results automatically.',
    canonical,
    ogImage: `https://solviqlab.com/og/fraction-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/fraction-calculator`,
      es: `https://solviqlab.com/es/fraction-calculator`,
      pt: `https://solviqlab.com/pt/fraction-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Fraction Calculator — Add, Subtract, Multiply, Divide',
        description: 'Calculate fractions instantly. Add, subtract, multiply, and divide fractions with step-by-step solutions. Simplifies results automatically.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Fraction Calculator — Add, Subtract, Multiply, Divide',
        description: 'Calculate fractions instantly. Add, subtract, multiply, and divide fractions with step-by-step solutions. Simplifies results automatically.',
        keywords: 'fraction calculator',
        url: canonical,
      },
    ],
  }
}
