// Auto-generated by CALCO Factory
import type { LoanCalculatorInput, LoanCalculatorOutput } from './types.js'

export function calculateLoanCalculator(input: LoanCalculatorInput): LoanCalculatorOutput {
  const { principal, annualRate, termMonths } = input
  const r = annualRate / 100 / 12
let monthlyPayment: number
if (r === 0) {
  monthlyPayment = principal / termMonths
} else {
  monthlyPayment = principal * (r * Math.pow(1 + r, termMonths)) / (Math.pow(1 + r, termMonths) - 1)
}
monthlyPayment = Math.round(monthlyPayment * 100) / 100
const totalPayment = Math.round(monthlyPayment * termMonths * 100) / 100
const totalInterest = Math.round((totalPayment - principal) * 100) / 100
return { monthlyPayment, totalPayment, totalInterest }
}
