// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface LoanCalculatorInput {
  principal: number
  annualRate: number
  termMonths: number
}

export interface LoanCalculatorOutput {
  monthlyPayment: number
  totalPayment: number
  totalInterest: number
}
