// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { LoanCalculatorInput } from './types.js'

export const loanCalculatorSchema = z.object({
  principal: z.number().min(100).max(10_000_000),
  annualRate: z.number().min(0).max(50),
  termMonths: z.number().min(1).max(600),
})

export type { LoanCalculatorInput }

export function validate(raw: unknown): LoanCalculatorInput {
  return loanCalculatorSchema.parse(raw) as LoanCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: LoanCalculatorInput } | { success: false; errors: string[] } {
  const result = loanCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as LoanCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
