// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { BodyFatCalculatorInput } from './types.js'

export const bodyFatCalculatorSchema = z.object({
  height: z.number().min(100).max(250),
  neck: z.number().min(20).max(80),
  waist: z.number().min(40).max(200),
  hip: z.number().min(40).max(200).optional(),
  sex: z.enum(['male', 'female']),
})

export type { BodyFatCalculatorInput }

export function validate(raw: unknown): BodyFatCalculatorInput {
  return bodyFatCalculatorSchema.parse(raw) as BodyFatCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: BodyFatCalculatorInput } | { success: false; errors: string[] } {
  const result = bodyFatCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as BodyFatCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
