// Auto-generated by CALCO Factory
import type { VolumeCalculatorOutput } from './lib/types.js'

export function getInterpretation(_output: VolumeCalculatorOutput, _lang = 'en'): string {
  return ''
}
