// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/volume-calculator`

  return {
    title: 'Volume Calculator — Cube, Sphere, Cylinder & More',
    description: 'Calculate volume of any 3D shape: cube, sphere, cylinder, cone, rectangular prism. Instant results with formulas for math and engineering.',
    canonical,
    ogImage: `https://solviqlab.com/og/volume-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/volume-calculator`,
      es: `https://solviqlab.com/es/volume-calculator`,
      pt: `https://solviqlab.com/pt/volume-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Volume Calculator — Cube, Sphere, Cylinder & More',
        description: 'Calculate volume of any 3D shape: cube, sphere, cylinder, cone, rectangular prism. Instant results with formulas for math and engineering.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Volume Calculator — Cube, Sphere, Cylinder & More',
        description: 'Calculate volume of any 3D shape: cube, sphere, cylinder, cone, rectangular prism. Instant results with formulas for math and engineering.',
        keywords: 'volume calculator',
        url: canonical,
      },
    ],
  }
}
