// Auto-generated by CALCO Factory
import type { CalorieDeficitCalculatorOutput } from './lib/types.js'

export function getInterpretation(_output: CalorieDeficitCalculatorOutput, _lang = 'en'): string {
  return ''
}
