// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/calorie-deficit-calculator`

  return {
    title: 'Calorie Deficit Calculator — How Many Calories to Lose Weight',
    description: 'Calculate the exact calorie deficit needed to reach your weight loss goal. Based on TDEE with safe deficit recommendations from nutritionists.',
    canonical,
    ogImage: `https://solviqlab.com/og/calorie-deficit-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/calorie-deficit-calculator`,
      es: `https://solviqlab.com/es/calorie-deficit-calculator`,
      pt: `https://solviqlab.com/pt/calorie-deficit-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Calorie Deficit Calculator — How Many Calories to Lose Weight',
        description: 'Calculate the exact calorie deficit needed to reach your weight loss goal. Based on TDEE with safe deficit recommendations from nutritionists.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Calorie Deficit Calculator — How Many Calories to Lose Weight',
        description: 'Calculate the exact calorie deficit needed to reach your weight loss goal. Based on TDEE with safe deficit recommendations from nutritionists.',
        keywords: 'calorie deficit calculator',
        url: canonical,
      },
    ],
  }
}
