// Auto-generated by CALCO Factory
import type { AverageCalculatorOutput } from './lib/types.js'

export function getInterpretation(_output: AverageCalculatorOutput, _lang = 'en'): string {
  return ''
}
