// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/average-calculator`

  return {
    title: 'Average Calculator — Mean, Median, Mode & More',
    description: 'Calculate mean, median, mode, range, and standard deviation from any list of numbers. Instant statistics for students and professionals.',
    canonical,
    ogImage: `https://solviqlab.com/og/average-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/average-calculator`,
      es: `https://solviqlab.com/es/average-calculator`,
      pt: `https://solviqlab.com/pt/average-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Average Calculator — Mean, Median, Mode & More',
        description: 'Calculate mean, median, mode, range, and standard deviation from any list of numbers. Instant statistics for students and professionals.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Average Calculator — Mean, Median, Mode & More',
        description: 'Calculate mean, median, mode, range, and standard deviation from any list of numbers. Instant statistics for students and professionals.',
        keywords: 'average calculator',
        url: canonical,
      },
    ],
  }
}
