// Auto-generated by CALCO Factory
import type { BmrCalculatorInput, BmrCalculatorOutput } from './types.js'

export function calculateBmrCalculator(input: BmrCalculatorInput): BmrCalculatorOutput {
  const { weight, height, age, sex } = input
  // Mifflin-St Jeor Equation (most accurate for general population)
const base = (10 * weight) + (6.25 * height) - (5 * age)
const bmr = sex === 'male' ? base + 5 : base - 161
return { bmr: Math.round(bmr) }
}
