// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface BmrCalculatorInput {
  weight: number
  height: number
  age: number
  sex: 'male' | 'female'
}

export interface BmrCalculatorOutput {
  bmr: number
}
