// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { BmrCalculatorInput } from './types.js'

export const bmrCalculatorSchema = z.object({
  weight: z.number().min(20).max(300),
  height: z.number().min(100).max(250),
  age: z.number().min(15).max(100),
  sex: z.enum(['male', 'female']),
})

export type { BmrCalculatorInput }

export function validate(raw: unknown): BmrCalculatorInput {
  return bmrCalculatorSchema.parse(raw) as BmrCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: BmrCalculatorInput } | { success: false; errors: string[] } {
  const result = bmrCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as BmrCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
