// Auto-generated by CALCO Factory
import type { RatioCalculatorInput, RatioCalculatorOutput } from './types.js'

export function calculateRatioCalculator(input: RatioCalculatorInput): RatioCalculatorOutput {
  const { a, b, c } = input
  function gcd(x: number, y: number): number { return y === 0 ? Math.abs(x) : gcd(y, x % y) }
const g = gcd(Math.round(a), Math.round(b))
const simplifiedA = a / g
const simplifiedB = b / g
const d = c !== undefined && c !== null ? (c * b) / a : 0
const decimal = Math.round(a / b * 1_000_000) / 1_000_000
return { simplifiedA: Math.round(simplifiedA * 10000) / 10000, simplifiedB: Math.round(simplifiedB * 10000) / 10000, d: Math.round(d * 10000) / 10000, decimal }
}
