// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface RatioCalculatorInput {
  a: number
  b: number
  c?: number
}

export interface RatioCalculatorOutput {
  simplifiedA: number
  simplifiedB: number
  d: number
  decimal: number
}
