// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { RatioCalculatorInput } from './types.js'

export const ratioCalculatorSchema = z.object({
  a: z.number().min(-1e9).max(1e9),
  b: z.number().min(-1e9).max(1e9).refine(v => v !== 0, 'B cannot be zero'),
  c: z.number().min(-1e9).max(1e9).optional(),
})

export type { RatioCalculatorInput }

export function validate(raw: unknown): RatioCalculatorInput {
  return ratioCalculatorSchema.parse(raw) as RatioCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: RatioCalculatorInput } | { success: false; errors: string[] } {
  const result = ratioCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as RatioCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
