// Auto-generated by CALCO Factory
import type { CompoundInterestCalculatorOutput } from './lib/types.js'

export function getInterpretation(_output: CompoundInterestCalculatorOutput, _lang = 'en'): string {
  return ''
}
