// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/compound-interest-calculator`

  return {
    title: 'Compound Interest Calculator — Watch Your Money Grow',
    description: 'Calculate compound interest over time with monthly contributions. See how your investment grows year by year with the power of compounding.',
    canonical,
    ogImage: `https://solviqlab.com/og/compound-interest-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/compound-interest-calculator`,
      es: `https://solviqlab.com/es/compound-interest-calculator`,
      pt: `https://solviqlab.com/pt/compound-interest-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Compound Interest Calculator — Watch Your Money Grow',
        description: 'Calculate compound interest over time with monthly contributions. See how your investment grows year by year with the power of compounding.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Compound Interest Calculator — Watch Your Money Grow',
        description: 'Calculate compound interest over time with monthly contributions. See how your investment grows year by year with the power of compounding.',
        keywords: 'compound interest calculator',
        url: canonical,
      },
    ],
  }
}
