// Auto-generated by CALCO Factory
import type { WeightConverterOutput } from './lib/types.js'

export function getInterpretation(_output: WeightConverterOutput, _lang = 'en'): string {
  return ''
}
