// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/weight-converter`

  return {
    title: 'Weight Converter — kg, lbs, oz, stones and more',
    description: 'Convert weight between kilograms, pounds, ounces, stones, grams, and tons. Instant and accurate weight unit converter.',
    canonical,
    ogImage: `https://solviqlab.com/og/weight-converter.png`,
    alternates: {
      en: `https://solviqlab.com/en/weight-converter`,
      es: `https://solviqlab.com/es/weight-converter`,
      pt: `https://solviqlab.com/pt/weight-converter`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Weight Converter — kg, lbs, oz, stones and more',
        description: 'Convert weight between kilograms, pounds, ounces, stones, grams, and tons. Instant and accurate weight unit converter.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Weight Converter — kg, lbs, oz, stones and more',
        description: 'Convert weight between kilograms, pounds, ounces, stones, grams, and tons. Instant and accurate weight unit converter.',
        keywords: 'weight converter',
        url: canonical,
      },
    ],
  }
}
