// Auto-generated by CALCO Factory
import type { ScientificNotationCalculatorOutput } from './lib/types.js'

const BUCKETS = [
  {
    "key": "small",
    "label": "Very Small",
    "range": "< 0.001",
    "interpretation": "Very small number, scientific notation useful for readability."
  },
  {
    "key": "normal",
    "label": "Normal Range",
    "range": "0.001–999999",
    "interpretation": "Standard range, scientific notation optional."
  },
  {
    "key": "large",
    "label": "Very Large",
    "range": "> 999999",
    "interpretation": "Very large number — scientific notation essential."
  }
]

export function getInterpretation(output: ScientificNotationCalculatorOutput, _lang = 'en'): string {
  // Return first matching bucket interpretation
  // Instruments override this with specific logic
  const firstOutput = Object.values(output as Record<string, unknown>)[0]
  if (typeof firstOutput === 'string') {
    const bucket = BUCKETS.find(b => b.key === firstOutput)
    return bucket?.interpretation ?? ''
  }
  return BUCKETS[0]?.interpretation ?? ''
}
