// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/scientific-notation-calculator`

  return {
    title: 'Scientific Notation Calculator — Convert & Calculate',
    description: 'Convert numbers to and from scientific notation. Add, subtract, multiply and divide numbers in scientific notation instantly.',
    canonical,
    ogImage: `https://solviqlab.com/og/scientific-notation-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/scientific-notation-calculator`,
      es: `https://solviqlab.com/es/scientific-notation-calculator`,
      pt: `https://solviqlab.com/pt/scientific-notation-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Scientific Notation Calculator — Convert & Calculate',
        description: 'Convert numbers to and from scientific notation. Add, subtract, multiply and divide numbers in scientific notation instantly.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Scientific Notation Calculator — Convert & Calculate',
        description: 'Convert numbers to and from scientific notation. Add, subtract, multiply and divide numbers in scientific notation instantly.',
        keywords: 'scientific notation calculator',
        url: canonical,
      },
    ],
  }
}
