// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/vat-calculator`

  return {
    title: 'VAT Calculator — Add or Remove VAT Instantly',
    description: 'Add or remove VAT from any price. Supports all VAT rates (5%, 10%, 15%, 20%, 21%, 25%). Instant calculation for businesses and consumers.',
    canonical,
    ogImage: `https://solviqlab.com/og/vat-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/vat-calculator`,
      es: `https://solviqlab.com/es/vat-calculator`,
      pt: `https://solviqlab.com/pt/vat-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'VAT Calculator — Add or Remove VAT Instantly',
        description: 'Add or remove VAT from any price. Supports all VAT rates (5%, 10%, 15%, 20%, 21%, 25%). Instant calculation for businesses and consumers.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'VAT Calculator — Add or Remove VAT Instantly',
        description: 'Add or remove VAT from any price. Supports all VAT rates (5%, 10%, 15%, 20%, 21%, 25%). Instant calculation for businesses and consumers.',
        keywords: 'vat calculator',
        url: canonical,
      },
    ],
  }
}
