// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/loan-calculator`

  return {
    title: 'Loan Calculator — Monthly Payment & Total Interest',
    description: 'Calculate your monthly loan payment, total interest paid, and full amortization schedule. Works for personal loans, auto loans, and more.',
    canonical,
    ogImage: `https://solviqlab.com/og/loan-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/loan-calculator`,
      es: `https://solviqlab.com/es/loan-calculator`,
      pt: `https://solviqlab.com/pt/loan-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Loan Calculator — Monthly Payment & Total Interest',
        description: 'Calculate your monthly loan payment, total interest paid, and full amortization schedule. Works for personal loans, auto loans, and more.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Loan Calculator — Monthly Payment & Total Interest',
        description: 'Calculate your monthly loan payment, total interest paid, and full amortization schedule. Works for personal loans, auto loans, and more.',
        keywords: 'loan calculator',
        url: canonical,
      },
    ],
  }
}
