// Auto-generated by CALCO Factory
import type { FractionCalculatorInput, FractionCalculatorOutput } from './types.js'

export function calculateFractionCalculator(input: FractionCalculatorInput): FractionCalculatorOutput {
  const { numerator1, denominator1, operation, numerator2, denominator2 } = input
  function gcd(a: number, b: number): number { return b === 0 ? Math.abs(a) : gcd(b, a % b) }
let n: number, d: number
if (operation === 'add') { n = numerator1 * denominator2 + numerator2 * denominator1; d = denominator1 * denominator2 }
else if (operation === 'subtract') { n = numerator1 * denominator2 - numerator2 * denominator1; d = denominator1 * denominator2 }
else if (operation === 'multiply') { n = numerator1 * numerator2; d = denominator1 * denominator2 }
else { n = numerator1 * denominator2; d = denominator1 * numerator2 }
const g = gcd(n, d)
const resultNumerator = n / g
const resultDenominator = d / g
return { resultNumerator, resultDenominator, decimal: Math.round(resultNumerator / resultDenominator * 1_000_000) / 1_000_000 }
}
