// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface FractionCalculatorInput {
  numerator1: number
  denominator1: number
  operation: 'add' | 'subtract' | 'multiply' | 'divide'
  numerator2: number
  denominator2: number
}

export interface FractionCalculatorOutput {
  resultNumerator: number | string
  resultDenominator: number | string
  decimal: number
}
