// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { FractionCalculatorInput } from './types.js'

export const fractionCalculatorSchema = z.object({
  numerator1: z.number().min(-10000).max(10000),
  denominator1: z.number().min(-10000).max(10000).refine(v => v !== 0, 'Denominator cannot be zero'),
  operation: z.enum(['add', 'subtract', 'multiply', 'divide']),
  numerator2: z.number().min(-10000).max(10000),
  denominator2: z.number().min(-10000).max(10000).refine(v => v !== 0, 'Denominator cannot be zero'),
})

export type { FractionCalculatorInput }

export function validate(raw: unknown): FractionCalculatorInput {
  return fractionCalculatorSchema.parse(raw) as FractionCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: FractionCalculatorInput } | { success: false; errors: string[] } {
  const result = fractionCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as FractionCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
