// Auto-generated by CALCO Factory
import type { TemperatureConverterOutput } from './lib/types.js'

const BUCKETS = [
  {
    "key": "freezing",
    "label": "Freezing",
    "range": "< 0°C",
    "interpretation": "Below freezing point of water."
  },
  {
    "key": "cold",
    "label": "Cold",
    "range": "0–10°C",
    "interpretation": "Cold weather conditions."
  },
  {
    "key": "comfortable",
    "label": "Comfortable",
    "range": "18–24°C",
    "interpretation": "Ideal room temperature."
  },
  {
    "key": "hot",
    "label": "Hot",
    "range": "> 35°C",
    "interpretation": "Very hot conditions."
  }
]

export function getInterpretation(output: TemperatureConverterOutput, _lang = 'en'): string {
  // Return first matching bucket interpretation
  // Instruments override this with specific logic
  const firstOutput = Object.values(output as Record<string, unknown>)[0]
  if (typeof firstOutput === 'string') {
    const bucket = BUCKETS.find(b => b.key === firstOutput)
    return bucket?.interpretation ?? ''
  }
  return BUCKETS[0]?.interpretation ?? ''
}
