// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/temperature-converter`

  return {
    title: 'Temperature Converter — Celsius, Fahrenheit, Kelvin',
    description: 'Convert temperature between Celsius, Fahrenheit, Kelvin, and Rankine instantly. The most accurate free temperature converter online.',
    canonical,
    ogImage: `https://solviqlab.com/og/temperature-converter.png`,
    alternates: {
      en: `https://solviqlab.com/en/temperature-converter`,
      es: `https://solviqlab.com/es/temperature-converter`,
      pt: `https://solviqlab.com/pt/temperature-converter`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Temperature Converter — Celsius, Fahrenheit, Kelvin',
        description: 'Convert temperature between Celsius, Fahrenheit, Kelvin, and Rankine instantly. The most accurate free temperature converter online.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Temperature Converter — Celsius, Fahrenheit, Kelvin',
        description: 'Convert temperature between Celsius, Fahrenheit, Kelvin, and Rankine instantly. The most accurate free temperature converter online.',
        keywords: 'temperature converter',
        url: canonical,
      },
    ],
  }
}
