// Auto-generated by CALCO Factory
import type { VolumeCalculatorInput, VolumeCalculatorOutput } from './types.js'

export function calculateVolumeCalculator(input: VolumeCalculatorInput): VolumeCalculatorOutput {
  const { shape, a, b, h } = input
  const bVal = b ?? a
const hVal = h ?? a
let volume: number
if (shape === 'cube') volume = a ** 3
else if (shape === 'sphere') volume = (4/3) * Math.PI * a ** 3
else if (shape === 'cylinder') volume = Math.PI * a ** 2 * hVal
else if (shape === 'cone') volume = (1/3) * Math.PI * a ** 2 * hVal
else volume = a * bVal * hVal
return { volume: Math.round(volume * 10000) / 10000 }
}
