// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface VolumeCalculatorInput {
  shape: 'cube' | 'sphere' | 'cylinder' | 'cone' | 'rectangular_prism'
  a: number
  b?: number
  h?: number
}

export interface VolumeCalculatorOutput {
  volume: number
}
