// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { VolumeCalculatorInput } from './types.js'

export const volumeCalculatorSchema = z.object({
  shape: z.enum(['cube', 'sphere', 'cylinder', 'cone', 'rectangular_prism']),
  a: z.number().min(0).max(1e9),
  b: z.number().min(0).max(1e9).optional(),
  h: z.number().min(0).max(1e9).optional(),
})

export type { VolumeCalculatorInput }

export function validate(raw: unknown): VolumeCalculatorInput {
  return volumeCalculatorSchema.parse(raw) as VolumeCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: VolumeCalculatorInput } | { success: false; errors: string[] } {
  const result = volumeCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as VolumeCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
