// Auto-generated by CALCO Factory
import type { VolumeConverterInput, VolumeConverterOutput } from './types.js'

export function calculateVolumeConverter(input: VolumeConverterInput): VolumeConverterOutput {
  const { value, fromUnit } = input
  const toLiters: Record<string, number> = {
  l: 1, ml: 0.001, cl: 0.01, m3: 1000, cm3: 0.001,
  gal: 3.78541, qt: 0.946353, pt: 0.473176, cup: 0.236588,
  floz: 0.0295735, tbsp: 0.0147868, tsp: 0.00492892, ft3: 28.3168, in3: 0.0163871,
}
const inLiters = value * (toLiters[fromUnit] ?? 1)
const r = (v: number, d: number) => Math.round(v * Math.pow(10, d)) / Math.pow(10, d)
return {
  liters: r(inLiters, 4),
  milliliters: r(inLiters * 1000, 2),
  gallons: r(inLiters / 3.78541, 4),
  cups: r(inLiters / 0.236588, 4),
  fluidOunces: r(inLiters / 0.0295735, 3),
}
}
