// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface VolumeConverterInput {
  value: number
  fromUnit: 'l' | 'ml' | 'cl' | 'm3' | 'cm3' | 'gal' | 'qt' | 'pt' | 'cup' | 'floz' | 'tbsp' | 'tsp' | 'ft3' | 'in3'
}

export interface VolumeConverterOutput {
  liters: number
  milliliters: number
  gallons: number
  cups: number
  fluidOunces: number
}
