// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { VolumeConverterInput } from './types.js'

export const volumeConverterSchema = z.object({
  value: z.number().min(0).max(1e12),
  fromUnit: z.enum(['l', 'ml', 'cl', 'm3', 'cm3', 'gal', 'qt', 'pt', 'cup', 'floz', 'tbsp', 'tsp', 'ft3', 'in3']),
})

export type { VolumeConverterInput }

export function validate(raw: unknown): VolumeConverterInput {
  return volumeConverterSchema.parse(raw) as VolumeConverterInput
}

export function safeValidate(raw: unknown): { success: true; data: VolumeConverterInput } | { success: false; errors: string[] } {
  const result = volumeConverterSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as VolumeConverterInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
