// Auto-generated by CALCO Factory
import type { DiscountCalculatorInput, DiscountCalculatorOutput } from './types.js'

export function calculateDiscountCalculator(input: DiscountCalculatorInput): DiscountCalculatorOutput {
  const { originalPrice, discountPercent } = input
  const discountAmount = Math.round(originalPrice * discountPercent / 100 * 100) / 100
const finalPrice = Math.round((originalPrice - discountAmount) * 100) / 100
return { discountAmount, finalPrice }
}
