// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface DiscountCalculatorInput {
  originalPrice: number
  discountPercent: number
}

export interface DiscountCalculatorOutput {
  discountAmount: number
  finalPrice: number
}
