// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { DiscountCalculatorInput } from './types.js'

export const discountCalculatorSchema = z.object({
  originalPrice: z.number().min(0).max(1_000_000_000),
  discountPercent: z.number().min(0).max(100),
})

export type { DiscountCalculatorInput }

export function validate(raw: unknown): DiscountCalculatorInput {
  return discountCalculatorSchema.parse(raw) as DiscountCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: DiscountCalculatorInput } | { success: false; errors: string[] } {
  const result = discountCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as DiscountCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
