// Auto-generated by CALCO Factory
import type { ScientificNotationCalculatorInput, ScientificNotationCalculatorOutput } from './types.js'

export function calculateScientificNotationCalculator(input: ScientificNotationCalculatorInput): ScientificNotationCalculatorOutput {
  const { value } = input
  if (value === 0) return { coefficient: 0, exponent: 0, scientific: '0', engineering: '0' }
const exponent = Math.floor(Math.log10(Math.abs(value)))
const coefficient = Math.round(value / Math.pow(10, exponent) * 1_000_000) / 1_000_000
const engExp = Math.floor(exponent / 3) * 3
const engCoef = Math.round(value / Math.pow(10, engExp) * 1_000_000) / 1_000_000
return {
  coefficient,
  exponent,
  scientific: `${coefficient} × 10^${exponent}`,
  engineering: `${engCoef} × 10^${engExp}`,
}
}
