// Auto-generated by CALCO Factory — do not edit manually
// Source: packages/instrument-intelligence/src/factory/code-generator.ts

export interface ScientificNotationCalculatorInput {
  value: number
}

export interface ScientificNotationCalculatorOutput {
  coefficient: number
  exponent: number | string
  scientific: number | string
  engineering: number | string
}
