// Auto-generated by CALCO Factory
import { z } from 'zod'
import type { ScientificNotationCalculatorInput } from './types.js'

export const scientificNotationCalculatorSchema = z.object({ value: z.number() })

export type { ScientificNotationCalculatorInput }

export function validate(raw: unknown): ScientificNotationCalculatorInput {
  return scientificNotationCalculatorSchema.parse(raw) as ScientificNotationCalculatorInput
}

export function safeValidate(raw: unknown): { success: true; data: ScientificNotationCalculatorInput } | { success: false; errors: string[] } {
  const result = scientificNotationCalculatorSchema.safeParse(raw)
  if (result.success) return { success: true, data: result.data as ScientificNotationCalculatorInput }
  return { success: false, errors: result.error.errors.map(e => e.message) }
}
