// Auto-generated by CALCO Factory
import type { DiscountCalculatorOutput } from './lib/types.js'

export function getInterpretation(_output: DiscountCalculatorOutput, _lang = 'en'): string {
  return ''
}
