// Auto-generated by CALCO Factory

export interface SEOMetadata {
  title: string
  description: string
  canonical: string
  ogImage: string
  alternates: Record<string, string>
  structuredData: unknown[]
}

export function getSEOMetadata(lang = 'en'): SEOMetadata {
  const canonical = `https://solviqlab.com/${lang}/discount-calculator`

  return {
    title: 'Discount Calculator — Final Price After Discount',
    description: 'Calculate the final price after applying any discount percentage. Also calculates how much you save and the effective discount rate.',
    canonical,
    ogImage: `https://solviqlab.com/og/discount-calculator.png`,
    alternates: {
      en: `https://solviqlab.com/en/discount-calculator`,
      es: `https://solviqlab.com/es/discount-calculator`,
      pt: `https://solviqlab.com/pt/discount-calculator`,
    },
    structuredData: [
      {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'Discount Calculator — Final Price After Discount',
        description: 'Calculate the final price after applying any discount percentage. Also calculates how much you save and the effective discount rate.',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        name: 'Discount Calculator — Final Price After Discount',
        description: 'Calculate the final price after applying any discount percentage. Also calculates how much you save and the effective discount rate.',
        keywords: 'discount calculator',
        url: canonical,
      },
    ],
  }
}
